### ISSUE TITLE
How to display the favicon to the page as well as display comment option on blog?

### ISSUE THREAD

**Issue by SilverFoxA** [daattali/beautiful-jekyll#10]
I tried the library and has successfully modified to my need but currently i'm facing little bit of problem in adding the favicon as well as displaying the comments or even a field to type in the comment. 
Please let me know if I am doing anything wrong.
Here is the url: http://silverfoxa.github.io/

Moreover when I try to host the same repo in terms of a project it shows error hence says the site does
not exits .i.e i wanted to make the url as http://silverfoxa.github.io/project but the following did not work for me.

**Comment by daattali** [comment]
- it looks like the favicon works

- if you want users to be able to leave comments on posts, [there is a section about it in my README](https://github.com/daattali/beautiful-jekyll#letting-users-leave-comments).  I just looked at your _config.yml file and it seems like you didn't provide a disqus id

- If you want the page `http://silverfoxa.github.io/project` to work then you need to have a repository named `project` and make a branch called `gh-pages` and copy the code into that branch. You should read up on GitHub User vs Project Pages if you don't understand this

**Comment by SilverFoxA** [comment]
sorry to say but there's no `disqus` parameter within the `_config.yml` file

**Comment by daattali** [comment]
Yes there is, line 66 in your current config file

https://github.com/SilverFoxA/silverfoxa.github.io/blob/master/_config.yml#L66

**Comment by SilverFoxA** [comment]
Thank you i have got it, It was commented so couldn't find it and thanks for this awesome easy to use library, Would love see few updates though regarding the theme

**Comment by daattali** [comment]
If you have suggestions for improvements that will benefit other people, then you're welcome to open an issue for that

**Comment by SilverFoxA** [comment]
Sorry to bug you  but what do you mean by the "disqus shortname not id", its the username right? i.e. https://disqus.com/by/"name here"/

**Comment by daattali** [comment]
No, not the username.  Look up "disqus shortname"

https://help.disqus.com/customer/portal/articles/466208

**Comment by SilverFoxA** [comment]
Thank you got it done :)

**Comment by rfitz9** [comment]
I would love to know how you were able to utilize a favicon

**Comment by jashrathod** [comment]
I have added the favicon.png file. I'm able to view it on the home page but not "About" page or any of the posts.

You can find the code here: https://github.com/jashrathod/jashrathod.github.io
