### ISSUE TITLE
Feature request: Edit in GitHub link/button

### ISSUE THREAD

**Issue by dagnelies** [daattali/beautiful-jekyll#1004]
Hi, 

First, thanks for this beautiful theme. The only thing I miss is a "Edit in GitHub" link or button on the pages. This would be a nice addition.

**Comment by daattali** [comment]
That's a good idea. I'll have to think of a way to incorporate that into the UI in a sensible way and take into account that not all usages of beautiful-jekyll are on github.

**Comment by daattali** [comment]
It's not perfect though, if anyone wants to improve it, I'd be happy to accept PRs. For example, if you're on a page that doesn't actually exist on github, it'll still show this button but take you to a 404 page. For example, if you navigate to the second page of the blog/feed, it'll try to go to a page called "page2/index.html" in your github repo.

**Comment by dagnelies** [comment]
Amazing 😲  🎉 I didn't expected you to implement that so quickly, impressive!
I'm gonna try it out right now.

**Comment by dagnelies** [comment]
Nice, works great, thanks!
