### ISSUE TITLE
Moving Blog to another Page

### ISSUE THREAD

**Issue by wittedhaddock** [daattali/beautiful-jekyll#102]
Taking the blog-emitting src from index.html ([this stuff](https://gist.github.com/wittedhaddock/916c24bd193d339593c9611167a4df26)), and moving it to a new page, say blog.html, results in no post-html to be emitted:

```
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="posts-list">
  
</div>


	    
    </div>
  </div>
</div>
```

Moving it back to the root index.html, and running `jekyll serve` then properly emits all blog-related HTML.

What is intrinsic to the root index.html that allows blog-html to be emitted? How can I transfer this logic to another page, blog.html?

Thank you so much! 

James

**Comment by daattali** [comment]
To have the blog hosted on a different URL, add the pagination HTML into a different page, for example under "blog/index.html", and in the config file you need to modify the `paginate_path`, for example `paginate_path: "/blog/page:num/"`
