### ISSUE TITLE
Blog post not generated with Next Page/ Previous Page widget

### ISSUE THREAD

**Issue by mbusb** [daattali/beautiful-jekyll#103]
Hi daattali,

Thanks for the beautiful-jekyll and making it easy for newcomers like me.  I am trying to build a simple site for my project with your theme. My intension is to create few static pages and a blog page for release announcement. I have hosted it in this link https://github.com/mbusb/mbusb.github.io. 

If you build and browse a site, all seems to be ok. But I am finding it difficult to generate a 'News' (blog) page with the "Read More", "Next Page" and "Previous Page" widgets which you normally see in your [demo](http://deanattali.com/beautiful-jekyll/) site. Right now my page_news.md content looks like [this](https://raw.githubusercontent.com/mbusb/mbusb.github.io/master/page_news.md) which generates a posts with long list (without above widgets). If I copy  your "index.html" code to my "page_news.md" does not generate any post at all. 

I have looked at codes of various "Success Stories" sites from your repo but I could not get what I wanted. Is there anything which I am missing in my project files? 

Any help is appreciated.

**Comment by daattali** [comment]
This is purely a jekyll issue, you can read the jekyll docs to understand how Blog posts+page works. Somebody else asked about this exact same issue yesterday so you can see what he did and my response - it should help you https://github.com/daattali/beautiful-jekyll/issues/102

If that doesn't help you enough, try reading the following two jekyll pages: https://jekyllrb.com/docs/posts/#displaying-an-index-of-posts and https://jekyllrb.com/docs/pagination/

**Comment by mbusb** [comment]
Thanks for the input. If you know that you have some solution for a problem (faced by many users) then why don't you include in the documentation. I have wasted lot of time to figure out what is the problem with the code.

Meanwhile my site is up and running. Very simple site which you can include in list of featured site, if you wish.

Once again thanks for your work.

**Comment by daattali** [comment]
It's not a problem faced by many users, only two people have ever asked
about this and both coincidentally happened this week, just by chance :)
 The documentation I provide is fairly extensive and I try not to bloat it
with info that's not useful to  a lot of people, I add to it when I see
many people facing a problem

---
http://deanattali.com
