### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by mrmccormack** [daattali/beautiful-jekyll#104]
Thanks for repostitory.

I've been working for a long time - trying to get syntax highlighting
on GitHub pages working. It never seems to work.

Any help would be appreciated.

I forked your beautiful-jekyll
http://mrmccormack.me/aboutme/

It works when previewing the .md file in repository... but not on compiled GitHub pages.

Here's what I added:

# Here is some sample colored code 

```html
<strong>hello world</strong>

```
# Test

{% highlight html%}
  hello world
{% endhighlight %}

# Another test

```scala
def test(i: Int): Unit = {
   println(i)
 }
```

```

**Comment by daattali** [comment]
I just went to your page and I do see syntax highlighting. I'm not sure what the problem is?

**Comment by mrmccormack** [comment]
Thanks for fast reply.

I added more syntax, and it is working now... not sure what it was... I did notice some compilation errors when I was testing (GitHub) Site.

I'll close this issue, sorry for trouble.
Rob
