### ISSUE TITLE
Use either `const` or `let` instead of `var` in JS

### ISSUE THREAD

**Issue by VincentTam** [daattali/beautiful-jekyll#1048]
The title says it all.  The rationale behind is due to the global scope of a `var`.  That's deprecated syntax.

References:

1. https://threejs.org/manual/#en/prerequisites
2. https://dev.to/paritho/3-reasons-to-use-var-in-javascript-1hoe

**Comment by daattali** [comment]
That's a good idea, if anyone wants to submit a PR I'd be happy to accept

**Comment by daattali** [comment]
fixed https://github.com/daattali/beautiful-jekyll/commit/47e87ef720322019a630ea7b21b3204163b14347
