### ISSUE TITLE
About comment_Function addition

### ISSUE THREAD

**Issue by Buppong** [daattali/beautiful-jekyll#1057]
excuse me, i didn't use well about github blog that i did try to add to comment  function but i didn't SO i need to advise me ,disqus function .  when i did to try  i have face to problem about github action issue about update node16 version and pause action. Where should I add the function to operate normally?

Thank you

**Comment by daattali** [comment]
I don't understand the question. Please try to re word your question.

**Comment by Buppong** [comment]
i got it. i want to add comment function on my blog what should i do? sorry eng isn't well .

**Comment by Buppong** [comment]
First of all, I am sorry that my English is difficult to explain well. 
the present state of problems

1. I wanted to add a comment function by disqus
2.  i did modify to config.xml file  , i went to the disqus homepage and i've done
3.  by the way i watched to my github action i found to problem ,  this is stopped working 
maybe, I corrected it wrong , 
what should i do . 
i need to  advice , sir  

thank you

**Comment by daattali** [comment]
I'm sorry but I ca'nt tell you what you did wrong -- this forum is for reporting bugs, not for getting personal help. For support you can try the [Discussions](https://github.com/daattali/beautiful-jekyll/discussions) section or ask for help on other online jekyll forums.
