### ISSUE TITLE
navbar & footer line color

### ISSUE THREAD

**Issue by catches** [daattali/beautiful-jekyll#1074]
So I changed the color, but the navbar & footer seems to have this white border that doesn't change with it:
![image](https://user-images.githubusercontent.com/105005455/210214734-4c488166-f727-4f68-ba8b-6bf13481ae17.png)
![image](https://user-images.githubusercontent.com/105005455/210214746-d22e6c66-473d-4a4b-9dbb-c0547f54b2b7.png)

**Comment by daattali** [comment]
If you're using a version of beautifuljekyll that's not extremely old, then that the top line can be changed with the "navbar-border-col" parameter, you can see it here https://github.com/daattali/beautiful-jekyll/blob/6ad1fcd87b73dc6e58e7ac5761ce3151b3c39478/_config.yml#L130

The footer line doesn't have a built-in parameter, you'll have to use custom CSS to change that.
