### ISSUE TITLE
Actions failing on a fresh fork

### ISSUE THREAD

**Issue by SamErde** [daattali/beautiful-jekyll#1077]
The Builk Jekyll action is failing with the following error. Has this project fallen behind supported versions, or have I hit a different issue?

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by daattali** [comment]
I'm not seeing the failure. I tried pushing a new commit to this repo and it passes: https://github.com/daattali/beautiful-jekyll/commit/848d04c90ac87555ccbd00797ce26ee2bd92ecdf

I also tried forking and still no error: https://github.com/daattalitest/daattalitest.github.io/commit/7ae6b48a3104731bb6c78ec76d65c2153e4417fc

That said, I'd be happy to update the versions, feel free to submit a PR

**Comment by SamErde** [comment]
I must have been messing something up. The error happened with two separate forks, but after a fresh one, it's all working fine again.
