### ISSUE TITLE
Remove Blog picture at Home page

### ISSUE THREAD

**Issue by catches** [daattali/beautiful-jekyll#1078]
yo, quick question, how would you remove the small picture to the right at the home page, but still have a image up once you open up the blog itself? thanks
![image](https://user-images.githubusercontent.com/105005455/211151473-87cfe050-32a6-41a9-956b-c0e4c9a16fed.png)

**Comment by daattali** [comment]
Look at the supported parameters section of the README, specifically at the thumbnail https://github.com/daattali/beautiful-jekyll#supported-parameters
