### ISSUE TITLE
quick question about /img/start.jpg and /img/path.jpg

### ISSUE THREAD

**Issue by facelesspanda** [daattali/beautiful-jekyll#108]
Hi.

I get what the `404-southpark.jpg` is (though I don't get why it's not simply called `404.jpg`), I get what the `avatar-icon.png` is. But what are the other two images, `path` and `start`? They're not used in the sample posts, they're not used in the readme, and I haven't seen them in the layouts or includes... what are they?

**Comment by daattali** [comment]
Thank you for your comment. The path image is actually used in one of the sample posts (in the master branch) and the start image is used in a page on the gh-pages branch

**Comment by facelesspanda** [comment]
Okay thanks, missed that.
