### ISSUE TITLE
Boxes style does not work

### ISSUE THREAD

**Issue by amosnothing** [daattali/beautiful-jekyll#1090]
https://amosnothing.github.io/aboutme/
![image](https://user-images.githubusercontent.com/24653016/215028897-c24d71fc-9a00-4948-a007-1d703db008dc.png)

**Comment by daattali** [comment]
The text of the box needs to go in a new line, like you see in the example https://github.com/daattali/beautiful-jekyll/blob/848d04c90ac87555ccbd00797ce26ee2bd92ecdf/_posts/2020-02-28-test-markdown.md?plain=1#L67-L68
