### ISSUE TITLE
Phantom posts showing, but no files in repo

### ISSUE THREAD

**Issue by craigvear** [daattali/beautiful-jekyll#1094]
Two new blogs have added themselves to my research project blog, but there is no sign of these files in the repo docs. the content of these does exist in other posts, but the titles don’t show up in any searches. Is there a json I need to clean up?

https://digiscore.github.io

**Comment by daattali** [comment]
I'm not sure what you're doing exactly, but it does seem like you somehow created these two pages. Looking at the HTML of your page, I see that those two are pointing to https://digiscore.github.io/2023-02-04-2021-11-26-The_Digital_Score_Book_&-8211;_Craig_Vear/ and https://digiscore.github.io/2023-02-04-2022-10-11-Impact_case_study-_Digital_Syzygies/ which are both pages that you must have created.

**Comment by daattali** [comment]
I closed this issue because there is no bug here with this project. You might need more help to sort your situation, but that should be done via a different channel, a jekyll help forum.

**Comment by craigvear** [comment]
Hi Dean, found the problem:

two of my blogs were reporting a mapping issue because of a colon in the title of a blog

"title: The Digital Score Book: Craig Vear"

This created an error, but didnt stop the code from being published AND created a phantom post. All clear now.

regards
craig
