### ISSUE TITLE
Google Analytics 4 support?

### ISSUE THREAD

**Issue by alainassaf** [daattali/beautiful-jekyll#1096]
Hello,

Is anything special needed to update a beautiful-jekyll site to use Google Analytics 4? 

Thanks,
Alain

**Comment by leabs** [comment]
From what I've read, you should not need to update anything to get GA working on a site using this theme. Simply uncomment the `gtag: ""` line in your `_config.yml` with your gtag and rebuild the site. 

If you **_did_** want to replace the GA3 tag with the new GA4 tag, it's being rendered in `beautiful-jekyll/_includes/google_analytics.html`

**Comment by sudohainguyen** [comment]
I did as you mentioned but still doesn't work @leabs

**Comment by leabs** [comment]
@alainassaf @sudohainguyen I just forked this repo and got GA4 working. 
Code repo here: https://github.com/leabs/beautiful-jekyll
Live site here: https://beautiful-analytics.vercel.app/

Steps I took:
Forked Repo
Added the `MEASUREMENT ID` as the  un commented `gtag` in `_config.yml`
Had to update jekyll for deployment
Pushed to vercel to host.

If you have a public repo I can look at it for you, but this should work.

<img width="639" alt="Screenshot 2023-02-21 at 10 27 05 AM" src="https://user-images.githubusercontent.com/7071812/220387123-68a40ece-811f-469e-853a-55e8c9cbac92.png">

<img width="494" alt="Screenshot 2023-02-21 at 10 22 59 AM" src="https://user-images.githubusercontent.com/7071812/220387030-4456fc47-d933-45d0-a1c6-7b896869cbeb.png">

**Comment by sudohainguyen** [comment]
this one 👁️ 
`https://github.com/sudohainguyen/sudohainguyen.github.io/blob/master/_config.yml`

**Comment by sudohainguyen** [comment]
now somehow it works to me 🤣  thanks!

**Comment by daattali** [comment]
Sorry I haven't been responsive, I've been busy with other open source projects. Beautiful Jekyll really does need to move to GA4. If anybody wants to make a PR for it, I'd be happy to get some help.

**Comment by daattali** [comment]
I was reading about google analytics 4 and realized that, as others here have mentioned, it's already supported, using the `gtag` field.

I will update the config file to make it clear that `google_analytics` is old and should not be used, and `gtag` is the one that should be used moving forward.
