### ISSUE TITLE
Several warnings (Gemfile dependencies and Node.js)

### ISSUE THREAD

**Issue by SwissOS** [daattali/beautiful-jekyll#1099]
Today I updated a page on my Github pages site (forked Beautiful-Jekyll) and got the following warning:
```github-pages can't satisfy your Gemfile's dependencies.```

And then in Build Jekyll:
```Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.```

I have no idea how to fix this, or even if it's important, as they are only warnings and the site update worked in the end.

**Comment by daattali** [comment]
Thanks for the report. Where did you get this message, was it emailed , or in Actions, or in github notifications?

That error message if pretty informative so I think I'll know how to fix it, but I want to replicate it before

**Comment by SwissOS** [comment]
Thanks for fixing the Node.js.

As for the gemfile issue, I am getting the warning when I update a page, then in the "Pages build and deployment" workflow report:

In the annotations section:
1 warning
  github-pages can't satisfy your Gemfile's dependencies.

**Comment by daattali** [comment]
That unfortunately I can't really help with. I'm not a ruby user, the gem stuff was mostly community-driven. If you're able to find the issue there I would be happy for a PR
