### ISSUE TITLE
Hackerrank link not showing

### ISSUE THREAD

**Issue by scotch83** [daattali/beautiful-jekyll#1110]
Using the remote theme in the config file the hackerrank social link is not showing, while it does if I copy the html.
Maybe forgot to deploy something?

**Comment by daattali** [comment]
It looks like you're using verions 5.0.0 (first line of your config file). You can see in the CHANGELOG https://github.com/daattali/beautiful-jekyll/blob/master/CHANGELOG.md that hackerrank was added afterwards, in the current "officially not yet released version". To use this newest vesion you'll need to remove the `@5.0.0` from that line.

**Comment by scotch83** [comment]
Thanks a lot! I tweaked it but this is definitely the issue. Maybe I can help back pointing you where I took the version, so you can adjust and avoid other issues like this.
🙏
https://beautifuljekyll.com/getstarted/#install-steps-hard
