### ISSUE TITLE
Cannot display color gradients

### ISSUE THREAD

**Issue by GyulyVGC** [daattali/beautiful-jekyll#1141]
`_config.yml` says  "Personalize the colours in your website. Colour values can be any valid CSS colour"

So I tried to set a linear color gradient: `navbar-col: "linear-gradient(45deg, rgba(12,95,198,1) 0%, rgba(233,132,27,1) 100%)"`

But it doesn't display the gradient (it displays transparent instead).

I've also tried with `navbar-col: "background: linear-gradient(45deg, rgba(12,95,198,1) 0%, rgba(233,132,27,1) 100%)"` but the result is the same.

I've already checked your FAQs and found nothing about that.

Thanks in advance for your support ❤️

**Comment by daattali** [comment]
That value does result in a colour but it's not technically a CSS colour. The config value goes into a `background-color` CSS property, which only supports legal colours. You can see the syntax definition of legal colours here https://www.w3schools.com/cssref/css_colors_legal.php

**Comment by GyulyVGC** [comment]
Is there any way I can manage to use gradients? Maybe including additional CSS files, right?

**Comment by daattali** [comment]
Yes you'll need to add a custom css file to overwrite. You can find the source here 
https://github.com/daattali/beautiful-jekyll/blob/8c1493387a0c3694e322437da703454bd28b0788/assets/css/beautifuljekyll.css#L126

**Comment by GyulyVGC** [comment]
Tyvm for the promptly answers and for the amazing template ❤️ 
Have a good day!
