### ISSUE TITLE
 Add more markdown compolents in "_data" 's subfolder

### ISSUE THREAD

**Issue by leijobs** [daattali/beautiful-jekyll#1153]
Hello, dear daattalli, thanks for your great work and I have forked your work and made my web, but I'm still a newbie to github pages and this project.  And I want add new components in `OFFICE HOURS` and `RESOURCES` in my web like the demo web `https://beautifuljekyll.com/`, so what I should do to link this titles with its compolents like several ‘.md’ blogs. Here is my web based on this project `https://leijobs.github.io/_posts/Projects/`, and I really want to add more markdown compolents in the 'Projects' section. Thanks!

**Comment by daattali** [comment]
It sounds like you're asking for help, rather than reporting an issue or a feature request. [You can get help from other places](https://beautifuljekyll.com/faq/#more)
