### ISSUE TITLE
Feature request: Support for svelte-kit

### ISSUE THREAD

**Issue by cyaris** [daattali/beautiful-jekyll#1173]
Would love to use `svelte-kit` within my `jekyll` blog. Have heard of this other solution called `svekyll` but the code isn't public.

**Comment by daattali** [comment]
I'm not sure what exactly you're asking for. What do you envision/what do you want to support exactly?

**Comment by cyaris** [comment]
I use a lot of d3 in my blog, and the syntax for d3 is a lot easier with `svelte-kit`. Was hoping for some combination of `jekyll` with `svelte-kit` so that github pages still uses `jekyll` for the theme and site structure, but the reactivity of `svelte` and components will also be possible.

**Comment by cyaris** [comment]
Here's an example of the syntax differences.

<img width="799" alt="Screenshot 2023-07-13 at 2 56 23 PM" src="https://github.com/daattali/beautiful-jekyll/assets/35279417/40795c35-96c1-4444-b29c-161ad066829c">

**Comment by daattali** [comment]
This is a github pages theme, which uses jekyll. It doesn't use svelte. I'm still not sure how you envision to use svelte within a github pages theme, you'll need to provide more details.

**Comment by cyaris** [comment]
If by forking the repo, there was a svelte configuration and package.json, that would allow for both Jekyll and .svelte files to work.

**Comment by daattali** [comment]
As someone who never used svelte, I simply don't understand how it would integrate with a jekyll theme. I would need to see a concrete example to understand. Regardless, I'd be happy to consider merging a pull request if you, or anyone else familiar with svelte, wants to help with that. Is that something you want to do?

**Comment by cyaris** [comment]
Sure! I'll try it out and see what I can come up with. May not be able to get to it for a few weeks but I won't forget either. Thanks!

**Comment by cyaris** [comment]
Hi @daattali. This blog post let me do everything I wanted. No pull request needed. Thanks!

https://codeandlife.com/2021/03/06/easy-to-embed-svelte-components/

**Comment by daattali** [comment]
Great to hear. Correct me if I'm wrong, but it doesn't look like this solution that you linked to would work in GitHub Pages?

**Comment by cyaris** [comment]
It's working locally. Is there a chance it won't render in github pages even if it works locally?

**Comment by cyaris** [comment]
The rollup function needs to be run each time you make an edit though.

**Comment by daattali** [comment]
This theme is focused on github pages, not on running jekyll locally. Many things don't work in github pages. I'm glad you were able to get it to work for your usecase, but this is not going to be applicable for the theme

**Comment by cyaris** [comment]
@daattali I'll let you know when I push to GitHub-pages and let you know if it rendered. Thanks!

**Comment by daattali** [comment]
It might render if you build it locally and push to github.

But it won't work when developed purely on github pages.

**Comment by cyaris** [comment]
Correct. It works if I build locally, and push to same repo as my github.io site. If I instead put the build in another repo and try to import/reference it, I get 403 errors. Any idea why that may be? Tried it in a public repo. Thanks @daattali.
