### ISSUE TITLE
Google Scholar link construction is broken

### ISSUE THREAD

**Issue by crypdick** [daattali/beautiful-jekyll#1187]
When I use `google-scholar: "4ODJ78oAAAAJ"`, it routes to a non-existent page: https://scholar.google.com/4ODJ78oAAAAJ.

I fixed this by setting `google-scholar: "citations?user=4ODJ78oAAAAJ"`, which correctly routes to https://scholar.google.com/citations?user=4ODJ78oAAAAJ

# Details
* I have merged the latest `master` into my fork
* My fork: https://github.com/crypdick/crypdick.github.io
* My site: richarddecal.com

**Comment by daattali** [comment]
Thanks for the report. Would you like to submit a pull request adding the `citations?user=`?
