### ISSUE TITLE
Post Header image option

### ISSUE THREAD

**Issue by vakesz** [daattali/beautiful-jekyll#1192]
I don't know if this is an option inside the premium version, but on my side I didn't like the thumbnail design on beautiful-jekyll, and created an option to have a horizontal header image for posts.

PR: https://github.com/vakesz/vkszblog/pull/5
The code is quite jank, so probably would require some optimizations.

Preview:
![image](https://github.com/daattali/beautiful-jekyll/assets/3627611/e4822fd7-ba05-4477-91e1-981734f2a52b)

-----------------------------
Please only submit feature suggestions or bug reports if you believe something is broken.

If you need help, you can attend the [Office Hours](https://beautifuljekyll.com/officehours) (only available for [sponsors](https://beautifuljekyll.com/plans/)).

**Comment by daattali** [comment]
That looks good, I'd be happy to introduce that to beautifuljekyll. The code would need to be very clean (for maintenability) and there would need to be a config parameter to specify whether the current behaviour should be used or if the thumbnail should be horizontal. The layout would need to be sure to look good on both desktops and mobile.

**Comment by vakesz** [comment]
The code I linked in the Issue as a PR link already scales within mobile, and desktop. But I know width set to 1000px(which gets limited by the post width) is not a nice solution but I haven't played much with CSS so it's mostly a grey area for me. 

Maybe one addition that would be nice to have an option like so:
```
# post-preview-style: header, thumbnail, header-mobile-thumbnail-desktop, none
# header: Header bar shown on post
# thumbnail: Thumbnail shown on post
# header-mobile-thumbnail-desktop: as the name suggests
# off: no pic on post
```

**Comment by daattali** [comment]
@vakesz do you want to submit a PR?

**Comment by daattali** [comment]
@vakesz this issue will be closed if no response

**Comment by vakesz** [comment]
Sorry for the delay. Surely if i'll get some more free time I would be happy to update it.

**Comment by daattali** [comment]
Closing because it won't get done by anyone else - but feel free to re open in the future if you'd like to work on it
