### ISSUE TITLE
Change Twitter to X

### ISSUE THREAD

**Issue by vakesz** [daattali/beautiful-jekyll#1193]
> social-network-links.html:
https://github.com/daattali/beautiful-jekyll/blob/master/_includes/social-networks-links.html#L90

> social-share.html
https://github.com/daattali/beautiful-jekyll/blob/master/_includes/social-share.html#L13

> _config.yml
https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml#L57

FontAwesome X Icon:
https://fontawesome.com/icons/x-twitter?f=brands&s=solid

-------------------------------
Please only submit feature suggestions or bug reports if you believe something is broken.

If you need help, you can attend the [Office Hours](https://beautifuljekyll.com/officehours) (only available for [sponsors](https://beautifuljekyll.com/plans/)).

**Comment by daattali** [comment]
This logo is not available in the fonrawesome version that's used in beautifuljekyll right now. You can submit a PR, but you'd need to make sure that the UI of all existing logos doesn't change after upgrading FA

**Comment by daattali** [comment]
Updating to the latest fontawesome (6.4.2) should be fine because it's backwards compatible.

**Comment by daattali** [comment]
Done
