### ISSUE TITLE
Files pushed to /_posts are not being shown in the website

### ISSUE THREAD

**Issue by sillasgonzaga** [daattali/beautiful-jekyll#12]
Here's my [github blog](http://sillasgonzaga.github.io/) created with beautiful-jekyll. It has only one post so far, the "First post!" so far.

However, I've pushed other two files to [/_posts](https://github.com/sillasgonzaga/sillasgonzaga.github.io/tree/master/_posts) but they are not showing up on my page. Why?

**Comment by daattali** [comment]
The file has to follow the naming convention, the filename has to start with the date like all the sample ones have
