### ISSUE TITLE
'social' reddit missing

### ISSUE THREAD

**Issue by kootenpv** [daattali/beautiful-jekyll#120]
I guess from the social section reddit is missing as an option.

**Comment by daattali** [comment]
Yes it is, there are dozens of social media websites, I only aimed to include the most useful ones. You can edit the `_includes/footer.html` file if you want to add reddit, it should be very easy, just follow the template that all the others use

**Comment by kootenpv** [comment]
I don't see it here? https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml#L71

So it's more of a hidden feature then?

**Comment by daattali** [comment]
To clarify: reddit is NOT supported out of the box. What I meant is that I only included the very popular sites in beautfiful jekyll, and reddit was not one of them. If you want to add reddit, you'd need to follow the template in the file I mentioned, (and you're right) also add it in the _config file

**Comment by kootenpv** [comment]
A bit of an early close then :-) 

Implemented in #121
