### ISSUE TITLE
Can't satisfy Gemfile, dubious ownership of repository

### ISSUE THREAD

**Issue by Soulsender** [daattali/beautiful-jekyll#1200]
Getting an error every time I commit and push. This happens even when I edit the file in the browser on github.
```
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Warning:  github-pages can't satisfy your Gemfile's dependencies.
```

My whole repo is the default fork of this repo, but whenever I make any changes, the build fails.

I had a different .github.io site but I wanted to switch to jekyll, so maybe that has something to do with it? I have no idea.

**Comment by daattali** [comment]
I don't know what that error is, but it's very unlikely that it's casued by this repository. I'm fairly certain this is something you'll need to fix on your end.

**Comment by Soulsender** [comment]
Any guidance? The only documentation I've been able to find is if you're building Jekyll on your local machine, but it seems like this is some issue with virtualization github uses to deploy the site.

**Comment by daattali** [comment]
I can't point you anywhere because this is not an issue related to this project, it sounds like 100% a git/github issue. Google is your best bet here.
