### ISSUE TITLE
When full-width:true title and subject to fill entire screen

### ISSUE THREAD

**Issue by sschwetz** [daattali/beautiful-jekyll#1216]
Hi,

When full-width is set to true the title and subtitle do not full the full page width but wrap in the same way as a standard page/post.

Cheers

**Comment by daattali** [comment]
Thanks for the report. This is actually a deliberate choice - only the main page content is full width, but the footer and header are purposely kept centered. I thought it doesn't look as good in general when the title/subtitle span the entire page.
