### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#1232]
### Discussed in https://github.com/daattali/beautiful-jekyll/discussions/1230

<div type='discussions-op-text'>

<sup>Originally posted by **talonx** October 31, 2023</sup>
My site repo is https://github.com/talonx/talonx.github.io/ and the site is live at https://code.deepinspace.net/

The search function does not seem to work at all. The search box comes up but nothing more happens when I type or press Enter. Anything I might be doing wrong?

Firefox 118.0.2 on Ubuntu 22 (snap).</div>

**Comment by daattali** [comment]
Thanks for reporting. I can see from a quick look at the javascript console on your webpage that this is likely an issue with not properly escaping the search information. 

This is what I'm seeing in the console:

![image](https://github.com/daattali/beautiful-jekyll/assets/952340/fae3ad33-ab1a-4d08-94fe-8a529f1c4b71)

And looking at the HTML, I see this:

![image](https://github.com/daattali/beautiful-jekyll/assets/952340/6413df28-37f6-456f-a383-28ed4f88a0e0)

I'll try to take a look to fix when I find time. Feel free to help with a PR as well if you can.

**Comment by daattali** [comment]
@talonx I'm keeping track of your issue here

**Comment by talonx** [comment]
> Thanks for reporting. I can see from a quick look at the javascript console on your webpage that this is likely an issue with not properly escaping the search information.
> 
> This is what I'm seeing in the console:
> 
> ![image](https://user-images.githubusercontent.com/952340/279538988-fae3ad33-ab1a-4d08-94fe-8a529f1c4b71.png)
> 
> And looking at the HTML, I see this:
> 
> ![image](https://user-images.githubusercontent.com/952340/279539007-6413df28-37f6-456f-a383-28ed4f88a0e0.png)
> 
> I'll try to take a look to fix when I find time. Feel free to help with a PR as well if you can.

Ah I did notice this but did not realize it might be related.
Thanks for tracking it.

**Comment by daattali** [comment]
The problem was that you used an apostrophe in the file name. I did not think about having to escape file names, but it's now fixed. You'll have to use the latest version

**Comment by talonx** [comment]
> The problem was that you used an apostrophe in the file name.

Ah - that happened when I imported some older posts into Jekyll.

**Comment by talonx** [comment]
Thanks for the quick turnaround. Would you be putting this in a release sometime soon?

**Comment by talonx** [comment]
i.e. I want to pin my Jekyll version to avoid other possible issues.

**Comment by daattali** [comment]
Yes of course, it will be in the next release. But I do suggest not using apostrophes (or any non alphanumeric/slashes/underscores) in file names, not just because of this issue, but in general it's not a good idea.

**Comment by talonx** [comment]
For now I've renamed the files and the problem is resolved. I'll upgrade the theme in the next release.

Thanks a lot for responding and resolving this so quickly.
