### ISSUE TITLE
Search is Broken

### ISSUE THREAD

**Issue by systemcenterblog** [daattali/beautiful-jekyll#1233]
https://github.com/systemcenterblog/systemcenterblog.github.io

I have read others with identical issue however, I have applied your updated search.html and I don't have any errors relating to escaped chars.

It behaves like the JS is not running and the JSON file is not created.

**Comment by daattali** [comment]
I saw your other comment "I have removed all my HTML posts that were converted from Blogger so only .MD posts are present and the search feature is working. What Character break the search script? i.e. _ ' ._ [] $"

To answer: I don't know exactly what breaks it. This is the javascript code that is responsible for this piece https://github.com/daattali/beautiful-jekyll/blob/ff34170c5d62507d62f9c946550dc63244aa6979/_includes/search.html#L11-L31

I'm working on many other open source projects this week so I can't invest any more time on this issue now. I'll try to come back to it in the future. If you have familiarity with javascript, I would welcome you to try to debug it and let me know if you find the cause!

**Comment by daattali** [comment]
For the other guy's case it was very easy to find the issue because the JS console error clearly showed where the problem is. With your site, I don't see a trivial cause. Maybe the string is just too long? That's just my first baseless guess.

**Comment by daattali** [comment]
@systemcenterblog search was recently updated, can you try with the latest (unreleased) version and tell me if it's still broken for you?
