### ISSUE TITLE
Code blocks do not scroll anymore

### ISSUE THREAD

**Issue by dagnelies** [daattali/beautiful-jekyll#1235]
I don't know when exactly this bug was introduced, but using the latest version of this theme, the view is now broken on mobile because of code blocks.

![image](https://github.com/daattali/beautiful-jekyll/assets/5452653/923d3b13-20e3-49c1-97f8-6cd4ec4e0d14)

I'm pretty sure that before such code blocks had scroll bar, so that the view didn't get bigger than the screen. Dunno when or why this happened.

Here is the same using a (much) older version of the theme:

![image](https://github.com/daattali/beautiful-jekyll/assets/5452653/333f4c5b-d2cf-4fed-8814-701c44c27850)

**Comment by daattali** [comment]
Thanks for reporting. Going through the list of recent changes, the one that is the most likely to have caused this is perhaps https://github.com/daattali/beautiful-jekyll/commit/ba46ef8abd1e2aea30c04b633a7fcdbb31e122b2

When I find some time I'll try to look into it. If you know how to, can you try to troubleshoot and see if that change indeed caused the issue?

**Comment by daattali** [comment]
I've done a bit of testing and that commit is indeed was breaks it. It was introduced from https://github.com/daattali/beautiful-jekyll/pull/1226 - I'll see if the author of that PR has a fix

**Comment by dagnelies** [comment]
Thanks for investigating and pin-pointing it to this commit 👍 
I think the issue comes from the `display: grid`, I'll take a look later on.

**Comment by daattali** [comment]
Thanks, I'd still like to give @ch0c0l8ra1n a chance to add any info

**Comment by daattali** [comment]
Thanks for @dagnelies in your help with https://github.com/daattali/beautiful-jekyll/pull/1236

I ended up making some HTML changes so I used your idea and implemented it in 068bf0f63cb93b566736ade443993e898dc174a1 and cf95491c367952617141dc98ab02fd58bf0f4984

**Comment by daattali** [comment]
Can you please confirm that it's fixed for you?
