### ISSUE TITLE
':' in title will make the webpage unable to show title

### ISSUE THREAD

**Issue by Z-Y00** [daattali/beautiful-jekyll#1247]
I want to have a title like:
Email update: x,y,z
But it will fail to render. 
Is there any escape trick for the ':'?
Thank you for the help
![image](https://github.com/daattali/beautiful-jekyll/assets/23717414/0370ff92-de1e-4589-b518-983b33ab1389)

**Comment by daattali** [comment]
You'll need to surround the entire string in quotes. In YAML you can always surround values in quotesto be safe, but it's required if you use certain characters.

```
title: "Email update: x,y,z"
```
