### ISSUE TITLE
`{% include comments.html %}` doesn't work in `page.html`

### ISSUE THREAD

**Issue by tae898** [daattali/beautiful-jekyll#1250]
https://github.com/daattali/beautiful-jekyll/blob/938b912c77488aa48921271eda89ceddea4981ad/_layouts/page.html#L28

does not work, while

https://github.com/daattali/beautiful-jekyll/blob/938b912c77488aa48921271eda89ceddea4981ad/_layouts/post.html#L85

works fine

Why is this? I also want to have comments for the pages.

**Comment by daattali** [comment]
Did you solve your question?

**Comment by tae898** [comment]
Yeah it was already on README. my bad.
