### ISSUE TITLE
[UI Issue]: Weird Behaviour with Dark Mode

### ISSUE THREAD

**Issue by TartejBrothers** [daattali/beautiful-jekyll#1254]
# Issue : 
- The dark mode on hover goes to the right and goes to grey colour.
- Once clicked it goes back to left to show light mode.
- it doesn't work as a trigger.
- The inline padding should also be increased a bit.

## Dark Mode
![image](https://github.com/daattali/beautiful-jekyll/assets/112921727/9ae49e25-5f5b-4ea6-987a-f262b714c5f9)

## Light Mode
![image](https://github.com/daattali/beautiful-jekyll/assets/112921727/8ae3df3b-6ebf-45ec-a6f9-d5cf4ab9d390)

**Comment by daattali** [comment]
I undertsand it may be weird behaviour for some, but it is actually exactly as intended. There is no way that is universally standard for this type of button.
