### ISSUE TITLE
yelp bug

### ISSUE THREAD

**Issue by tsolloway** [daattali/beautiful-jekyll#1259]
should be (at least in the US / LA):
`a href="https://yelp.com/{{ network[1] }}" title="Yelp">`

**Comment by tsolloway** [comment]
in social-networks-links.html   ln 236

**Comment by daattali** [comment]
You're right that `xxx.yelp.com` no longer seems to work, it seems like the yelp URLs changed sometime in the past few years. I can't find any official documentation on how their URL structure should look like, so from some 2 minute experimentation, your solution seems safe. Would you like to submit a PR? (Please also update the CHANGELOG)
