### ISSUE TITLE
share buttons not working

### ISSUE THREAD

**Issue by yimingli** [daattali/beautiful-jekyll#126]
I might be missing something, but it seems that none of the demo blog posts shows share buttons, when in the default front matter `social-share: true`.

**Comment by daattali** [comment]
I'm not sure why you think that, I just forked this repo and I do see the social sharing buttons

http://imgur.com/a/kxe13

https://daattalitest.github.io/2015-02-20-test-markdown/

Maybe you're referring to something else. The social-share buttons are the twitter/facebook/linkedin square buttons beneath a post , above the pagination

**Comment by yimingli** [comment]
Thanks! I was referring to demo blog posts such as this one: http://deanattali.com/beautiful-jekyll/2015-02-26-flake-it-till-you-make-it/ Is this post based on beautiful-jekyll?

I also tried to incorporate social share buttons into jekyll's default theme to no avail. I added `/_includes/social_share.html`, edited `_config.yml` and `_layouts/post.html`, but it didn't work. Could you please point me to the right direction? What other site files should I modify? Thanks a lot!

**Comment by daattali** [comment]
Oh I see. The demo website is built with a very outdated version before I
added support for those buttons.

Honestly I don't remember exactly where all the moving pieces are, it'll
take me time to figure that out again and I'm working on a lot of projects
and don't really have that time,  sorry!

**Comment by yimingli** [comment]
No worries, great theme! Thanks.
