### ISSUE TITLE
Mobile avatar-container display 

### ISSUE THREAD

**Issue by tsolloway** [daattali/beautiful-jekyll#1264]
avatar-container can conflict website title on mobile. My hot fix was:

```
@media (max-width: 574px) {
  .avatar-container {
    display: none;
  }
}
```

**Comment by daattali** [comment]
The icon can interfere with the title and also with the menu links, even in desktop mode. The custom solution I've suggested in the past is to simply move it down. In your case:

```
@media (max-width: 574px) {
  .navbar-custom .avatar-container {
    bottom: -2.5rem;
  }
}
```
