### ISSUE TITLE
Custom Feed name

### ISSUE THREAD

**Issue by monksy** [daattali/beautiful-jekyll#1278]
I would like to customize the feed name from feed.xml to feed. I wish there was a way to configure the name. 

WP generates /feed for me. However, I need this to be consistent for the URLs.

**Comment by daattali** [comment]
It seems that `/feed` does work in the cases that I tried (https://beautifuljekyll.com/feed and https://deanattali.com/feed both work)
 
I'm not sure how you can make an XML page with a URL of `/feed`. That would be a question to ask in a more general jekyll forum - it's not specific to this theme. From what I know, if you create a file with no extension, jekyll won't know how to render it correctly (or, at least I don't know how to get jekyll to render it correctly). If you create a file called `feed.md` or `feed.html` then you could navigate to them using the url `/feed`, but then they're no longer XML files, so I'm not sure how that would work either. I would encourage you to ask in a jekyll forum.
