### ISSUE TITLE
[HELP]  Note box with bullet points

### ISSUE THREAD

**Issue by Ede1994** [daattali/beautiful-jekyll#1297]
I would like to use the .box-note, .box-success together with bullet points, for example:
{: .box-success}
**Key Points**:
- bla bla
- bla bla

Alternatively, I would create a new box exactly for this use case, I know how to do that in css, but where do I create the actual rules for the box?

Many thanks in advance! :)

**Comment by daattali** [comment]
I'm not quite sure how to do that. However, this is a general jekyll question, not specific to this theme, so you should be able to ask this question in any jekyll forum online, such as https://talk.jekyllrb.com/
