### ISSUE TITLE
Publish beautiful jekyll as a ruby gem https://jekyllrb.com/docs/themes/

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#130]

**Comment by sasivarnan** [comment]
+1

**Comment by daattali** [comment]
Does anybody want to help me with this?  I don't think I'll find time in the near future to take a few hours to learn how to build this locally well enough to be able to publish it as a gem -- please contact me if you can help

**Comment by daattali** [comment]
The theme is available as a gem now

https://rubygems.org/gems/beautiful-jekyll

However, the documentation for creating gems is really poor so since I'm a complete noob with ruby/gems, I'm not 100% sure how well this worked. Specifically, I don't know how to install the theme in a way that would pull all the theme files (the layouts, includes, etc.)
