### ISSUE TITLE
favicon.ico setting

### ISSUE THREAD

**Issue by yiluheihei** [daattali/beautiful-jekyll#131]
A great work for website creating. 

I found that there is no "favicon.ico" according to your step-to-step tutorial. 

We can set a "favicon.ico" by adding `<link rel="icon"  href="/img/favicon.ico" />` in the "header.html". Or a yaml parameter "ico" could be offered to control if "favicon.ico" is show to the site.

**Comment by daattali** [comment]
You can simply add a favicon to the root folder and it'll automatically be
picked up

**Comment by yiluheihei** [comment]
Thanks  👍
