### ISSUE TITLE
Navbar rendering incorrectly

### ISSUE THREAD

**Issue by Maspital** [daattali/beautiful-jekyll#1313]
Hi,

The navbar is rendering incorrectly (aka menu items are going through the avatar) on some screen sizes.
Additionally, if the menu is open while the screen is getting resized, the avatar disappear.

The second issue is somewhat irrelevant, but the first one is irritating.
Have I overlooked a config parameter somewhere? Otherwise I probably need to fall back to either using submenus or removing the avatar.

[Screencast from 17.04.2024 15:00:59.webm](https://github.com/daattali/beautiful-jekyll/assets/38432054/8481c978-2e81-4e65-b848-8680324543a4)

**Comment by daattali** [comment]
Please see here for my response. This is not an easily solvable problem, if you have an idea on how to fix it I'd be happy to hear  https://github.com/daattali/beautiful-jekyll/issues/471
