### ISSUE TITLE
Github pages build not working

### ISSUE THREAD

**Issue by way0utwest** [daattali/beautiful-jekyll#1326]
Please only submit feature suggestions or bug reports if you believe something is broken.
I copied your ci.yml file over to a BeautifulJekyll build, but the appraisal install doesn't seem to work.

Log file: 
( install dependencies step)
Fetching jekyll-sitemap 1.4.0
Installing jekyll-sitemap 1.4.0
Bundle complete! 3 Gemfile dependencies, 32 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from sass:
Ruby Sass has reached end-of-life and should no longer be used.
* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
bundler: command not found: appraisal
Install missing gem executables with `bundle install`
Error: Process completed with exit code 127.

Any help appreciated. This is for a US charity site I run that stopped working this week.
If you need help, you can attend the [Office Hours](https://beautifuljekyll.com/officehours) (only available for [sponsors](https://beautifuljekyll.com/plans/)).

**Comment by daattali** [comment]
I cannot provide personalized help in this manner. Please seek help on general jekyll forums.
