### ISSUE TITLE
update to font-awesome 6?

### ISSUE THREAD

**Issue by heidibaum** [daattali/beautiful-jekyll#1330]
I'd like to request an update to font awesome 6 (spurred by desire to add bluesky icon to social network links). I've tried updating the fa link in the base.html file in my own repository, but that hasn't done the trick and I'm out of my depth. Thanks!

**Comment by heidibaum** [comment]
correction: I meant I tried updating the font-awesome link in base.html (not social-networks-links.html)

**Comment by daattali** [comment]
Upgraded to 6.5.2 https://github.com/daattali/beautiful-jekyll/commit/4a9894966d454becb4b7ca847ac02e731c2b2305
