### ISSUE TITLE
Why can't I embed gif or videos? Why aren't notes showing properly?

### ISSUE THREAD

**Issue by Linchihj** [daattali/beautiful-jekyll#1337]
Hi @daattali,

Thank you for designing such a beautiful template. I have a few questions, though. How come sometimes what I see in markdown preview in Visual Studio Code doesn't match the final output? Like in preview mode notes and gif or videos appear normal, but cannot be shown on the actual github page. 

Does your template only support an older version of jeykyll or github?

**Comment by daattali** [comment]
There are many different "flavours" of markdown. I'm not sure what Visual Studio Code shows. This template uses Jekyll, which is what GitHub Pages supports. Any markdown that works in a plain jekyll site or in a plain GitHub Pages site should work here. If you find a case where that isn't true, please do share the code that breaks that statements.
