### ISSUE TITLE
Change default font?

### ISSUE THREAD

**Issue by ghost** [daattali/beautiful-jekyll#1358]
Hey, quick question, where and how would you change the default font of everything?

**Comment by daattali** [comment]
There are two main fonts. You can see them defined in the beautifuljekyll.css:

https://github.com/daattali/beautiful-jekyll/blob/ac7d6024b3a917ccfc1ac54f8e6601d8becb5da6/assets/css/beautifuljekyll.css#L22-L23

So you need to create a new css file and overwrite this rule
