### ISSUE TITLE
Add phone number to footer

### ISSUE THREAD

**Issue by TaylorAndrew** [daattali/beautiful-jekyll#136]
Is there anyway we can add a phone number to the footer to go alongside the email, github, etc.?

**Comment by daattali** [comment]
Currently no, but it can be easily added if there was a sensible way for it
to look. All other links are a circular icon that act as links - but for
the phone number you'd need to actually spell it out , it can't simply be a
circular logo,right? Which will make it look awkward in my opinion

**Comment by TaylorAndrew** [comment]
Actually, I guess thinking mobile-first, I was assuming it would be a circular icon that when you clicked it opened the call screen with the number pasted into the keyboard, much like how calling businesses via google maps works. 

But I do see the issue with non-mobile.

**Comment by daattali** [comment]
I guess on desktop it'd try to open Skype or similar, I'll take a look

**Comment by TaylorAndrew** [comment]
Thanks Dean! If you are able to find a solution, it would definitely be a huge benefit to my site. 

Well, theoretically, at least. In the case that someone actually goes to it in the future.

**Comment by daattali** [comment]
OK you can now use the `telephone` flag in the config file. You'll have to re-fork my repo to get these changes. I tested on android and on desktop
