### ISSUE TITLE
collapsible markdown is not parsed properly in a page layout

### ISSUE THREAD

**Issue by jpdeleon** [daattali/beautiful-jekyll#1363]
I have a page layout with markdown. Since the content is long, I enclosed each section in a collapsible section using the `<details>` tag following [this article](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). The markdown itself is rendered properly in github (see [my page](https://github.com/jpdeleon/jpdeleon.github.io/blob/master/teaching.md) for example) but somehow the markdown format is not rendered properly after publishing (see [rendered my page](https://jpdeleon.github.io/teaching/)), perhaps due to conflict with css?

**Comment by ccorsi** [comment]
This isn't an issue with this theme but just with your plugin/gem configuration.  This can be shown by just replacing your page layout with none.   If you serve that page locally you will see that you are still seeing the issue that you are describing above.  

I looked at the Github Pages documentation about what plugins to use at [Plugins](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins) and added those plugins to my _config.yml and Gemfile without successfully producing the expected page.  Obviously, Github is doing something different when processing pages through its Github site compared to how Github Pages does it.

As an aside, Github Pages publishes a list of all its dependency they use at [GitHub Pages Dependency versions](https://pages.github.com/versions/).

In the end, it seems to me that Github just needs to clarify how they generate the markdown files through the github website compared to how github pages does it.

**Comment by jpdeleon** [comment]
Thanks for looking into this! I will just refrain from using the `<details>` tag since it is not worth the trouble of digging into the details of github pages rendering.

**Comment by daattali** [comment]
According to [this comment](https://github.com/gettalong/kramdown/issues/155#issuecomment-339402782), and after testing it myself, it seems that the culprit was that kramdown by default doesn't support markdown inside tags. But you can enable it by add a config parameter. I tested this and it indeed works.

**Comment by jpdeleon** [comment]
Thanks for investigating further. To add, adding a markdown="1" attribute to the <details> tag and a markdown="span" attribute to the <summary> tag will solve this issue, as presented [here](https://github.com/github/docs/issues/32988).
