### ISSUE TITLE
Markdown code blocks wrapping

### ISSUE THREAD

**Issue by jpuritz** [daattali/beautiful-jekyll#137]
Thanks for all your work on this great theme.  

Is there anyway to change the default behavior of markdown code blocks.  I really don't want them to wrap.

```bash

echo "Please tell me a way to stop this from wrapping across multiple lines!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

```

**Comment by daattali** [comment]
If you know CSS, it should take a few minutes to fidgeting around with the style for codeblocks to achieve that. I don't know it off the top of my head

**Comment by daattali** [comment]
Try adding this to your CSS

```
pre code {
  white-space: pre;
}
```
