### ISSUE TITLE
Where to change colors of social icons?

### ISSUE THREAD

**Issue by akirawashere** [daattali/beautiful-jekyll#1386]
Hey, just wondering where would you change the color of these

![image](https://github.com/user-attachments/assets/47c02657-f130-4890-a3b7-3416a62962f6)

**Comment by daattali** [comment]
They take the same colour as the text colour on the page and the background colour of the page. You'll need to use CSS to change that. A CSS tutorial is out of scope for this theme, but it's a good idea to learn basic CSS because then you'll be able to make a lot of visual modifications.
