### ISSUE TITLE
resizing html file and rendering ipynb in _posts

### ISSUE THREAD

**Issue by jpdeleon** [daattali/beautiful-jekyll#139]
Hi Dean,

I used your Jekyll template and it's awesome. I am completely new to this so I'm sorry for asking very basic question. I wanted to upload .ipynb file into into the _posts folder but it does not render properly. So I opted to upload an .html file instead. However, the page size is off as you can see here:
https://jpdeleon.github.io/2016-12-07-Tutorial_01_Exoplanet_Plots/

I would like it to render like this: http://nbviewer.jupyter.org/github/jpdeleon/jpdeleon.github.io/blob/master/_posts/2016-12-07-Tutorial_01_Exoplanet_Plots.html

I am always working with Jupyter .ipynb and my wish is to render the file readily in Jekyll by just uploading the .ipynb to _posts. Is this possible? Note that .md file will work but I'm just wondering how it'll be done for ipynb. Thank you!

**Comment by daattali** [comment]
Yes it's possible, you'll just have to play with the CSS a tiny bit.

Here are the steps you'll need to do:

Add a file called `jupyter.css` inside the `css` folder and put the following in it:

```
header + .container > div.row > div {
  margin: 0 auto !important;
}
#notebook-container {
  -webkit-box-shadow: none;
  box-shadow: none;
}
```

Then in the YAML of the file (between the `---` at the top of the file), add a line: `css: /css/jupyer.css`

**Comment by jpdeleon** [comment]
Thank you for the detailed instruction. I added the `jupyter.css` file 
https://github.com/jpdeleon/jpdeleon.github.io/blob/master/css/jupyter.css

and added `css: /css/jupyer.css` to the YAML, as instructed
https://github.com/jpdeleon/jpdeleon.github.io/blob/master/_posts/2016-12-15-The%20Kill%20List.html

However, the page still doesn't seem to render properly 
https://jpdeleon.github.io/ 
for both jupyter (.ipynb) and .html files. Sorry if I missed your point above. But thanks for the help!

**Comment by daattali** [comment]
It should work absolutely fine. You misspelled `jupyer.css` --> `jupyter.css`

I just copied your html file into a test repo, it works.

https://github.com/daattalitest/daattalitest.github.io/blob/master/_posts/2016-12-12-jupytertest.html

https://daattalitest.github.io/2016-12-12-jupytertest/
