### ISSUE TITLE
[question] browser tab image

### ISSUE THREAD

**Issue by TaylorAndrew** [daattali/beautiful-jekyll#140]
Sorry to keep bothering you. But I am not seeing where you specified to have the image of yourself be the image that shows up in the browser tab. It isn't the title img or the navigation img. I noticed that it was also your github profile img so I (finally) added an image to my github profile, but that doesn't seem to be it either.

I'm sorry if it's directly in front of me and I'm just missing it. Though looking through a couple of other websites that have used beautiful-jekyll, they do not have a browser tab img set either, so I may not be going crazy.

-Andrew

**Comment by daattali** [comment]
The tiny image in the tab is called a favicon. Yes, that's a separate question that isn't related to my theme, it's jekyll in general. I think you just need to place a valid favicon picture named `favicon.ico` in the root folder, and after a few minutes/hours it should show up once the cache clears

**Comment by bidyutchanda** [comment]
Here, by root you mean the main folder of the website or the /img folder? @daattali

**Comment by JackGruber** [comment]
Hi, the main folder of the Website.

**Comment by daattali** [comment]
Main website folder
