### ISSUE TITLE
Add RSS support in gem

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#146]
https://github.com/daattali/beautiful-jekyll/pull/145#issuecomment-269129554

@sasivarnan

**Comment by daattali** [comment]
gem version 1.1.1 supports RSS with `rss-footer: true`

**Comment by sasivarnan** [comment]
@daattali. Awesome work. Thanks a lot. 😄

**Comment by sasivarnan** [comment]
Looks like `Github Pages` supports only the `gem` themes  provided in the following site https://pages.github.com/themes/. 😞

**Comment by sasivarnan** [comment]
I got this email from `github` when I committed my site with theme changes.

```
The page build completed successfully, but returned the following warning:

You are attempting to use a Jekyll theme, "beautiful-jekyll-theme", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by daattali** [comment]
Yes that is true. If youre using github pages, you should use the regular
master branch, its better to have all the files yourself. I prefer it to
the gem, i only offer it as a gem as an alternative solution

**Comment by sasivarnan** [comment]
@daattali Using [GitLab pages](https://pages.gitlab.io) for hosting my [website](https://cybeadon.com) which lets us to define our own build process and we can use  custom `jekyll` plugins and `gems`. Building site takes around 4 minutes, still considerable.
