### ISSUE TITLE
[Not a issue] Post image in navbar avatar

### ISSUE THREAD

**Issue by shineon82** [daattali/beautiful-jekyll#156]
If I set a picture in a post (**image:**  in the front matter) it's displayed instead of the default avatar in the navbar. 
It's possible to display it below the title of the post and leave the default avatar? 

Sorry for my poor english

**Comment by daattali** [comment]
Currently no. The post image feature was only added a couple weeks ago and
it wasn't my idea it was a user who wanted it, so I didn't spend a ton if
time thinking about it

**Comment by shineon82** [comment]
Ok, thanks! Well, I hide avatar when set image to post.
