### ISSUE TITLE
<div class=container> content extends outside of <div class="container" role="main"> in pages

### ISSUE THREAD

**Issue by martinjhnhadley** [daattali/beautiful-jekyll#163]
Containers within pages extend outside of their row in the <div class="container" role="main">

Example page:

```html
layout: page
title: Meet The Team
---

We are a group of researchers based at the University of Oxford who are passionate about research reproducibility and open research. The project aims to bring together expertise in these areas from across the University, and our members work in a diverse range of disciplines in the natural, medical, and social sciences, and in the humanities.

<div class="container">
<div class="row justify-content-center">

<div class="col-sm-4" style="text-align:center">

<a href="../laura-fortunato"><img src="../img/profile-pic_laura-fortunato.jpg" style="border-radius: 50%;
    width: 150px;
    height: 150px;"/></a>

</div>

<div class="col-sm-4" style="text-align:center">

<a href="../philip-fowler"><img src="../img/profile-pic_phillip-fowler.jpg" style="border-radius: 50%;
    width: 150px;
    height: 150px;"/></a>

</div>

<div class="col-sm-4" style="text-align:center">

<a href="../martin-john-hadley"><img src="../img/profile-pic_martin-john-hadley.jpg" style="border-radius: 50%;
    width: 150px;
    height: 150px;"/></a>

</div>

</div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/9363263/22332436/da50dbe6-e3c8-11e6-9e0f-ac711447577f.png)

Rows can be added without containers, but I believe it's best practice to always wrap containers around rows?

I had a quick look into how to fix this myself, but couldn't figure it out.

**Comment by daattali** [comment]
The templates I made are for the 99% of people who don't know how bootstrap
works and only write in markdown. If you're defining your own bootstrap
layouts (rows/containers) It's better if you either modify the page
template or create a new template or use a layout type that is more flexible

**Comment by martinjhnhadley** [comment]
That makes a lot of sense, thanks for reply!
Personally, I'd argue that was sufficient to close this and so am.
Cheers 🍻
