### ISSUE TITLE
bigimg on an old version

### ISSUE THREAD

**Issue by radaniba** [daattali/beautiful-jekyll#170]
Hello There

I am using a fork since Feb 2016, and I don't think `bigimg` is supported at that time, as I made some changes to the theme myself, I am wondering what are the changes I need to bring to my fork so that I can add support to bigimg

any idea ?

Last commit I have from yours is `abc9e978bf81cc746eb3de55be5896768b9369b0` which is a year ago

**Comment by daattali** [comment]
You should take a look at this commit entitled "support big images; fix issue 37"

https://github.com/daattali/beautiful-jekyll/commit/e6cb0a4f546d43f2c121970ac181c0d12ab1242c

It'll be a bit of a manual work to go through all those code changes and apply them, but I had to do that myself too so you can do it :) good luck!

**Comment by radaniba** [comment]
Thanks Dean, worked just fine
