### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by MatthewClarkMay** [daattali/beautiful-jekyll#197]
I set link-tags: true in _config.yml and then locally ran jekyll build to build the site. I then moved the _tags directory up into my site repo and pushed it to my <username>.github.io repo so Pages will build it. The links all work, but for some reason it doesn't inherit the css/js from my templates. Any thoughts?

**Comment by daattali** [comment]
Sorry, I don't know why it isn't working for you. Usually if the css/js aren't showing it means that page isn't using the template, but that would also mean that the header and footer are not included. I personally do not do any local development, only from github, sorry!
