### ISSUE TITLE
avatar covers menu

### ISSUE THREAD

**Issue by fiezt** [daattali/beautiful-jekyll#198]
When the window is scaled to only be half of a screen I have an issue where the avatar covers the menu. If I make the window less wide the menu will eventually collapse so it is not covered by the menu. How can I prevent this issue? I attached a photo of the problem.
![screen shot 2017-04-20 at 11 11 15 pm](https://cloud.githubusercontent.com/assets/22989351/25264960/28dddfb4-261f-11e7-9f2f-8715ddce2c7f.png)

**Comment by daattali** [comment]
Unfortunately that's an issue  that happens and is going to be extremely difficult to fix because it's impossible to account for all cases (all screen sizes and all menu lengths). It depends on how many menu items you have, how long they are, and how side the screen is. My only "solution" is to try to limit the menu items to only a few (you can use submenus) and to make them short ("undergraduate background" for example is long). I know it's a terrible "solution" but it's a compromise between that or making your photo cover up some menu when the screen is very small. Sorry I don't have a more useful suggestion!

**Comment by fiezt** [comment]
Thanks for the reply and the great theme. Is there not a way to force the menu to collapse once the menu gets to be within a margin of the avatar though?

**Comment by daattali** [comment]
No, there isn't. The menu collapsing is a feature of bootstrap (
http://getbootstrap.com/css/) and that determines at what screen width it
collapses. You can try your luck at tinkering with the CSS yourself if you
know how to and you have the willpower to do so, but it isn't going to be
fun :)

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by fiezt** [comment]
Okay that makes sense. What about moving the menu above the avatar? I am guessing that is not a quick fix though.

**Comment by daattali** [comment]
Do you mean making the menu talle permanently, or moving the avatar down permanently? Both of these are possible to do, but again require CSS. Moving the avatar down probably is fairly easy to do (I haven't looked at that code in a couple years so I'm only guessing!)

**Comment by fiezt** [comment]
Yeah either would be decent solutions in my opinion. I think that moving the avatar to be below the menu would likely be the best solution to the problem.

**Comment by daattali** [comment]
OK, you still do need to know CSS for that - if you do then I can point you
in the right direction of where to look but not if css is foreign to you

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by fiezt** [comment]
I don't know a lot about it. I program though, so I think I could pick it up. If you could point me in the right direction that would be awesome, I think I will have to use a different them if I cannot fix that issue.

**Comment by daattali** [comment]
It's possible that it's as easy as finding the position property of the avatar in `css/main.css`. Maybe try changing [this line](https://github.com/daattali/beautiful-jekyll/blob/master/css/main.css#L192) to 0 or some other value between -50 to 0
