### ISSUE TITLE
It's not work

### ISSUE THREAD

**Issue by hdi-hvd** [daattali/beautiful-jekyll#203]
I was followed your guide and got 404 page. What's wrong with my _config.yml ? Please help me. Thanks a lot.
https://github.com/hdi-hvd/duyhuynh.github.io/blob/master/_config.yml

**Comment by daattali** [comment]
I don't know if you have any problems with your config file, but one thing that is definitely making it not work is the fact that you didn't name your project `hdi-hvd.github.io`

Please try to follow the steps exactly as outlined [here](https://github.com/daattali/beautiful-jekyll#build-your-website-in-3-steps)

**Comment by hdi-hvd** [comment]
thank you, it's work. =))
