### ISSUE TITLE
Social Share and Footer Link not working

### ISSUE THREAD

**Issue by saifkabirasif** [daattali/beautiful-jekyll#210]
Hi,

Thanks for the nice theme. I'm having issues with social share. Although, I kept social-share true for facebook, twitter, linkedin etc, they are not appearing. In the footer also, though Github and Email links are working, facebook is not coming although I enabled it.

Need your help in this regard.

**Comment by daattali** [comment]
You need to set those values in the _config.yml file in order for them to appear in the footer

**Comment by saifkabirasif** [comment]
Hi Dean,
Thanks for the quick response.
I've already done that but social media share was not appearing. After some tinkering, I found that uBlock Origin add-on is blocking social media sharing specifically Facebook and Twitter. After turning that off, the all social media sharing appeared.

Hope this helps others who have uBlock Origin also.

Again thanks for the tremendous job you are doing for thousands of budding data science enthusiasts.

**Comment by daattali** [comment]
Ah that's annoying, good to know , thanks!
