### ISSUE TITLE
Twitter card not working properly

### ISSUE THREAD

**Issue by JosemyDuarte** [daattali/beautiful-jekyll#219]
Even when I define the share-img property for a post, when I share the post on Twitter it show my avatar, not the share-img. I checked the html <head> of the post and it seems OK.

**Comment by daattali** [comment]
I'm traveling for the next few weeks and will not be able to look at this.
I'll try to take a look when I can, thanks!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by JosemyDuarte** [comment]
I took some time trying to solve the issue. Seems to be a "problem" from Twitter. Reference: https://dev.twitter.com/cards/troubleshooting#refreshing

I don't know if adding the commit hash to the image URL could be a workaround. 

PD: Thanks for the theme!

**Comment by daattali** [comment]
Thanks for taking a look. I didn't know there were old and new versions. If
you figure it out,  feel free to submit a PR!

**Comment by daattali** [comment]
I'm closing this issue since it looks like the problem does go away eventually (quote from the documentation: "Our web crawlers re-index the Card tag information on your page roughly every week")
