### ISSUE TITLE
Possible for code scrolling?

### ISSUE THREAD

**Issue by apryor6** [daattali/beautiful-jekyll#222]
Currently, code blocks wrap around instead of creating a scroll bar. This can sometimes make it difficult to read. Is there any way to enable horizontal scrolling in code blocks?

**Comment by daattali** [comment]
Can you clarify and show an example of what you mean?

Code blocks currently **do** result in a horizontal scrollbar when they're too long. I just looked at your website and it does use horizontal scrollbars:

![image](https://user-images.githubusercontent.com/952340/28231294-05e5bb58-68eb-11e7-9a2b-ddb30f073ee9.png)

**Comment by apryor6** [comment]
Ah, it's the browser. In Safari (9.1.2) it doesn't scroll, but in Chrome it does. I thought that was strange because I saw a previous issue where you had updated the CSS for `white-space`. I'm closing the issue. Thanks
