### ISSUE TITLE
Need more social buttons

### ISSUE THREAD

**Issue by TheRealBenForce** [daattali/beautiful-jekyll#233]
Great work here @daattali ! Would you be open to a pull request providing a few more buttons? Is there, any particular order you arranged them in that I should continue to adhere to?

**Comment by daattali** [comment]
Thank you for the initiative. Which buttons would you like to add?

**Comment by TheRealBenForce** [comment]
Steam and Twitch..

**Comment by daattali** [comment]
Yeah those are common enough nowadays, just make sure to follow examples of
previous people adding icons (edit the config file as well)

**Comment by TheRealBenForce** [comment]
Oops, I forgot Yelp also. Cool?

**Comment by daattali** [comment]
Yep!

**Comment by daattali** [comment]
@TheRealBenForce are you planning on adding these?

**Comment by daattali** [comment]
sorry it's already done, I forgot!
