### ISSUE TITLE
Change default page?

### ISSUE THREAD

**Issue by rccordell** [daattali/beautiful-jekyll#241]
I love the look and functionality of your theme and have been working to adapt it for a team project page at [oceanicexchanges.github.io](oceanicexchanges.github.io). We will likely do some blogging as part of the project, but that won't be our focus. I could create a different `index.html` file but that would kill the (very nice) blogging page. Is there another way to set a different page as the default while keeping the blogging page intact?

**Comment by daattali** [comment]
It is possible to do that, I've done it a few times in the past but I forget the exact steps, I always have to look it up. The full documentation for jekyll is at http://jekyllrb.com/docs/home/

I think it involves changing a setting in the config file to tell jekyll what page to serve the feed from.

You can look at https://github.com/reconhub/reconhub.github.io as an example website where I've done what you want (you can look at the config file and directory structure to see how it works)

**Comment by JovinLeong** [comment]
How is this an actual answer that warrants closing the issue?
