### ISSUE TITLE
release new gem version

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#243]
as mentioned in #237

**Comment by daattali** [comment]
I've decided to stop supporting the Ruby gem because it has too many issues. It requires a lot more work from the user than simply cloning/forking the git repo, it requires a lot more work from me to maintain two branches with similar features, and it's less flexible and harder to use. There are also issues, for example the default jekyll site built with `jekyll new` has an aboutme page that searches for a file `icon-github.html` which doesn't exist in my theme, so that causes an error.

If anyone wants to use beautiful-jekyll, I highly suggest forking from the main repo rather than using the gem

**Comment by ohadschn** [comment]
Note that gem-based themes are the [recommended Jekyll theme type](https://jekyllrb.com/docs/themes/). They might lack built-in GH pages support, but making them work [shouldn't be too much of an issue](https://4brunu.github.io/blog/2017/01/29/using-jekyll-gem-based-themes-on-github-pages). In addition, gem-based themes are actually supported out of the box on [GitLab pages](https://gitlab.com/ohadschn/ohadschn.gitlab.io), and I think a few others like Netlify.

The problem with fork-based theming is the lack of a good update story. You have to deal with multiple remotes and 3-way merging, a real pain compared to `bundle install`. What do you mean by having to maintain two separate branches BTW?

**Comment by daattali** [comment]
> what do you mean by having to maintain two separate branches?

Every change that happens to the main branch needs to be merged into here. 


You bring up good points, but I simply don't know enough ruby and jekyll to deal with this on my free time. I only made the gem initially because I wanted to experiment with it for fun, and I'm happy there is a version for it, but it's not something I can afford to maintain (at least until I decide to invest a bit more time into getting experience with ruby/gems, because right now I spend way too much time googling errors every time I try to do anything).

I personally don't use it so it was hard for me to see that it's useful. The fact that running `jekyll new` and then using this theme results in an error really put me off - is that not a big deal for people who use jekyll gems?

**Comment by ohadschn** [comment]
Hey, that's fair enough. I don't think `jekyll new` is much of a factor though as most people could just start off by forking your repo (or some blank sample repo like https://gitlab.com/pages/jekyll and copy  `index.html` and `_config.yml`).

Regarding a separate branch, I'm still not sure why you'd keep a separate branch for the gem. Why not keep the gemspec on `master`? Anyway, if you ever decide to invest a little more in this, I can recommend [minimial-mistakes](https://github.com/mmistakes/minimal-mistakes) as a reference. The owner looks like he knows what he's doing, and he maintains an up to date gem (which is what I'm currently using for [my blog](https://gitlab.com/ohadschn/ohadschn.gitlab.io)).

**Comment by daattali** [comment]
Ohad, thanks for your discussion, I'll reopen this. I may be wrong about this, but I do think 2 branches are necessary since they don't contain identical code. The master branch is specifically tailored for github pages, and the gem branch has a different structure, different readme, and slightly different files. But again, my knowledge of gems is extremely limited so maybe there is a better way to do it.

**Comment by ohadschn** [comment]
Sure thing Dean, thanks for listening. I am far from a gem expert myself but I do believe Minimal Mistakes only has a master branch and his theme is both GH-page ready and gem-enabled. You can take a look at his [gemspec](https://github.com/mmistakes/minimal-mistakes/blob/master/minimal-mistakes-jekyll.gemspec), maybe it'll give you some ideas. He is also extremely responsive and helpful, you could open an issue asking him about it and I'm sure he'll give you a good answer.

**Comment by daattali** [comment]
Yep he does indeed have just one branch. I chose to use a different branch so that I wouldn't have to change the file structure (moving all the assets into `assets/`) and so that the README would be specific for github users on master, and to ruby gem users on the gem version. Maybe it's not worth the hassle of keeping them separate only for that though :)

**Comment by ohadschn** [comment]
IMHO, Definitely not worth the hassle :)

BTW, personally I would recommend everyone to use Git**Lab** pages with out of the box support for gem-based themes - it works great!

**Comment by daattali** [comment]
Perhaps. I'm currently still a github fanboy. And this theme was created
with the intent of being focused on people who want to create github pages,
that's still how I try to keep it. I might reconsider later. You've done
enough convincing for today, maybe try again tomorrow :) layla tov
