### ISSUE TITLE
[Question] How do I change the amount of posts on the home page?

### ISSUE THREAD

**Issue by sipart** [daattali/beautiful-jekyll#245]
Sorry for what might be a simple question but how do I extend the amount of posts on the home page - I would like to have 10 instead of 5 :-)

Thanks for getting me hooked on creating a github page and posting - really appreciate how easy it was.

Cheers

https://sipart.github.io/

**Comment by daattali** [comment]
In the _config.yml file, look for the line `paginate: 5` and change it to 10

**Comment by sipart** [comment]
## Cheers
