### ISSUE TITLE
Is it possible to have online drafts? 

### ISSUE THREAD

**Issue by cjsommer** [daattali/beautiful-jekyll#246]
I cannot run Jekyll locally and it would be helpful for me if I could preview my drafts on my github page before I release them to the public. Through a hidden link or something like that. I have tried using tips and tricks found https://github.com/barryclark/jekyll-now/issues/65 but have had no success. 

Was wondering if this has been brought up before or maybe someone has already done this for beautiful-jekyll?

**Comment by daattali** [comment]
It's not really a generally supported feature of jekyll to be able to preview drafts. I haven't read Barry's solution, so I'm not sure if it's very specific to his theme only or if it's applicable to any jekyll theme. But what I usually do before publishing a post, to view it for formatting and proof reading, is I create it in a random page, for example `test.md` and then I go to `mysite.github.io/test` to view it. It won't be 100% identical to how it would appear when it's an actual blog post later, but the page will generally look the same. You may even be able to add a `layout: post` to make it a bit more like a post, although I don't do it and have good results.

**Comment by cjsommer** [comment]
My problem is I have RSS feeds that automatically get posted to Slack once my post goes in the _posts folder and I push it to Github. Thankfully VS Code's markdown features and plugins give me a pretty good view of ow my post ill look before I push to Github, I just thought Barry's solution was pretty slick.

I fiddled around with it for a while but couldn't get it to work like he did. I was able to prevent the draft: true posts from displaying, but I could not get a direct link to my draft posts to work.

Maybe I'll spend some more time on it when I have some time.

**Comment by daattali** [comment]
I'm sorry I don't think I'll have time to look at Barry's source code to see what he does with drafts. But I think what I suggested--simply placing the content in a file that is not under _posts--should work too

**Comment by daattali** [comment]
@cjsommer is that solution sufficient for you?

**Comment by lostmsu** [comment]
@daattali if I do this, I can only place the `.md` file in the root folder, right? `_drafts` would not work?

**Comment by daattali** [comment]
@lostmsu My understanding of jekyll is that files under `_drafts` are not published - that's a special folder for jekyll.

**Comment by Timmmm** [comment]
Just to confirm, because the implicit nature of all this means it isn't obvious:

* `/_drafts/foo.md` -> Not published
* `/_wip/foo.md` -> Also not published (seems like anything that starts with `_` is special?)
* `/foo.md` -> Published at `/foo/`
* `/wip/foo.md` -> Published at `/wip/foo/`

So I think the best solution is to make a folder called `wip` or `drafts` and put your files in there.

**Comment by daattali** [comment]
This isn't a beautifuljekyll specific suggestion,  it's just Jekyll in general. I think that's correct, but it's best to ask in a Jekyll forum

**Comment by Timmmm** [comment]
Sorry my comment wasn't clear - I wasn't asking if it was the case - I was stating that it is the case, for future people like me who find this from Google.

**Comment by daattali** [comment]
Ah ok, great!
