### ISSUE TITLE
Post and Page Templates

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#253]
Hi Dean,
what do you think about adding a basic template file for new posts/pages?

Especially for the possible *YAML Front Matter* variables and their meanings?

Maybe something like this:

```
---
layout: # page | post (blog) | minimal
title:	# Page or blog post title
subtitle: # Short description of page or blog post that goes under the title
image: # /path/to/img
show-avatar:  #(false) | true
bigimg:	# /path/to/img - or multiple entries <- "Path": "Description">
category: # Powershell
tags: # [tag1, tag2, tag3]

# ---- Jekyll optional vars ---- #
# date: # overrides tha tage from the file name YYYY-MM-DD HH:MM:SS
# permalink: # (default /year/month/day/title.html)
# published: # (true) | false

# ---- Theme based optional vars ---- #
# comments: # (false) | true
# show-avatar: # (true) | false
# social-share: # If you don't want to show buttons to share a blog post on social media, use social-share: false (this feature is turned on by default).
# use-site-title: # (false) | true
---

**Content**
* TOC Placeholder
{:toc}
```

So it would be easier for users starting a new page/post without jumping back and forth between the readme and actual file.

**Comment by daattali** [comment]
Hi Marco, I think this would be very useful for some people, but those are likely the people who wouldn't really need this kind of help. I'm trying to think of the jekyll/internet noobs (that was always the focus of this theme - make something incredibly simple with instructions that hopefully my mom could follow and use) and I think for them this page would be intimidating and they wouldn't know what to do with it. The brackets, the `|` signs, the fact that they need to type the value after the field name but before the comment character - I think this is convenient for people who understand this but for the majority of people who are not power users it can be offputting.

**Comment by OCram85** [comment]
I'm ok with that.
I came up with the template idea when I first started with beatuiful-jekyll. I was trying to create a overview fo the possible vars in the front matter area of a post. I know there are some mandatory and optional feature realted vars.

But I absolutely understand to keep it as simple as possible. Simplicity always wins^^

**Comment by daattali** [comment]
I think title is the only mandatory field. Although even if you don't set that
