### ISSUE TITLE
PR for badges

### ISSUE THREAD

**Issue by yonicd** [daattali/beautiful-jekyll#259]
i want to create a PR for the badges in the [_layouts/post.html](https://github.com/yonicd/yonicd.github.io/blob/master/_layouts/post.html#L11_L55) but it was added after a lot of commits to other things. how can i create a PR for only that file? if it's not possible you can just ctrl-c+ctrl-v the new script for the badges. there isnt any additional script needed to create them.

**Comment by daattali** [comment]
I don't think there's any magical way to do it nicely, I think a PR needs
to be made against the current version :/

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
this has been implemented
