### ISSUE TITLE
Fix mixed indentation in files

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#260]
I noticed mixed indentation in various files.  The indentation should be 4 spaces per level.

Reworking on this could cause 2 problems:
- One giant commit / PR with all the touched files.
- Running into problems with  [rendered whitespaces](https://shopify.github.io/liquid/basics/whitespace/) with liquid content. 

I think I could help working this out in near future.

**Comment by daattali** [comment]
Yep, those are two valid concerns. It may be a giant PR, there's no way to avoid that, that's ok. The rendered whitespace issue just means that we need to be smart about what files and lines get their whitespace "fixed", which I think will end up just being some manual labour :/

**Comment by OCram85** [comment]
Maybe the best way is a commit per file. You are right. The only way to
make sure the change didn't caused any other side effects would be to
compare the rendered file before and after the change...

Am 04.10.2017 19:01 schrieb "Dean Attali" <notifications@github.com>:

Yep, those are two valid concerns. It may be a giant PR, there's no way to
avoid that, that's ok. The rendered whitespace issue just means that we
need to be smart about what files and lines get their whitespace "fixed",
which I think will end up just being some manual labour :/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/beautiful-jekyll/issues/260#issuecomment-334222397>,
or mute the thread

**Comment by daattali** [comment]
I think it's fine to do just one bit commit instead of one per file

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by OCram85** [comment]
You're absolutely right. Maybe #261 could help...

**Comment by OCram85** [comment]
Duplicate - #270
