### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by glederrey** [daattali/beautiful-jekyll#263]
It seems that there's a problem with docker. 

When I run the docker command, I get these results: 

```
Configuration file: /app/_config.yml
Configuration file: /app/_config.yml
            Source: /app
       Destination: /app/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.206 seconds.
 Auto-regeneration: enabled for '/app'
Configuration file: /app/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

The problem is that it's listening on **127.0.0.1** instead of **0.0.0.0**. Therefore, when I try to curl it or to connect to `http://localhost:4000`, I get a connection reset. 

Does anyone knows how to fix this? Thanks!

**Comment by OCram85** [comment]
You can adjust the `bundle exec jekyll serve` command with this additional vars in `_config.yml`

```YAML
# Serving
port:    4000
host:    127.0.0.1
```

**Comment by glederrey** [comment]
I will look at this. Thanks!

**Comment by daattali** [comment]
@OCram85 as you may know, I'm not a ruby expert and don't use a lot of jekyll locally (mostly through github pages). Would you recommend adding these params to the config file, or do you foresee it being problematic for some people?

**Comment by OCram85** [comment]
Personally,  I wouldn't add these vars in the _config.yml.

Why? - I think 90% of the basic users can build and run jekyll with the
default values.
Second, you could override the default in special use cases with `bundle
exec jekyll serve --host 0.0.0.0`

But that's only my personal opinion ^^

Am 05.10.2017 19:50 schrieb "Dean Attali" <notifications@github.com>:

**Comment by glederrey** [comment]
Thanks a lot @OCram85 !

If I can make a suggestion, I would add the following information in the paragraph:

---

*Note*: If you cannot access your website at http://localhost:4000 due to a *connection reset by peer*, check if the terminal is displaying the following:
```
Configuration file: /app/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
If it is the case, you can override the default host by adding `--host 0.0.0.0` after `bundle exec jekyll serve`. You should now see:
```
Configuration file: /app/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```
Your website should not be accessible at http://localhost:4000

---

What do you think about this? @OCram85 @daattali

**Comment by OCram85** [comment]
If it doesn't cause any other side effects we could change the jekyll command in the `Dockerfile` into this:
```YAML
CMD bundle exec jekyll serve --host 0.0.0.0 --port 4000
```

@glederrey: I always like additional notes for debugging, but @daattali  has to decide this ^^ ... I'm not a maintainer - just an average user who :heart: beautiful-jekyll.

**Comment by glederrey** [comment]
Since you said that for 90% of the users, the command given should work, I didn't want to change it. Adding an additional note for the poor users as me is always a good thing.. =)

But if you think that it shouldn't change anything, then @daattali can directly change the command, yes. 
And I asked your opinion since your found the fix of my problem. =)

**Comment by daattali** [comment]
I've added a small note in the readme: https://github.com/daattali/beautiful-jekyll/commit/1194093d71240d5beff312eb32b7b3520e31978e

I really don't want to take up too much resources and space for this because if you're using Docker then you're not a super beginner and you likely can google/stackoverflow to solve more advanced problems. I want to focus the theme more on the average basic user. Thanks for your comments!

**Comment by glederrey** [comment]
That's perfect! If other people face the same problem, they will find the solution directly. 

Thanks a lot @daattali

**Comment by mucst** [comment]
@glederrey 's solutuion worked for me. 
I am running a `ruby:2.7-bullseye` based container and had this "Connection was reset" issue. After setting the `host` in `_config.yml` (or appending the `--host` argument, everything worked like a charm.
