### ISSUE TITLE
index page is a problem!!!! I dont know why

### ISSUE THREAD

**Issue by cihatix** [daattali/beautiful-jekyll#267]
I downloaded this theme from GitHub to my ubuntu desktop. I changed the __config.yaml file. 
Everything is ok. But,

I run "jekyll serve" command and opened 127.0.0.1:4000 web page. 
in the front page, there is a problem. I cannot see any feature about the theme. When I visit the posts everything is ok. Can you help me how to fix this

**Comment by daattali** [comment]
Hello, it's possible that maybe you don't have a proper index page? Try copying the index.html page from this project into your site's root directory.

Other than that, I can't really help much with this debugging. As I say in the README:

> Disclaimer: I personally am NOT using local development so I don't know much about running Jekyll locally. If you follow this route, please don't ask me questions because unfortunately I honestly won't be able to help!

I honestly do not know much about jekyll outside of github so I'm afraid I can't help, sorry. You might have better luck asking on jekyll specific online forums
