### ISSUE TITLE
.navbar-toggle:focus color persistence after hidden.bs.collapse

### ISSUE THREAD

**Issue by jennydaman** [daattali/beautiful-jekyll#268]
Addresses the issue mentioned here: https://github.com/daattali/beautiful-jekyll/pull/256#issuecomment-337092241

![screenshot from 2017-10-16 21-28-33](https://user-images.githubusercontent.com/20404439/31642452-0954382e-b2b9-11e7-8ec2-58d693831d5e.png)

I noticed some awkward attribute stuff going on. Bootstrap is probably to blame (though I did not review its 6567 + 2307 SLOC). 

1. Assuming the screen width is less than 760px, `navbar-toggle` will be shown. 
2. Clicking on `navbar-toggle` once will expand `navlinks-children` (JS event: `show.bs.collapse`). **A new HTML attribute is initialized, `aria-expanded="true"`**
3. Clicking on `navbar-toggle` a second time will hide `navlinks-children` (JS event: `hidden.bs.collapse`). **`aria-expanded="false"`, and a new class is added as well: `collapsed`**

I tried to fix the bug: https://github.com/daattali/beautiful-jekyll/compare/master...jennydaman:fix-navbar-toggle

How my patch works is that, when the `collapsed` class is introduced, the new CSS rule for `button.navbar-toggle.collapsed:hover` takes priority. 

The solution works on desktops, even though it's essentially duct tape over a crack. 

**However, this patch does not work on mobile/touchscreen devices**, defeating the whole purpose. This is what I think is happening. When a user taps on `navbar-toggle` to hide the `navlinks-children`, their virtual pointer *lingers on the button* so the `:hover` state persists. 

I tried to cover this up using JavaScript in `js/main.js`, but it didn't work. (`jquery-1.11.2.min.js` is *very outdated*. Might be an issue?) 

I predict a functional fix for this bug on touchscreen devices would require impractical workarounds or direct modification of third party scripts. Might be best to just ignore it too, or to delete rules about `:hover` altogether for the sake of consistency... The perfectionist in me cringes.

(I'll worry about pull request #256 after this issue is resolved.)

**Comment by daattali** [comment]
Wow I never realied bootstrap's navbar toggle feature was this awkward. Sorry you have to go through this! If it doesn't fix it on mobile, then I wouldn't want to merge it. The perfectionist in *me* just can't do that :)

This bug with the navbar toggle focus presisting doesn't actually have anything to do with your PR though, does it? Your PR changes the text colour of navbar, and the hover colour **of links**. This navbar toggle button is not a hyperlink and isn't affected. It's a separate issue. I think you can still continue with your original PR as it doesn't change anything about that bug. Am I mistaken?

**Comment by jennydaman** [comment]
I intend on making another commit to my PR so that the `navbar-toggle` button changes color to the link hover color. 

Depending on your decision about this issue, then how I'd go about handling that would be different. I'll just leave this issue alone for now and make one last commit tomorrow about the `navbar-toggle` button color.

**Comment by daattali** [comment]
I wouldn't want a fix that only fixed desktops but not smaller screens. I'd prefer to have broken functionality on both :p

**Comment by jennydaman** [comment]
Found a solution while working on my own site! I pushed a commit to https://github.com/jennydaman/beautiful-jekyll/tree/colors that fixes this issue (related PR: #256). Color works on touchscreen and mobile devices.

Though it's probably bad practice to be fixing a bug in a mostly unrelated PR...

**Comment by daattali** [comment]
Awesome! Could you actually submit a separate PR that just fixes this issue please?

**Comment by daattali** [comment]
@jennydaman let me know if there's a PR for this please

**Comment by jennydaman** [comment]
Nope... I don't have a perfect solution that works on all platforms, just silly workarounds.

If your goal is consistency, I advise that you get rid of any `:hover` effect on the element, and keep the darker color when the menu is expanded. That is the quickest "fix."

To achieve the optimal solution, someone would have to completely rewrite how the bootstrap classes are being used. I don't have the time to read all that documentation right now... (might come back and look at this, but like in a few months)

**Comment by jennydaman** [comment]
OR how about more dirty hacks! I'm going to try something dumb right now, and report back on how it goes.

- prevent all `:hover` effects for small screens (so touchscreen pointers hovering over `.navbar-toggle` doesn't affect anything)

**Comment by jennydaman** [comment]
Let me get this clear, the ideal rules for color would be:
- normal: light
- hover: dark
- aria-expanded=true: dark

The issue comes from how touchscreens manage`:hover`. When tapping somewhere, the virtual pointer clicks once, then hovers over that point until somewhere else is clicked.

```css
button:hover {
    background-color: blue;
}
```

The code segment above works as expected on small, non-touchscreen devices. However, the button will stay blue on touchscreens if the button is tapped.

What I want to achieve is for `:hover` rules to be **ignored** on small touchscreens. That's not possible with vanilla CSS (`@media only screen and (max-width: 768px)`).

**Comment by daattali** [comment]
I didn't notice your edit on the last comment. Is there anything else you'd like to address or are we ok now after discussing this in the PR?

**Comment by jennydaman** [comment]
I have a bad habit of editing comments, whatever. I'm going to work on  #268 (colors). The commit history is messy, I'm going to start with a new branch...

**Comment by daattali** [comment]
Sounds good. I do find that after more than 5-10 minutes it's safer to just
add a new comment, even though it feels spammy

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>
