### ISSUE TITLE
combine gem branch into master branch

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#269]
so that I won't have to support development in parallel branches that are nearly identical

**Comment by gpotter2** [comment]
Nowadays with `remote_theme` supported natively by github pages, if you made a theme that followed https://jekyllrb.com/docs/themes/ it would be plug and play.

I've tested it: if you move the `css/` and `js/` folders (all non default `_something` folders) to an `assets/` folder, it works just fine.

**Comment by daattali** [comment]
That's great! I don't know anything about ruby and haven't looked into github remote  themes, so I would appreciate if you wanted to make a pull request.

**Comment by daattali** [comment]
@gpotter2 if you'd like to make a PR for this, it should be much smoother than the previous one :)

**Comment by daattali** [comment]
I've released a new gem and combined it with master. I'll add documentation soon and delete the gem branch.
