### ISSUE TITLE
[Umbrella Task] Source Cleanup

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#270]
# Meta
### :question:  About *[Umbrella Tasks]*
> [Umbrealla Tasks] are logical constructs to manage complex issues broken down in multiple small tasks. This should help with getting an overview, plan and delegate complex tasks. 

## :arrow_down_small: Blocked By _(Sub Tasks)_
- ~#264~

## :arrow_up_small: Blocks _(Parent Tasks)_

# :package: Content

## :page_facing_up: Preparation Tasks

| Ref | Summary | State |
| :---: | :--------- | :-----: |
| ~#272~ | add basic editor config for developer using VSCode | :exclamation: |
| ~#271~ | add .gitattributes to fore eol standards. | :white_check_mark: |

## :blue_book: Main Tasks
Each commit in this PR should covers a  single file. The file itself should be reworked to
- fix indentation (4 spaces per tab)
- fix liquid whitespace rendering issue for clean rendered source code.

- `./Includes`

| Ref | File | Status |
| :---: | :--- | :--------: |
| ~#273~ | `disqus.html` | :white_check_mark: |

### :mag: Post Edit Checks
You need to test the changes by 
- comparing rendered file output. 

### :bookmark: Legend
- :white_check_mark:  - file touched, fixed, and checked
- :exclamation:  - :fire: :fire_engine: :boom: mhm, this didn't work
- :no_entry:  - nothing to change in this file. not touched, ignored in this PR.

## :hourglass: Workflow
- This issue description gets updated by every additional commit or change.
- Contribution or help with files is wanted and needed.

**Comment by daattali** [comment]
This issue should win a github organization award

**Comment by OCram85** [comment]
Sorry for this meta overhead. But if I don't work with github I normally use phabricator. It has some usefull issue managing properties which you can only get in github like this. .... Unless you don't want to addons like zenhub or waffle. But I this it would be too much...

**Comment by daattali** [comment]
No, don't apologize, it's great!
