### ISSUE TITLE
request: ResearchGate footer link

### ISSUE THREAD

**Issue by mghassany** [daattali/beautiful-jekyll#274]
To add a researchgate profile.

**Comment by daattali** [comment]
Feel free to submit a pull request to add it, just follow the format all
the other icons use

**Comment by daattali** [comment]
@mghassany I'm closing this issue as nobody else seemed to want it. Feel free to implement it if you'd like

**Comment by mghassany** [comment]
OK.
As for me, I finally used the researchgate icon from http://jpswalsh.github.io/academicons/
