### ISSUE TITLE
Markdown guide reference

### ISSUE THREAD

**Issue by murillocg** [daattali/beautiful-jekyll#275]
I had some difficulties to use table in a post.
Sounds like this markdown doesn't work: https://help.github.com/articles/organizing-information-with-tables/

Which markdown reference I should use to write my posts?

**Comment by daattali** [comment]
This is exactly the purpose of the first demo "blog post": https://github.com/daattali/beautiful-jekyll/blob/master/_posts/2015-02-28-test-markdown.md

Look at the source (raw version) of that file and you'll see how to create a table

**Comment by murillocg** [comment]
Thank you very much!
