### ISSUE TITLE
white space between bigimg and footer when blog moved

### ISSUE THREAD

**Issue by ericpgreen** [daattali/beautiful-jekyll#288]
@daattali, great theme. Thanks for all of your work on it. 

I moved the blog off the landing page using your instructions, and now I'm trying to remove the white space that remains between the bigimg and the footer. Have you come across this before?

![image](https://user-images.githubusercontent.com/546433/33226503-5e5b8d3c-d15d-11e7-9147-3aada0a3bdd4.png)

**Comment by ericpgreen** [comment]
I know that `index.html` uses the `page` layout. I'm a bit out of my element, but I see that `page.html` (in `_layouts`) uses the `base` layout and includes:

```
{% include header.html type="page" %}

<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      {{ content }}
	    {% if page.comments %}
        <div class="disqus-comments">
	        {% include disqus.html %}
        </div>
	    {% endif %}
    </div>
  </div>
</div>
```

`base.html` includes

```
<!DOCTYPE html>
<html lang="en">
  
  {% include head.html %}
  <body>
    {% include nav.html %}
    {{ content }}
    {% include footer.html %}
    {% include footer-scripts.html %}
  </body>
</html>
```

I tried creating a referencing a new `page` layout and a new `base` layout, but I haven't stumbled on the right parameter to show just the header, `bigimg`, and footer on the main `index.html` page. Any tips to get me moving in the right direction @daattali?

**Comment by daattali** [comment]
The whitespace issue you're seeing is not because of the template. It's purely CSS. Looking at the CSS on the page, the `footer` tag has a `margin-top` of 50px and the big-img in the header has a `margin-bottom` of 20px. If you remove these margins, there won't be any gap. You'll need to know basic CSS to do that

**Comment by ericpgreen** [comment]
Ah, ok. Thanks for your advice. Did the trick.
