### ISSUE TITLE
How to deploy on https://app.netlify.com/

### ISSUE THREAD

**Issue by HashHackerAds** [daattali/beautiful-jekyll#291]
Any Help

**Comment by daattali** [comment]
Sorry that's out of scope for a jekyll site. I haven't tried it but I'm
sure there are tutorials on netlify!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Attend my 4-day workshop: Learn how to analyze data with R and create Shiny
apps. 15% discount to existing clients. Register here!
<https://www.eventbrite.com/e/modern-r-data-processing-visualization-and-reporting-with-r-tickets-39862492789?aff=deanemail>
