### ISSUE TITLE
Invisible avatar is still clickable in .top-nav-short

### ISSUE THREAD

**Issue by alefi87** [daattali/beautiful-jekyll#293]
When scrolling so the avatar fades out and the main nav turns "short" the avatar is still clickable. You can't see it, but the hitbox is still there, so it's a bit confusing, not to mention that it might hijack clicks on some of the content under it (e.g. another link in the text).

I guess that one is tough to solve with pure CSS since `display` is not affected by `transition` rules, but since JS is used for certain functionality, perhaps the avatar animation might as well be done with something like `jQuery('.avatar-container img').fadeOut(500)`?

**Comment by daattali** [comment]
You're right that's a behaviour I've known about for a while but never
seemed to actually bother anyone. If you find a clean way to fix it, you're
welcome to submit a PR!

**Comment by alefi87** [comment]
Submitted a PR. Disregard the git weirdness above - it's just one commit and minor changes to two files.

**Comment by daattali** [comment]
thank you!
