### ISSUE TITLE
support navbar links to external pages

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#3]

**Comment by daattali** [comment]
nobody seems to want this, so closing (will reopen and work on it if there's demand)

**Comment by isomerase** [comment]
+1!

**Comment by daattali** [comment]
@isomerase noted.  Will add this soon once I get a bit of time

**Comment by daattali** [comment]
this has been implemented

**Comment by isomerase** [comment]
<3

**Comment by daattali** [comment]
My girlfriend would not appreciate that comment.
