### ISSUE TITLE
Add logo to the website (favicon)

### ISSUE THREAD

**Issue by niccokunzmann** [daattali/beautiful-jekyll#312]
I added a favicon option for the website. This is useful, if we want to use an image.

Website: http://hashtec-potsdam.github.io/
Source code commit: https://github.com/HashTec-Potsdam/HashTec-Potsdam.github.io/commit/2ebbc64eae5e3cdb18128a7e8aae5da01e81acee#diff-aeb42283af8ef8e9da40ededd3ae2ab2

I realize, you personally will not need this as your site provides a favicon at the top.

So, what I would like to ask:
Is a contribution to this site welcome if it contains the favicon functionality as posted above?

**Comment by daattali** [comment]
Thanks for the suggestion!

Technically you don't even need to add that line to the HTML. Simply placing a valid favicon in the root is enough. So because I like to keep this theme and settings as simple as possible, I'd rather not add this setting since it's not necessary.

**Comment by vinisalazar** [comment]
Hi @daattali . First thank you for this wonderful theme. I am having trouble placing a favicon.  I placed a favicon.ico image in the root and added this line to the _config.yml:
`favicon: "/favicon.ico"`

It did not work. Am I missing something?

Thanks

**Comment by utkuozsan** [comment]
Hi @vinisalazar,
Add the below line to _includes/head.html under <head> section.It will work.
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?">

**Comment by wfsimao** [comment]
Hi @niccokunzmann , put the image in the **/img** folder.
Add this line to **_include/head.html** <link rel="icon" href="{{site.baseurl}}/img/favicon.png">

**Comment by cryptic0** [comment]
> Hi @niccokunzmann , put the image in the **/img** folder.
> Add this line to **_include/head.html**

Which line?  In any case, edit by @utkuozsan works which keeps the favicon in the root.
