### ISSUE TITLE
tags/categories

### ISSUE THREAD

**Issue by ajkl** [daattali/beautiful-jekyll#32]
is there a way to create tags/categories for posts ?

**Comment by daattali** [comment]
We've just talked about this in person, but I'll post the answer here for anyone in the future who has a similar question.

Somebody once sent me [this github pages website](http://amunategui.github.io/) and asked me how to do something similar (a page that shows all posts of a specific tag). If you look at the github repo for that website https://github.com/amunategui/amunategui.github.io, you can see what he's doing and copy it. It works, but it's just a bit hacky. In the github repo for his website, you'll see he has a "tags" folder. Inside that folder, he has a folder for each of his tags, and inside each tag's folder he has an index.html that looks at all the posts and only shows the ones that have this tag.  So you can do that if you'd like, but I prefer not to.
