### ISSUE TITLE
[Question] How to have more than one posts pages like the main page?

### ISSUE THREAD

**Issue by datamancy-dev** [daattali/beautiful-jekyll#329]
Hello Dean, first off thanks for making this awesome theme! 

I would like to have two "main" pages that draw from separate posts directories.

So the end result would be a link on the navbar that takes you to a different page like the main page that has posts that you can click on specific to that page. These posts should in turn redirect to the post itself like the main page works.  

Is that possible? Thanks for all your support and work.

**Comment by daattali** [comment]
I think this is possible. It's a general jekyll question though, not specific to my theme. You can read the jekyll documentation to see if you find a solution https://jekyllrb.com/docs/pagination/ or you can ask on a jekyll-specific forum https://jekyllrb.com/help/

**Comment by datamancy-dev** [comment]
Thanks!
