### ISSUE TITLE
Remove the hardcoded JS and CSS that resulted from github migrating to jekyll3

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#33]
On 2016-02-01 GitHub decided to upgrade to Jekyll v3 without warning us.  This caused a lot of breakage.  As a very quick and dirty fix, I hardcoded css and javascript in two files. Hopefully there's be a nicer fix eventually (this affects the master branch and gh-pages branch)

1947c4907e3bf3a3e4d2f5bf76ed3e529b9f90d1
6d0fff729ad47234491d49ab48c0ac9b4e7bc946

**Comment by sillasgonzaga** [comment]
Many thanks for the quick fix. My blog is based on your personal template so I went nuts when I got an email from Github with some warning after I published a post.

**Comment by daattali** [comment]
Oh , I went nuts for a few hours trying to figure out what's broken... :)  I files this issue with jekyll but unfortunately it doesn't seem like it's going to be addressed https://github.com/jekyll/jekyll/issues/4439

**Comment by sunieldalal** [comment]
Thanks a lot Daattali for the quick fix!

**Comment by daattali** [comment]
@sillasgonzaga @sunieldalal instead of saying thank you, I'd really appreciate if you could post on jekyll/jekyll#4439 to let jekyll know that this issue is affecting more people so that they'll take a look :) The solution I put in place is not great, but I'm glad you guys found it

**Comment by daattali** [comment]
@sillasgonzaga @sunieldalal I implemented a better fix, still not ideal, but it's less hacky and will generalize better. Feel free to use it too, see https://github.com/daattali/beautiful-jekyll/commit/9197b79d9d4d96ca6e2e935814ca92079bd71791 and https://github.com/daattali/beautiful-jekyll/commit/57539e35e86ba9c55886da8ea54a87cdbf8e75ca

**Comment by sunieldalal** [comment]
Thanks @daattali..

**Comment by kootenpv** [comment]
Thanks for the fix, I also went nuts. Came to post an issue; glad it was already solved! Good job :)

**Comment by daattali** [comment]
@kootenpv Glad to hear it's helping people. I really hope Jekyll will have a proper fix on their end at some point!

**Comment by daattali** [comment]
Jekyll recently fixed the bug
