### ISSUE TITLE
Text Selection Colour is White

### ISSUE THREAD

**Issue by adivijaykumar** [daattali/beautiful-jekyll#330]
Whenever I select text in a post on my site adivijaykumar.github.io, the selection colour is white, which means it is not actually visible at all! Do you know what could be the reason?

![screenshot_2018-03-07-20-40-15-375_com android chrome](https://user-images.githubusercontent.com/11767643/37100209-60224ae8-2248-11e8-8a00-0900829e56af.png)

**Comment by shyd** [comment]
Hi, you probably didn't set `hover-col` in `_config.yml:50`: https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml#L50

`::selection` renders like this on your site:

```
::selection {
  color: white;
  text-shadow: none;
  background-color: ;
}
```

`background-color` is the selection background color, but it's empty.

**Comment by adivijaykumar** [comment]
@shyd Thank You! This worked well, I had probably edited out some colours when I was tweaking.
And thank you for building this wonderful theme :)

**Comment by daattali** [comment]
Thank you for answering @shyd

**Comment by shyd** [comment]
You are both welcome 😃
