### ISSUE TITLE
Posts file to be renamed with date format

### ISSUE THREAD

**Issue by devaroop** [daattali/beautiful-jekyll#332]
First of all - this project is super helpful. Thanks for that.

Any new post file has to have the `date` prepended to the file name or else does not show up in the blog list.

For e.g.:

`_posts/custom_blog_post.md` doesn't work 

but

`_posts/2018-03-14-custom-blog-post.md` works.

If this is a feature, lets add this in the documentation for everyone's help.

**Comment by daattali** [comment]
That's right. Posts have to have this format. It's in the jekyll documentation https://jekyllrb.com/docs/posts/

**Comment by bidyutchanda** [comment]
I racked my brain over this. Thank you. Hi @daattali , I think you should add this as a bold text in the repo's readme.

**Comment by daattali** [comment]
Sure, feel free to add it to the README at the appropriate place and I'll accept the PR
