### ISSUE TITLE
JS loading order problem

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#342]
I've noticed a problem caused by the loading order of the JS files

## Scenario
- Add a custom Javascript file in a new blog post or page by:
  - using the YAML key js
  - writing your Javascript directly in the file within the `<script>` tag
- If you're using jQuery or other frameworks which were defined in the layout the execution fails

## Analysis

The include snipped `footer-scripts.hml` adds the `js` files in the wrong order. It adds the custom files first instead of the layout and global wide files. This results into an situation where you can't use jQuery, Ajax or Bootstrap related functions because the were loaded afterwards...

**Comment by daattali** [comment]
This sounds like an easy fix if anybody wants to submit a PR
