### ISSUE TITLE
add padding to .post-image

### ISSUE THREAD

**Issue by mwirt** [daattali/beautiful-jekyll#363]
Just a suggestion--
.post-image rubs up against the preview text of blog posts on the left on tablet/midsized viewports, on the bottom on narrow ones. consider adding padding/margin on the left and bottom to give more whitespace. great theme btw i'm working with it to make a blog for my mom <3

**Comment by daattali** [comment]
Can you please show an example before and after your suggested change? Thanks!

**Comment by mwirt** [comment]
this might be personal preference, but adding whitespace to post-image(not really an issue at wider widths, only tablet/mobile) to me makes things look a little more structurally in sync.



### as is tablet:  



> ![nopad](https://user-images.githubusercontent.com/15525514/41314728-9aae4090-6e5b-11e8-8a93-ef0184c85563.png)  
  


### w/ 15px padding-left tablet:  



> ![wpad](https://user-images.githubusercontent.com/15525514/41314771-af7dc428-6e5b-11e8-92c7-9eb7d76366c9.png)  
  


### as is mobile:  
  


> ![mobnopad](https://user-images.githubusercontent.com/15525514/41314829-d5534448-6e5b-11e8-9b75-1c4d4dea6808.png)  
  


### w/ 15 px margin-bottom mobile:  



> ![mobwpad](https://user-images.githubusercontent.com/15525514/41314861-e6c174c0-6e5b-11e8-9c6f-9cc49ad72d24.png)

**Comment by daattali** [comment]
For the tablet, it seems that when you pushed it , the image was no longer a perfect circle. If you could submit a PR that ensures the UI doesn't break in any screen setting, I would happily merge it
