### ISSUE TITLE
Footer not at the bottom of page

### ISSUE THREAD

**Issue by antnh6** [daattali/beautiful-jekyll#364]
I was hoping if anyone could give me some pointers on how to fix the problem with my footer on my landing page.  I've tried modifying the margins in aboutme.css, but it still didn't fix the issue. 

So here is what I have in my `aboutme.css` which I linked to the front matter of my `index.html` in the form `css: "/css/aboutme.css"`

```
#aboutme-section {
  font-size: 19px;
}

.about-text {
  position: relative;
  margin-left: 30px;
}

.about-icon {
  font-size: 24px;
  position: absolute;
  left: -40px;
  margin-top: 5px;
}

#aboutme-section p:last-child {
  margin-bottom: 0;
}

#contactme-section {
  font-size: 19px;
  margin-top: 60px;
}

#contactme-section h1 {
  font-size: 50px;
}

#contact-form p {
  font-size: 100px;
  margin-bottom: 0px; 
  /* the value was 10 */
}

#contact-form .form-control {
  margin-bottom: 0px;
  /* the value was 15 */
}

#paypalbtn {
  text-align: center;
}

#paypalbtn a {
  text-decoration: none;
  font-size: 1.2em;
  font-family: arial;
}
```
Everywhere is fine. Only the landing page has this issue.

I hope you don't mind me using the terminal to cover some of the contents of my half-finished site.
![selection_003](https://user-images.githubusercontent.com/12288545/41198364-cd719fc0-6c46-11e8-9b1e-d33bbd75efeb.png)

Thank you very much!

**Comment by daattali** [comment]
This may be the very common HTML problem of how to make a footer stick to
the bottom. It's not specific to this theme, it's a widespread problem. Try
googling for "html footer bottom" or similar words and you'll see there
isn't a one size fits all solution.

**Comment by antnh6** [comment]
Thanks so much for replying so quickly. I will look into that right away. 

Do you happen to know how to fix this problem where the avatar circle lays on top of the sections in the title bar when I resize to a smaller window? Ty again.
![selection_001](https://user-images.githubusercontent.com/12288545/41203999-016b98ce-6cad-11e8-893e-70deb5b721c1.png)

**Comment by daattali** [comment]
That's just what happens if you make your window too small and you have too
many menu items. It's not possible to create something that will fit any
amount of text on any type of screen and look good for everything. But if
you want you can change the CSS so that the circle will move down more and
be underneath the navigation bar instead of in it. That should only involve
a couple css modifications

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>
