### ISSUE TITLE
Code fences render differently on the bundled version of jekyll than on Github Pages.

### ISSUE THREAD

**Issue by hkhanna** [daattali/beautiful-jekyll#365]
Code fences render differently on the bundled version of jekyll than on Github Pages. 

Github Pages:
![image](https://user-images.githubusercontent.com/222784/41325187-f808c62c-6e86-11e8-9109-463934bbccbe.png)

Locally with Jekyll 3.5.2:
![image](https://user-images.githubusercontent.com/222784/41325209-1f6e43a4-6e87-11e8-9386-3f82b901fa18.png)

I've narrowed the issue to the fact that GHP seems to insert a `<div class="highlight">` before the `<pre class="highlight">` which triggers a rule in `main.css` that sets `padding: 0`. 

```
.highlight > pre {
  padding: 0;
}
```

**Comment by daattali** [comment]
Thanks! You can submit a PR that adds a padding to the github page css that matches whatever padding should be there
