### ISSUE TITLE
_config.yml error

### ISSUE THREAD

**Issue by mark62726** [daattali/beautiful-jekyll#368]
Hi man, good job on your theme 🍡 
My error happend whenever i uncomment a line on _config (i.e  navbar-img: "/img/test.png"), the github page send me an error 
"Your site is having problems building: You have an error on line 7 of your _config.yml file. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/."
But the line 7 is fine, i never touch it just uncomment and the error happen
Then i comment it again, and everything works again
![image](https://user-images.githubusercontent.com/12106700/42073822-cc9ef1b6-7b36-11e8-8d40-35936d9f7aa6.png)

**Comment by mark62726** [comment]
NVM i resolve it by not uncoment a line, just write a new line with the same content

**Comment by daattali** [comment]
What was the problem exactly?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by mark62726** [comment]
Hi man, thanks for the reply, the problem was:
When i uncomment a line in _config.yml the page deployment send me the error "Your site is having problems building..."
![img](https://raw.githubusercontent.com/mark62726/img-hosting/master/config.yml%20uncomment.png)

So i left the comented line and wrote a new with updated content
Thats how i fixed the issue
![img](https://raw.githubusercontent.com/mark62726/img-hosting/master/new-line.png)

**Comment by daattali** [comment]
I notice there is a space in the beginning of the line in the first image -
I wonder if that was the error? If you add a space as the first character
in line 44, does it break again?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>
