### ISSUE TITLE
bigimg incorporation

### ISSUE THREAD

**Issue by sfxfactor** [daattali/beautiful-jekyll#37]
Can you incorporate the bigimg headers you have on your personal website into the general distribution?

**Comment by daattali** [comment]
I think you're right, I should. I've seen dozens of people copying my personal website instead of beautiful jekyll because they wanted those images.  I'll do it, but probably not in the next few weeks as I'm extremely busy. Thanks for bringing it up

**Comment by daattali** [comment]
@sfxfactor this is now in beautiful jekyll. You can either pass a single image or a list of images to cycle through on any page with the `bigimg` YAML

**Comment by cryptic0** [comment]
It is not clear how to supply a list of images.  I can get one image to work with ``bigimg: img/test.jpg``, and I have tried various versions to provide multiple images, but I am not getting the syntax correct.

```bash
bigimg: img/rotate/
bigimg: img/rotate/*.jpg
bigimg: img/rotate/test1.jpg,test2.jpg,test3.jpg
```

**Comment by daattali** [comment]
you can look at my website on github to see an example

**Comment by cryptic0** [comment]
I took a look, but it's not clear what options were removed from the yaml header for this page.  I don't see the yaml header in your website's ``index.html`` page. Was it removed and the page was fully written manually?

**Comment by daattali** [comment]
https://github.com/daattali/daattali.github.io/blob/master/index.html

I'm not sure what you mean by options that were removed. That is the index page for my website and it shows how to use bigimg.
