### ISSUE TITLE
[Question] - Remove center logo

### ISSUE THREAD

**Issue by 0xtf** [daattali/beautiful-jekyll#370]
Hi there,

First of all, great work on the project! Much appreciated. 

With the option of having the logo to the left of the navigation bar, I was wondering if there's an easy to remove the logo from the middle of the bar?

Didn't feel like butchering the CSS :) 

Thank you!

**Comment by daattali** [comment]
I think you're talking about the avatar? Look in the config file for the
avatar line and remove it

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by 0xtf** [comment]
/me goes looking for the facepalm emoji

Thank you @daattali and apologizes for the noise!
