### ISSUE TITLE
[Question] Pages, baseurl and relative paths

### ISSUE THREAD

**Issue by 0xtf** [daattali/beautiful-jekyll#371]
Hi,

To make sure I wasn't, again, bringing up to discussion something that was documented, I went over a couple of websites and the documentation in this project. I couldn't find anything that answered this question. 

It appears individual pages are being presented as site/page/, which makes for relative URLs to fail. 

Example:

/ of the website holds two files:

- index.md
- contact.md

If I have a relative path in contact.md to point to index.md, wen visiting contact.md, it will try and open site/contact/index, and not site/index. 

I changed the url and baseurl to try and get around it, as I'm using it as a project page, but couldn't figure it out. 

Any help or pointers would be greatly appreciated!

Thank you.

**Comment by 0xtf** [comment]
Hi @daattali,

Please, don't apologize. It's not a problem at all!

I decided to open this because I wasn't sure if I was doing something wrong. Now that I have confirmation I'll work on implementing it in a way that is maintainable. 

Do you have any recommendations? I don't mind adding all links with a *../page*.

**Comment by daattali** [comment]
The best thing to do would be to fix the issue I linked to, I think I gave
suggestions there how to tackle it. I believe creating a small HTML
template (as an _include file) that takes a parameter and does the
necessary checks to see if the given path is local or absolute and always
returns a predictable path is the best way forward. If you want to fix it
just on your repo, then yes using ./ vs / is correct, just note that if you
have a project page vs a user page (as described in the readme) the
behaviour of / will be different

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by 0xtf** [comment]
Thank you @daattali. Unfortunately I won't be able to help with the changes that need to take place. Wish I was though. I'll look into implementing with the small ./ vs /. 

Thanks!
