### ISSUE TITLE
please update readme.md

### ISSUE THREAD

**Issue by xorceria** [daattali/beautiful-jekyll#375]
In order to get the site running, there are some changes needed:

- add or uncomment "gem install tzinfo-data" in Gemfile
- change index.md content to any template which is not the nonexistent "home"
- execute "bundle install" + "bundle update activesupport" before trying to start the server
- execute "jekyll serve" as "bundle exec jekyll serve" or you'll never see past errors
- if you start from docker, don't think that it will automagically start serving the website, use command stated above

**Comment by daattali** [comment]
@xorceria thanks for the feedback, and I apologize for the year it took me to reply. If you could please try the current version of the readme and see what needs to be improved, I would appreciate if you could submit a Pull Request
