### ISSUE TITLE
It would be possible make this theme AMP compatible? 

### ISSUE THREAD

**Issue by JosemyDuarte** [daattali/beautiful-jekyll#377]
I don't know if it would be hard to make beautiful jekyll to follow the AMP "standard". I think that could be useful if it's possible.

https://www.ampproject.org/

**Comment by daattali** [comment]
That's a great idea! I may take a look one day when I have time, but I'd also be happy to accept contributions for this

**Comment by daattali** [comment]
I just read a little bit about how websites become AMP compliant. It seems like it's not a simple process and it actually adds a lot of complexity and looks a bit like a maintenance hell. Keeping in line with the main idea of this theme - simplicity - I decided not to support AMP
