### ISSUE TITLE
Problem after loading latest bootstrap css and js from cdnjs server

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [daattali/beautiful-jekyll#383]
Hi, I tried to use the **cdnjs** server link for latest css and js links for bootstrap, instead for **local ones**. 
Problem is that the navigation bar shifts to left with small icon.
PS: -
- I am a beginner in css and js. 
- Please see the attached screenshots
- I have also created ext-lib tag in front matter to load specific css and js as per author's wish.

![image](https://user-images.githubusercontent.com/17742733/43818057-7ecc1782-9afa-11e8-9b89-20953ad850f7.png)

![image](https://user-images.githubusercontent.com/17742733/43818078-9873916a-9afa-11e8-8766-b81ae50d3c2b.png)

**Comment by daattali** [comment]
I'm not sure what could cause that, perhaps you're loading a different css/js version than the version current being used. Try making sure you match versions.

**Comment by Kulbhushan-Chand** [comment]
Ahh. nice catch.
**The problem resolves after matching versions of js and css**. I have to use ver. 3.3.2 from cdnjs server (The same version is in the local js and css folder).
Thanks
_However if I may request to update the repository to use the latest bootstrap, would it be possible, and right now I have not the expertise to do so._
