### ISSUE TITLE
Update to Bootstrap 4

### ISSUE THREAD

**Issue by kulbhushanchand** [daattali/beautiful-jekyll#384]
**There are some issues when using latest bootstrap from cdnjs server. [Here is the link to closed  issue ](https://github.com/daattali/beautiful-jekyll/issues/383  )**. 
The theme works well on bootstrap ver 3.3.2 for both js and css. 
_**However if I may request to update the repository to use the latest bootstrap**_, would it be possible, and right now I have not the expertise to do so.

**Comment by Kulbhushan-Chand** [comment]
Thanks for the feedback. Is it possible to make it free from bootstrap via custom css, like this theme - https://github.com/mmistakes/minimal-mistakes

**Comment by OCram85** [comment]
I personally think using the bootstrap framework for beautiful-jekyll has 2 huge advantages:
- Customization to individual needs is much easier with a detailed underlying component based framework.
- Using bootstrap guarantees you the help of a big community.

Like already said, it's only my personal opinion. But maybe it could be worth thinking about a reboot for this theme with bootstrap 4 - at a given time.

**Comment by daattali** [comment]
@Kulbhushan-Chand thanks for your suggestions. I don't think the theme will ever be completely standalone, using bootstrap as a core theme adds a lot of value and consistency. While I don't see the removal of bootstrap happening, upgrading to bootstrap 4 may happen in the future

**Comment by Kulbhushan-Chand** [comment]
@OCram85  @daattali  Thanks for your feedback. You are right about bootstrap. Hope we will soon see the latest addition of bootstrap 4.

**Comment by danielmpetrov** [comment]
Would an update to the latest Bootstrap 3 (v3.3.2 -> v3.4.1) be a welcome PR?

**Comment by daattali** [comment]
@danielmpetrov is there a big benefit to upgrading within bootstrap 3? I'm not too familiar with the new features of 3.4 vs 3.3

**Comment by danielmpetrov** [comment]
@daattali Mostly bug fixes. It will also enable the theme to upgrade jQuery to version 3, which brings security fixes. There is an open PR for this as well - #357

**Comment by daattali** [comment]
Ah yes I do see that comment you made there. Are there *any* regression bugs or behaviour changes? I'd be happy to update to the latest bootstrap 3 if you can test it out a bit and make sure there are no breaking changes!

**Comment by danielmpetrov** [comment]
Since it's a point release, there wouldn't be any breaking changes, but I share your concern @daattali. I can go through it in the upcoming days and open a PR if it works out.

**Comment by daattali** [comment]
Perfect. Yes I don't anticipate big (or any) problems, but because of the
number of users affected with any change, I try to be very cautious, so
some testing would be a good idea

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com
<http://attalitech.com>

**Comment by daattali** [comment]
I've started the work on migrating to bs4 in a `bs4` branch. It's a lot more work than I imagined, there are a lot of components that break and need to be rewritten. If anybody wants to help, PRs are welcome.

**Comment by daattali** [comment]
Beautiful Jekyll now uses bootstrap 4.4.1
