### ISSUE TITLE
Why I can't use jekyll serve?

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [daattali/beautiful-jekyll#385]
Hi,
Every-time I have to use `bundle exec jekyll serve` and **it works fine**
### **_BUT_**
and when I use `jekyll serve`, i got the following error -
![image](https://user-images.githubusercontent.com/17742733/44194578-094a7700-a154-11e8-92ef-08c4c5a9acc3.png)

I tried updating the i18n in **gemfile.lock** from 0.9.1 to 0.9.5, but another version conflict in **public_suffix** appears.
![image](https://user-images.githubusercontent.com/17742733/44194672-54648a00-a154-11e8-8168-9416afd756bd.png)

![image](https://user-images.githubusercontent.com/17742733/44194689-5dedf200-a154-11e8-8bb5-a7eb3731f9b8.png)

![image](https://user-images.githubusercontent.com/17742733/44194721-8118a180-a154-11e8-81bc-c2272e8133d0.png)

**Comment by daattali** [comment]
Hello @Kulbhushan-Chand , unfortunately as I mention in the README, I cannot provide support/debugging for local installations of the theme. The theme is prioritized as a github online theme, and all the local development features have been contributed exclusively by users who are not officially affiliated with the project

**Comment by Kulbhushan-Chand** [comment]
@daattali 
**It is OK.** 
 For now I will stick to using `bundle exec jekyll serve`.

**PS. -** _Let this issue open, other may contribute for solution_
