### ISSUE TITLE
Unable to show posts under "blog" navbar

### ISSUE THREAD

**Issue by xw321** [daattali/beautiful-jekyll#389]
Hi daattali, I really enjoyed the beautiful-jekyll and I've been using it to build my own page recently. 

However I have encountered an issue when I tried to display posts under the "blog" navbar. I have created a blog folder and added an index.html to it, but posts are not listed there. I have checked with other users who has the similar layout but I couldn't find the problem.

An example layout is like [this](https://www.repidemicsconsortium.org/), where the home page doesn't have posts, and they can be found under the "news" navbar. I have tried to put the portion about post list (from index.html in root) to the HTML file under blog folder, but still not working.

Hope you can take a look, thank you.

**Comment by xw321** [comment]
nvm fixed!

**Comment by noahmanion** [comment]
How did you fix it? Having a similar problem.

**Comment by xw321** [comment]
HI, sorry for replying late. It's been a long time after I fixed this, I barely recall any details. My suggestion would be take closer look at my repository and other similar ones. I think I spent some time tweaking the _config.yml file. Good luck.

**Comment by xw321** [comment]
> How did you fix it? Having a similar problem.

HI, sorry for replying late. It's been a long time after I fixed this, I barely recall any details. My suggestion would be take closer look at my repository and other similar ones. I think I spent some time tweaking the _config.yml file. Good luck.

**Comment by TaoDFang** [comment]
yes I have same problem....

**Comment by noahmanion** [comment]
I added a directory called 'blog' and put an index file in there that contains page metadata and the code to create a post index. I also listed 'blog' in the navbar section of config.yml. You can see on my github.io repo.

**Comment by daattali** [comment]
Read the FAQ  section of the README, there's a paragraph about this.

**Comment by TaoDFang** [comment]
> I added a directory called 'blog' and put an index file in there that contains page metadata and the code to create a post index. I also listed 'blog' in the navbar section of config.yml. You can see on my github.io repo.

Thanks Man it works !

**Comment by TaoDFang** [comment]
> Read the FAQ section of the README, there's a paragraph about this.

Hi daattali, thanks for your reply. I did the same thing as README file says. But it didnt work. 
I checked other people's page. I think its import to manually change index.html file in blog fold to add blogs

**Comment by daattali** [comment]
This theme has gone through a lot of updates in the last month. If you think there are issues with the current setup+instructions (if you fork the current version of the project), feel free to fix it in the README!

**Comment by TaoDFang** [comment]
Yeah, will do this after I figure out whats really happening there. Dont want  to create problems for other people
