### ISSUE TITLE
An easy way to change the width of the post's/page's content

### ISSUE THREAD

**Issue by Shot511** [daattali/beautiful-jekyll#393]
Hey,

Is there an easy way to change the width of the post's/page's content? The default width of the content is too narrow for me.

**Comment by daattali** [comment]
You may be able to go to the different layout files (under the _layout folder) and simply change the bootstrap widths. For example, col-lg-8 can be changed to col-lg-10

**Comment by heshameraqi** [comment]
> You may be able to go to the different layout files (under the _layout folder) and simply change the bootstrap widths. For example, col-lg-8 can be changed to col-lg-10

This works, I think the issue should be closed.

**Comment by YoniChechik** [comment]
Hi, great git! 
I still have a problem with this answer because it makes the page not centered... can it be solved?

**Comment by YoniChechik** [comment]
> Hi, great git!
> I still have a problem with this answer because it makes the page not centered... can it be solved?

got it... this is for large screens (out of 12 columns...):
col-lg-10 col-lg-offset-1
