### ISSUE TITLE
Create Discourse forum for beautifuljekyll - place for people to ask questions and act as a knowledge hub

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#401]
I've been thinking about this for a long time - it'd be great to have a [Discourse](https://www.discourse.org/)-type forum where people can ask questions for quick help. I get daily emails about "how do I do X" and there are also github issues sometimes that are simple enough that many members would be able to answer. This would also open up the knowledgebase for everyone to see rather than keeping it private.

Discourse needs a server to install on, I can provide that server, but I don't have the time currently to do the installation. If anyone wants to help with installing discourse on a server I provide, please contact me. Ideally I would also like to be able to host more than one forum on that server (other projects, not only beautifuljekyll)

**Comment by aisbergde** [comment]
it would be fine to have a place where users could exchange experience. Less questions will be. Maybe an existing forum can be used, creating a subforum? Maybe something already exists?

**Comment by daattali** [comment]
A sub-forum I don't think would make much sense because there is already a general forum where people can ask questions and tag beautifuljekyll. In the first sentence unde the Support section of the readme:

> If you need any help, I suggest heading over to the [Jekyll support forum](https://talk.jekyllrb.com/).

The most useful improvement in my opinion is to create a dedicated support channel just for beautifuljekyll that other users can participate in.

**Comment by aisbergde** [comment]
the common jekyll forum is a good starting point, but there is no separate group and I cant see that tags are used or can be easy used for filtering. I use mobil access.

Something dedicated would be fine. github pages have no dedicated forum features.

I don't know how easy it would be to setup something like disqus, vanillaforum, netlify or similar. For many years I host my pages on a dedicated server, and to try jekyll is an alternative way to generate static content based on markdown. The first experiences are very good. Anyway a forum associated with the project home page would be a great idea.

**Comment by Hax4us** [comment]
Make a room on gitter

**Comment by daattali** [comment]
That's more of a chatroom than a discussion forum with independent threads, no?

**Comment by daattali** [comment]
GitHub now supports Discussions so that will be the solution to this! Anything that isn't a feature request or bug report should be hadnled in https://github.com/daattali/beautiful-jekyll/discussions
