### ISSUE TITLE
Navbar scrolling background

### ISSUE THREAD

**Issue by AzimsTech** [daattali/beautiful-jekyll#403]
![navbar](https://i.imgur.com/FQ9WIz4.gif)
Can anyone help me change/remove this **white** **background** from navbar without changing entire web page color?

**Comment by AzimsTech** [comment]
Solved by removing navbar transition animation entirely. https://github.com/AzimsTech/AzimsTech.github.io/commit/7bae1e62bae349407ea6429916686e6cf416689c

**Comment by Kulbhushan-Chand** [comment]
@AzimsTech how you have created gif of desktop screen?

**Comment by AzimsTech** [comment]
@Kulbhushan-Chand I use [ShareX](https://github.com/ShareX/ShareX)

**Comment by Kulbhushan-Chand** [comment]
@AzimsTech thanks, this looks awesome.
