### ISSUE TITLE
How to type math equations in mark down? [help wanted]

### ISSUE THREAD

**Issue by tobyatgithub** [daattali/beautiful-jekyll#405]
As title... 

I searched and the only plausible answer for that I found was to use codedogs or other 3rd party websites to create math equations as images and then import back those images in mark down.

I'm wondering are there any better way, or any tutorial of doing this? Something more similar to latex markdown 

(I search through markdown resources and went through markdown classes but didn't find anything related..) 

Much appreciated!

**Comment by daattali** [comment]
I'm not sure what the best way is. This is more of a general jekyll question. I think using third party solutions, like using an image or something like that, is the way to go from what I recall, but it's a Google question!
