### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by rfitz9** [daattali/beautiful-jekyll#41]
How do I incorporate a favicon?

**Comment by daattali** [comment]
add a proper favicon file named `favicon.ico` to the root directory

**Comment by rfitz9** [comment]
I do, but it's not working

**Comment by daattali** [comment]
It is working, I can see it, try loading your site on someone else's computer or your phone.  This question is a general jekyll/github pages question and not related to this theme, if you're having trouble with general stuff like that please ask it on some specific question board where other people can provide answers. I'm extremely busy this month and don't want to spend time on these issues
