### ISSUE TITLE
Uploading .ipynb file?

### ISSUE THREAD

**Issue by bidyutchanda** [daattali/beautiful-jekyll#434]
Hi Dean, 

Is a Jupyter notebook .ipynb file considered a post? Because you said somewhere in Readme that only files containing dates in yyyy-mm-dd-<filename>.md gets considered as a post. 

So can I directly upload .ipynb files as posts or do I have to convert them into Markdown files and then upload them?

**Comment by daattali** [comment]
Jupyter notebooks will not render like you want them to. Jekyll does not support that out of the box to my knowledge. You can search (on google or any jekyll forum) for ways that people get their python notebooks to render on jekyll websites, it's not something I'm familiar with.
