### ISSUE TITLE
Implement OpenGraph support

### ISSUE THREAD

**Issue by gpotter2** [daattali/beautiful-jekyll#438]
Hi & Thanks for this amazing project !

beautiful-Jekyll is missing OpenGraph tags support, see http://ogp.me/
It means that pages in "preview" mode when for instance linked on facebook, discord... are poorly displayed.

I don't currently have the time to draft a proper implementation, so am currently hard-coding them in each page...

**Comment by daattali** [comment]
OpenGraph support is already implemented.
