### ISSUE TITLE
Add permalink to 404.html

### ISSUE THREAD

**Issue by radaniba** [daattali/beautiful-jekyll#44]
the page 404.html with the current header will not display if the website is hosted on github

I fixed this by adding a 

```
permalink: /404.html
```
I don't think this needs a PR since I added other things but I though you might want to fix that

Cheers

Rad

**Comment by daattali** [comment]
Thank you, I've just added that.  I guess this broke when Github moved from Jekyll 2 to 3, because it definitely worked for the past year.  Thanks!
