### ISSUE TITLE
bug fix Dockerfile for permission error

### ISSUE THREAD

**Issue by hepengfei** [daattali/beautiful-jekyll#443]
docker build -t beautiful-jekyll "$PWD" break with the following error:

> There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is
> likely that you need to grant write permissions for that path.

The jekyll/jekyll images had added a new user and group jekyll:jekyll, so we
must copy file with the right permissions.

```
COPY --chown=jekyll:jekyll Gemfile .
COPY --chown=jekyll:jekyll Gemfile.lock .
```

Following is my patch for this bug fix.

[0001-fix-Dockerfile-COPY-file-with-chown-for-jekyll-jekyl.patch.zip](https://github.com/daattali/beautiful-jekyll/files/2709692/0001-fix-Dockerfile-COPY-file-with-chown-for-jekyll-jekyl.patch.zip)

**Comment by daattali** [comment]
I believe this is now fixed with a recent commit. Feel free to reopen the issue if this is still happening.
