### ISSUE TITLE
Add markdown icon

### ISSUE THREAD

**Issue by mbrossar** [daattali/beautiful-jekyll#446]
Hi Dean,

Looking at your "about me" page at [https://deanattali.com/aboutme/](https://deanattali.com/aboutme/),
I am wondering how can we use the icons (e.g. the suitcase, the ball) in a markdown file, or in an HTML file ?

**Comment by daattali** [comment]
They're not markdown icons, they're font awesome icons. You can read about them and see all the possible icons you can use on fontawesome's website https://fontawesome.com/

It's the same icons that are used in the footer for the social media icons. Here's an example usage in beautifuljekyll to give you a sample of how it's used https://github.com/daattali/beautiful-jekyll/blob/364604551d151cad89b3fbc662325db2e763ffb1/_includes/social-share.html#L26
