### ISSUE TITLE
Font change for entire website

### ISSUE THREAD

**Issue by bidyutchanda** [daattali/beautiful-jekyll#447]
Hi Dean. 
Can you point me towards the file which will exactly let me change the style of the whole website? Mainly fonts and colors?

**Comment by daattali** [comment]
It should be the main.css file

**Comment by daattali** [comment]
There's special CSS rules where for when different widths of the browser. Search for "media" in the css file and you'll find them

**Comment by maique** [comment]
Thank you so much. I'll look into it.

: instagram.com/maique
: maiquemadeira.com


On Sun, Jan 27, 2019, at 05:48, Dean Attali wrote:
> There's special CSS rules where for when different widths of the
> browser. Search for "media" in the css file and you'll find them> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/daattali/beautiful-jekyll/issues/447#issuecomment-457891210
