### ISSUE TITLE
German translation in ui-text.yml

### ISSUE THREAD

**Issue by LupusE** [daattali/beautiful-jekyll#454]
You did a amazing Job with this template. I really like it as base for my own project.
So I'd have one error and one request for improvement. All regarding the German translation in ui-text.yml.

[...]
  comment_form_email_label   : "E-Mail-Ad~~d~~resse"
[...]
There i one d too much. the word is 'E-Mail-Adresse.

The 'Sie' is very formal. Meanwhile even in Germany is the 'you' well accepted. Especially online it is common to use the more casual 'Du'. But as mentioned before is is not an error, it is just my idea to improve the theme.
Here is what 'I've changed for my site:
[...]
de: &DEFAULT_DE
  comments_label             : "Hinterlasse einen Kommentar"
  comments_title             : "Kommentare"
  comment_form_info          : "Die E-Mail Adresse wird nicht veröffentlicht. Benötigte Felder sind markiert"
  comment_form_comment_label : "Kommentar"
  comment_form_md_info       : "Markdown wird unterstützt."
  comment_form_name_label    : "Name"
  comment_form_email_label   : "E-Mail-Adresse"
  comment_form_website_label : "Webseite (optional)"
  comment_btn_submit         : "Kommentar absenden"
  comment_btn_submitted      : "Versendet"
  comment_success_msg        : "Danke für den Kommentar! Er wird nach Prüfung auf der Seite angezeigt."
  comment_error_msg          : "Entschuldigung, es gab einen Fehler. Bitte fülle alle benötigten Felder aus und versuche es erneut."
de-DE:
  <<: *DEFAULT_DE
[...]

**Comment by daattali** [comment]
Thanks for the feedback! Would you mind creating a pull request to make these changes?

**Comment by LupusE** [comment]
Thanks a lot for your patience :)
