### ISSUE TITLE
Nokogiri venerability

### ISSUE THREAD

**Issue by VincentTam** [daattali/beautiful-jekyll#457]
I received email from GitHub from two weeks.

![screenshot_2019-02-07-01-57-41](https://user-images.githubusercontent.com/5748535/52384582-67f70a80-2a7e-11e9-85ed-29ffd4694130.png)

**Comment by daattali** [comment]
These alerts do come up from time to time. I myself never used the ruby version of this theme - I made it especially for github pages. So any problems like these have to be fixed by the community.
