### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by anupamjamatia** [daattali/beautiful-jekyll#462]
Hi, I was trying to build a simple website following the steps described [here](https://github.com/daattali/beautiful-jekyll#build-your-website-in-3-steps) but getting the 404 page while i enter the url.

steps I followed - 
1. Forked the repository 
2. Changes done in _config.yml file 
3. Committed 
![screenshot from 2019-02-17 20-52-34](https://user-images.githubusercontent.com/12252279/52915164-aef2c480-32f6-11e9-957c-d90ca58d3d2d.png)
Please suggest what to do.

Regards

**Comment by daattali** [comment]
Your username is "anupamjamatia", not "aj". If you follow the instructions exactly as laid out in the README, the website would work. Please only open an issue if you believe there is a bug with the software, not to ask for help. If you need personal help, you should post on a jekyll forum.

**Comment by anupamjamatia** [comment]
ok thanks.

**Comment by pjakobsen** [comment]
Ironically the code is different in the  instructions and in your source that actually can and does cause a 404.  You need to add baseurl = ""  You can see it in your instruction video (gif), but it's not present in the _config.yml file.   Once I added that I got rid of my 404 error.
