### ISSUE TITLE
Unordered list ignore margin?

### ISSUE THREAD

**Issue by AzimsTech** [daattali/beautiful-jekyll#466]
I was wondering if anyone had a similar issue. This problem only happened on mobile as you can see below:

![example](https://i.imgur.com/aUDbEBB.png)

**Comment by daattali** [comment]
This is not specific to this theme or to jekyll in general. It's likely a
general CSS question. I think stackoverflow/google would be a good place to
search for a solution

**Comment by AzimsTech** [comment]
Okay, I will look into that. Sorry for inconvenience.

**Comment by AzimsTech** [comment]
https://github.com/AzimsTech/AzimsTech.github.io/commit/ebaa4cc2e866ed87ad9ec67a84490ff2146e63e1 has fixed my issue.
