### ISSUE TITLE
Local development: install without Docker?

### ISSUE THREAD

**Issue by cryptic0** [daattali/beautiful-jekyll#470]
Author: please ignore!

This question is mainly for those who have implemented this theme locally.  Can this be done without docker?  If it's just a theme, then why not just install it as such within a site generated by jekyll?  I don't wish to deploy my site to github pages.  Thanks for any feedback.

**Comment by hugo-ma-alves** [comment]
Hello

With the Gemfile of the master branch I couldn't run it. 
But I deleted the Gemfile.lock and did a "bundle install" and now it is working. 
You can check my gemfile.lock [here](https://github.com/hugo-ma-alves/hugo-ma-alves.github.io/blob/master/Gemfile.lock)

**Comment by cryptic0** [comment]
Do you mean you replaced the original Gemfile.lock with the one you linked above?

**Comment by hugo-ma-alves** [comment]
Just delete it and run "bundle install" again.
It should get the most recent dependencies.

**Comment by cryptic0** [comment]
I have libxml2 (2.9.9_2) installed already.  When I tried your method, I got strange date time errors:

``bundle install`` was successful, but the following results in many errors.

```bash
bundle exec jekyll serve

Configuration file: /Users/cryptic0/Dropbox/Sites/beautiful-jekyll/_config.yml
            Source: /Users/cryptic0/Dropbox/Sites/beautiful-jekyll
       Destination: /Users/cryptic0/Dropbox/Sites/beautiful-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: could not read file /Users/cryptic0/Dropbox/Sites/beautiful-jekyll/vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.3.0/gems/jekyll-3.7.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```
I should mention that I have another site with a different theme that I am working on and "jekyll serve" works fine with it.

**Comment by hugo-ma-alves** [comment]
The date on your file name is invalid.

Change it to something else, like:
2019-03-26-welcome-to-jekyll.md

**Comment by cryptic0** [comment]
I am not sure those files are meant to be touched.  As they are deep inside the ``vendor/`` folder.  Google search indicates that files with empty time stamps are used as templates to name new posts with current ``date``. 

Another problem is that jekyll seems to be looking inside ``vendor/.../ruby/2.3.0/`` instead of ``...ruby/2.6.0/``.  Not quite sure what to make of this.

**Comment by hugo-ma-alves** [comment]
Sorry my bad, I haven't noticed that they were on the /vendor. 
I'm no ruby expert so I can't help you on this :(

**Comment by hugo-ma-alves** [comment]
Sorry I am sleeping today, once again I haven't read the full question 😄 

So you installed the vendor stuff inside your project folder. So all those files are being read by Jekyll.
You just need to ignore them on _config.yml. Edit the file and add vendor/ to excludes.

For example, if you run `bundle install --path ./vendor` you can change your _config.yml file to exclude the vendor/ directory:

    exclude:
      - CHANGELOG.md
      - CNAME
      - Dockerfile
      - Gemfile
      - Gemfile.lock
      - LICENSE
      - README.md
      - Vagrantfile
      - vendor/


And then it works as expected:

About ruby versions, if you are using rbenv you can install 2.6.2.
rbenv install 2.6.2
rbenv global 2.6.2

**Comment by cryptic0** [comment]
That works.  Strangely enough, I redid all steps by recloning the repo, deleting Gemfile.lock, running bundle install and this time I did not have the ``vendor/`` folder.  So I did not need to exclude it.  All is well. Thanks for your help.

**Comment by daattali** [comment]
I haven't followed this conversation, but if there's anything incorrect
with the current setup or documentation, please do let me know!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by cryptic0** [comment]
Dean, I will update your section on "local development" to include "without Docker" instructions and send you a pull request.   All credit goes to @hugo-ma-alves.
