### ISSUE TITLE
Pagination showing only the last item

### ISSUE THREAD

**Issue by nateforsyth** [daattali/beautiful-jekyll#486]
Hi Dean,

Loving your work, still trying to get it working as I expect it to.

In my _config.yml, I have the following:
`
**paginate: 10**
`

Once I hit 11 posts, all that is displayed within the pagination is a single item; the last one.

This is Ruby right? It's something I'm not familiar with, and have been bumbling my way through trying to resolve this pagination issue.

Here's the home page as it stands right now, note that there is only one item.

![broken jekyll pagination](https://user-images.githubusercontent.com/13162026/57273425-da15d480-70eb-11e9-90da-694e912fe2e5.png)

Here's the same home page when I set the pagination parameter in the config to 20, note only showing 2 but all 11 are rendered as expected.

![broken pagination 2](https://user-images.githubusercontent.com/13162026/57273627-9c657b80-70ec-11e9-915b-df7e277dc245.png)

Halp! :)

Thanks again for all the work.

Nate

**Comment by daattali** [comment]
That's strange. If you clone my project and not change anything, does the pagination work properly? If you clone my project and change the pagination parameter does it work?

**Comment by nateforsyth** [comment]
Hi Dean

Thanks for replying, it's appreciated.

I found what caused the error - I somehow ended up with a permalink in the index.html file; removal of which has reinstated pagination as it should have been.

Definitely a case of operator error. I'll close this as such, leaving it here in case anyone else is as stupid as I was :D

---
**permalink: /index.html**
layout: page
title: Dreams of .DEV
subtitle: A journey in code
use-site-title: true
---
