### ISSUE TITLE
_posts/2016*.md  doesn't work but 2015 work

### ISSUE THREAD

**Issue by hxsnow10** [daattali/beautiful-jekyll#49]
Is it a bug?

**Comment by hxsnow10** [comment]
i find it may be a  problem about time zone.Today is 4-4 beijing, i edit it 2016-04-04, it doesn't work, 2016-03-03, it works.

**Comment by daattali** [comment]
This has nothing to do with beautiful-jekyll. It may be a Jekyll thing, maybe it doesn't allow you to have posts with a date in the "future".  Try setting your timezone on the post maybe https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts  or maybe if you change the timezone inside the config.yml file it'll work
