### ISSUE TITLE
There is no margin in header suddenly

### ISSUE THREAD

**Issue by binlidaily** [daattali/beautiful-jekyll#491]
So sorry to disturb you, I cannot fix this indeed. 

There is no margin in header suddenly as you can see in following picture, I don't know why, I don't remember I had changed the html file such as head.html or header.html or nav.html, could you please tell me which css file or html file I should review.

![image](https://user-images.githubusercontent.com/5987437/57567717-190b9900-7410-11e9-8310-e26f3711673c.png)

**Comment by homebrewman** [comment]
Hi binlidaily, 
You should assign @daattali . He can not track this issue if you don't mention him.

**Comment by daattali** [comment]
@binlidaily it's not easy for me to track the changes you've made. You can look in your repository's git history for changes made to these relevant files. I noticed that all your git commit messages simply say "commit" so I suggest in the future you use more descriptive names to make it easier for you to backtrack and see what changes happened. This is essentially a troubleshooting exercise for you, you'll just need to either look at your history and find the offending line, or you can compare your files to my files and see where it differs.

**Comment by tushar-97** [comment]
@binlidaily Were you able to fix this? I am having the same issue.

**Comment by binlidaily** [comment]
Not yet, I tried to use the raw code to rebuild my site, that didn't work. I found that it's all right if I use Safari, but not Chrome.

**Comment by daattali** [comment]
I tried creating a new website from this theme right now and saw the same problem you described.  So it wasn't something in your code. It's fixed now.

In the future, if you find a problem, the best thing to do is see if the problem is with your code or mine - if it's with my code then I will fix it.
