### ISSUE TITLE
Documentation Translation Guidelines for readme file

### ISSUE THREAD

**Issue by chimimode** [daattali/beautiful-jekyll#496]
Hi,  I like this theme so much and I would like to translate the readme file into Korean, my language.
(Even now this sentence is written as a translator and may not be correct.)

Are there guidelines for translating documents? How do you share the translated document?

Thank you

**Comment by daattali** [comment]
Thanks for offering the translation! Unfortunately I don't know of any standard way to offer translations of README files on github. It's a great idea, but I've never seen it so I'm not sure how to do it in a sensible way. If you find information elsewhere about translating README files, I'd be very interested!

**Comment by daattali** [comment]
Unfortunately I don't think this is a feature that is supported by GitHub. I did a bit of research into it and it looks like some projects simply have "README.fr.md" "README.ko.md" etc. I wouldn't be opposed to you creating a "README.ko.md" file
