### ISSUE TITLE
Consider implementing greedy navigation bar

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#507]
This will take care of a very common issue people have, where having too many links in the navigation ends up taking too much space. However, it doesn't solve the issue with links being hidden by the avatar

**Comment by daattali** [comment]
https://github.com/lukejacksonn/GreedyNav

**Comment by abelcheung** [comment]
Would it be possible to limit the width of nav link parent container with `max-width` CSS property?

**Comment by daattali** [comment]
You're asking about adding this CSS in addition to greedy nav, right? Yes that's a good idea, might be a good solution for the avatar issue

**Comment by daattali** [comment]
This will not be implemented because it will make the current navbar too different
