### ISSUE TITLE
Update README for GitLab deployment

### ISSUE THREAD

**Issue by VincentTam** [daattali/beautiful-jekyll#510]
In the "[Prerequisites](https://github.com/daattali/beautiful-jekyll/blob/209c71b6752215286ce4a04495bbd1505e9ef997/README.md#prerequisites)" section of the README, it's written that a GitHub account is required.  Nonetheless, it turned out that this theme also works on GitLab, with an addition of [an appropriate GitLab CI config file](https://gitlab.com/adiea/adiea.gitlab.io/blob/f99fcffa/.gitlab-ci.yml) and the line `exclude: vendor` in `_config.yml`.  For a proof of this, you may see [my demo GitLab repo](https://framagit.org/VincentTam/tempsite) and [the associated Beautiful Jekyll + Framagit demo site](https://vincenttam.frama.io/tempsite) created for testing this theme's reCAPTCHA support in https://github.com/einsteinpy/blog.einsteinpy.org/issues/356.

Reference: https://www.chenhuijing.com/blog/hosting-static-site-gitlab-pages/

**Comment by daattali** [comment]
@VincentTam if what you said is still true for GitLab, I'd be happy to accept a small PR to the README

**Comment by iootaa** [comment]
A free and open-source instance of Gitlab allows to use Jekyll. The host is french and so the doc is : https://framablog.org/2017/03/20/les-gitlab-pages-debarquent-dans-framagit/

**Comment by daattali** [comment]
@iootaa Feel free to add a few sentences to the README on how to translate this into GitLab!

**Comment by VincentTam** [comment]
@iootaa Thx for info.  I tested that a year ago on Framagit, the free (as in freedom) GitLab instance that you've mentioned: https://framagit.org/staticman-gitlab-pages, and I would say that it works with almost any static web generator you can think of, thanks to the built-in GitLab CD/CI, which can execute any Docker image (hosted on either Docker Hub or [GitLab container registry](https://docs.gitlab.com/ee/user/packages/container_registry/)).

However, as Staticman's project maintainer no longer suggests using public (or shared) API instance in https://github.com/eduardoboucas/staticman/issues/317#issuecomment-56525006, I removed the links between the Git* bots and my API instances on Heroku.  I'm going to start a new issue about this and update this repo's README.

**Comment by VincentTam** [comment]
Closing due to removal of technical instructions about comment service integration in the README.
