### ISSUE TITLE
[Question] Support for "crippled" browsers?

### ISSUE THREAD

**Issue by abelcheung** [daattali/beautiful-jekyll#517]
This may affect any future contributors, so might be best left open or specified in FAQ. By "crippled" browser I mean those still having a non-negligible market share, yet considered not as capable by current web standard. IE &le; 11 is a good example due to its age, or Opera Mini which disables some styling features by design. Both of them [are still relatively widely used][1], when compared with some new and shiny ones.

My question is: **which browsers does this theme intend to support?** This issue would be particularly important for CSS. For example, if I submit changes using [`position: sticky` CSS property][2], it effectively means older IE users are on their own. Javascript contributions are also affected, in case some unsupported feature may need to be polyfilled. 

[1]: https://caniuse.com/usage-table
[2]: https://caniuse.com/#feat=css-sticky

**Comment by daattali** [comment]
(I made my comment on your PR asking about browser compatibility before seeing this issue!)

There isn't an official "supported" browser set, but I do prefer to try to be as conservative as possible. I try to be reasonable (nobody cares about IE6 anymore) but I prefer to avoid using new-ish features that aren't widely supported. The `position:sticky` property is a good example of something I'd prefer to avoid. IE11 is a browser that I do still want to support.

**Comment by abelcheung** [comment]
Hmm, I'll take that as, the look and feel as well as website functionality should behave the same across traditional major desktop browsers. That brings in a second question: **how about changes that improve performance/security for current generation of browsers only?**

Again using IE as example: `_includes/ext-js.html` includes a feature utilizing [Cross-Origin Resource Sharing][1] support, which can improve security when scripts or style sheets are loaded from external CDN, but that feature will never be implemented (and thus ignored) for older IE. There could be many ideas that improve UI responsiveness, network performance and so on.

Would there be any requirement that feature suggestion or PR must benefit all browsers, or it's ok as long as user experience for unsupported browsers won't be hindered?

**Comment by daattali** [comment]
It's ok as long as old browsers don't get a regression.

But I would be a bit hesitant to add a lot of performance-related code, in favour of not over complicating the codebase. This theme is used by simple static websites, not complex websites with database queries and other features that make performance a top priority. Even the feature you're referring to in `ext-js.html` I'm not sure how many people use it, but I would bet it's a very very small number of users, and moving forward I prefer to cater to more users rather than have very esoteric features. I hope that makes senes!
