### ISSUE TITLE
[Question] Custom Social Media Logos

### ISSUE THREAD

**Issue by IneffableKoD** [daattali/beautiful-jekyll#519]
I manually added Telegram to the social links. 

`icon: "fa-telegram"` does not exist, and I can't find out where to add it myself.

Thank you for your splendid work!

**Comment by daattali** [comment]
The telegram icon is a new addition to font-awesome, it does not exist in the version this theme uses. It exists in font awesome version 5.

This is related to https://github.com/daattali/beautiful-jekyll/issues/324 - if you want to upgrade to the new fontawesome on your website, you can take a look at this PR https://github.com/daattali/beautiful-jekyll/pull/400

**Comment by daattali** [comment]
font awesome 5.12 is now implemented, so you can try these new icons
