### ISSUE TITLE
Spacing in navigation bar links

### ISSUE THREAD

**Issue by angoodkind** [daattali/beautiful-jekyll#528]
The links in the navigation bar are set too far apart, where there is no buffer between the page border and the first/last link (see attached screenshot). Is there a workaround for this?
<img width="1403" alt="Screen Shot 2019-08-08 at 4 20 09 PM" src="https://user-images.githubusercontent.com/1312344/62738725-9f784c80-b9f8-11e9-995c-f04e5de8c587.png">

**Comment by daattali** [comment]
This is an issue that got introduced because of broken code. It was fixed a few months ago - you can see the fix that I wrote and do the same in your code: https://github.com/daattali/beautiful-jekyll/commit/89d1a4fd7e585cf1897bb6bc6e4b3593a63f5f43
