### ISSUE TITLE
bigimg not appearing on Older Posts page

### ISSUE THREAD

**Issue by angoodkind** [daattali/beautiful-jekyll#530]
I have added a `bigimg` to my index.html page, and it renders perfectly on the landing page. However, when I click Older Posts, it no longer appears, and looks like this:
<img width="1403" alt="Screen Shot 2019-08-09 at 6 09 40 PM" src="https://user-images.githubusercontent.com/1312344/62813751-2816eb80-bad2-11e9-8081-dce3724872d6.png">

Is there a way to fix this?

**Comment by daattali** [comment]
Did you follow the same format for images as on my demo site? This sounds like a `/img` vs `img` type of issue

**Comment by angoodkind** [comment]
Oops! That was the issue. Thanks!
