### ISSUE TITLE
StaticMan Nested Replies Support

### ISSUE THREAD

**Issue by wini3d** [daattali/beautiful-jekyll#542]
Since the new Staticman v3 now supports nested replies, it would be nice to have the nested comment format supported and added, perhaps you can choose between the old flat and nested by include?

**Comment by VincentTam** [comment]
@wini3d Support for nested comments is independent of the version of Staticman using.  For example, here's [a blog post written a year ahead of Staticman v3](https://networkhobo.com/2017/12/30/hugo-staticman-nested-replies-and-e-mail-notifications/).

I don't have the time to search into Jekyll's syntax, but you may find the "double-loop" logic in some Hugo sites, like https://yasoob.me/posts/running_staticman_on_static_hugo_blog_with_nested_comments/.

**Comment by wini3d** [comment]
Sorry this issue should have been closed earlier. Thanks for the info
