### ISSUE TITLE
How do you write mathematical formulas？

### ISSUE THREAD

**Issue by ximingxing** [daattali/beautiful-jekyll#557]
can beautiful-jekyll support mathematical formulas ?

if so, What is the syntax for writing a formula？

if not, do we have other options to support mathematical formulas jut like includes plugins?

By the way, thanks，beautiful-jekyll is an amazing project！

**Comment by daattali** [comment]
Yes please see the README https://github.com/daattali/beautiful-jekyll/blob/master/README.md#how-do-i-use-mathjax-equations-in-my-posts

**Comment by mcc-us** [comment]
This link is dead. I could **not find information on using mathjax or kramdown to display mathematical formulas**. 
Am I missing something?

**Comment by daattali** [comment]
FAQ are here https://beautifuljekyll.com/faq

In there you'll find a link to https://github.com/daattali/beautiful-jekyll/issues/195

**Comment by daattali** [comment]
You can now use `mathjax: true` YAML parameter
