### ISSUE TITLE
_config.yaml issue after migrating

### ISSUE THREAD

**Issue by wi5nia** [daattali/beautiful-jekyll#563]
Hi,

I have migrated from another theme to Beautifull Jekyll and a strange issue occured that GH pages tells me that there is an error in my config file in line 4:
title: Tomasz Wisniewski

After commenting it out an error on line 7
description: Tomasz Wisniewski blog

and so on and so forth. 

Locally everything works.

Any suggestions on the resolution?

**Comment by daattali** [comment]
What was the issue? To help others who might have similar problems

**Comment by wi5nia** [comment]
The issue was a misleading GH Pages error message because the error was WAY down the config file and it was an additional space where it shouldn't be
