### ISSUE TITLE
share-img doesn't work on Twitter and Linkedin

### ISSUE THREAD

**Issue by wi5nia** [daattali/beautiful-jekyll#565]
I have added a share-img to my post
share-img: "path"
and the image is used when sharing to facebook but not Twitter and Linkedin.

What is the issue?

**Comment by daattali** [comment]
As per the documentation: "If you want to specify an image to use when sharing the page on Facebook or Twitter, then provide the image's full URL here,"

Looking at a sample page on your website , I see this in the source code:

```
  <meta name="twitter:image" content="/assets/images/apimappins/addmasterappins.png" />
```

which means you weren't using the image's **full** URL

**Comment by wi5nia** [comment]
I've corrected the entry and still twitter and linkedin don't show the image :(

**Comment by daattali** [comment]
It takes some time to update. https://cards-dev.twitter.com/validator
