### ISSUE TITLE
ORCID icon

### ISSUE THREAD

**Issue by akiannillo** [daattali/beautiful-jekyll#568]
I'm trying to use the ORCID icon, but it doesn't show up (see bottom of https://akiannillo.github.io/).

https://github.com/akiannillo/akiannillo.github.io/blob/master/_data/SocialNetworks.yml

**Comment by daattali** [comment]
It's not in the template, this thee doesn't know about orcid. That socialnetworks yaml file contains the possible websites you can use. If you want to add orcid, you'll need to add it to the template (look at the history of when one of the others were added and follow the same steps)

**Comment by ryan-p-randall** [comment]
It looks like the ORCID icon was added to [Font Awesome just a couple months ago, in 5.11](https://github.com/FortAwesome/Font-Awesome/issues/4401#issuecomment-533557617).  

Would adding it to this theme be as easy as bumping the version this theme loads in lines 6 & 7 of `_layouts/base.html`?

Like just changing 
```
common-ext-css:
  - "//maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" 
 ```
to 
```
common-ext-css:
  - "//maxcdn.bootstrapcdn.com/font-awesome/5.11.2/css/font-awesome.min.css"
```
?

@akiannillo if bumping that doesn't automatically add the ORCID icon or breaks other things, you might instead try adding the [Academicons font](https://jpswalsh.github.io/academicons/) to your site.

**Comment by daattali** [comment]
If I remember correctly, updating to font awesome 5 does involve some extra work, you can google for the migration instructions.

**Comment by akiannillo** [comment]
Hi all,
changing simply the CSS does not work.
Even adding the academicons font, it breaks alignments and other things.
I'll look at this (https://github.com/daattali/beautiful-jekyll/pull/400/files) when I have time.
Best,

**Comment by daattali** [comment]
font awesome has been updated to 5.12.1 so you can try using orcid now
