### ISSUE TITLE
 How to change theme to suit right handed languages

### ISSUE THREAD

**Issue by MuhammadIbnAlAbbas** [daattali/beautiful-jekyll#572]
how to change theme to suit right handed languages so that it changes from being left aligned:

![Screenshot_2019-12-24 يل يبلاسب لايبل تيلاتن بل ا الحياة](https://user-images.githubusercontent.com/53350464/71384053-17759680-25d7-11ea-9d9b-ac11d48ab324.png)

to become right aligned:
![Screenshot_2019-12-24 سر بسم الله الرحمن الرحيم - موضوع](https://user-images.githubusercontent.com/53350464/71384066-22302b80-25d7-11ea-897c-6804f97c0990.png)

**Comment by daattali** [comment]
I believe you should be able to add `direction: rtl;` to the CSS of just the main section or a few main sections.

Maybe try adding something like the following to the CSS

```
div.container[role="main"] {
  direction: rtl;
}
```

**Comment by daattali** [comment]
I just tried it and adding that css rule does indeed work
