### ISSUE TITLE
Change the size of the title 

### ISSUE THREAD

**Issue by sshen82** [daattali/beautiful-jekyll#581]
Hi, thank you for building this. this template is awesome!

However, I do have a question on how to change the size of the title in the main page. I didn't find it in the yml file (Maybe I just don't know which one is.)

Thanks in advance!

**Comment by daattali** [comment]
That's not a yaml option. To change sizes (and anything else related to how things appear) you need to edit the main.css file

**Comment by sshen82** [comment]
Oh, ok, thank you for your help!
