### ISSUE TITLE
[Question] Setting the opacity of bigimg

### ISSUE THREAD

**Issue by tirthasheshpatel** [daattali/beautiful-jekyll#592]
Is there a way to set the opacity of the ``bigimg`` (like the ``overlay_filter``) or going full rgba?

**Comment by daattali** [comment]
There is no simple way to do that. The image is displayed using the `background-image` css property, and as far as I know it doesn't support opacity. There may be hacky workarounds - if you're comfortable with css and HTML then you can try googling for something like "css background image opacity" but my guess is that it wouldn't be simple.

**Comment by tirthasheshpatel** [comment]
Thanks for your response, @daattali. Will look into html and css methods for a workaround!
