### ISSUE TITLE
[Feature]-support weekday 

### ISSUE THREAD

**Issue by memoriesus** [daattali/beautiful-jekyll#599]
Hope it can support display day (week- Monday ....)time including week

**Comment by daattali** [comment]
When you open an issue, please describe in detail what the issue is. Currently the text of your issue is:

> Thank you for submitting an issue!
> 
> Please only submit bug reports or feature suggestions. Please do not submit support requests and general help questions in this forum.

**Comment by memoriesus** [comment]
@daattali  I mean add day for the blog
For instance 
>**Posted on Fri, Apr 3**

**Comment by daattali** [comment]
This isn't supported by beautiful jekyll as an option that you can easily change, but if you really want to add the weekday you can change the date format. According to [the docs](https://shopify.github.io/liquid/filters/date/) there are many ways to format a date.

**Comment by daattali** [comment]
You would need to find where in the code the "Posted on xxx" is being generated, and use [these docs](https://shopify.github.io/liquid/filters/date/) to format the date in whatever way you prefer
