### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by YoniChechik** [daattali/beautiful-jekyll#602]
Hi Dean, I LOVE your template and use it for almost a year now! It's absolutely amazing!!!

Couple of questions:
1. Why don't you use jekyll-seo-tag instead of implementing all yourself?
2. Can you maybe consider updating a couple of outdated libraries? this what's popping for me when I audit my site (www.AIisMath.com):
![image](https://user-images.githubusercontent.com/16686924/78781069-4a863f00-79a8-11ea-972a-024fb7530fc6.png)

Thanks again!

**Comment by daattali** [comment]
1. Correct me if I'm wrong, but the jekyll plugin you refer to only works if you use this theme by installing it with ruby. It doesn't work with GitHub Pages. This theme was primarily designed as a very simple and easy to use GitHub Pages theme, and the priority will always be for GitHub Pages. I wanted to make a theme that ANYONE can use. For those people such as yourself that are advanced enough to know how to use command line, you can also figure out how to use other plugins. SEO is not a priority for this theme, keeping it simple is.

2. Upgrading bootstrap will require a major overhaul of the all the UI code. It can be done but it's not a simple task. I'd be happy to accept help for this if anyone wants to take that on, but the current bootstrap is working just fine. Whatever can be upgraded (such as font awesome) does get upgraded

**Comment by daattali** [comment]
I'm closing this issue as it's not really an issue. If you want to open an issue for a specific task (ie "update library X to version Y" or "use SEO") please do!

**Comment by YoniChechik** [comment]
Actually jekyll-SEO-tag is defaulted in GH: https://pages.github.com/versions/

**Comment by daattali** [comment]
You're right, I don't know where I saw that it's not supported. It clearly is!

I'm not sure why I didn't use it initially when I built this >5 years ago - maybe it wasn't available, or maybe I just didn't know about it (which is very possible). If I would write this theme from scratch today I'd definitely use that plugin now that you told me about it. Is there any major benefit to adding it now and tinkering with all the existing code?

**Comment by YoniChechik** [comment]
It has json+ld

**Comment by daattali** [comment]
Sorry I don't understand what that means. What exactly has json+id?

**Comment by YoniChechik** [comment]
https://yoast.com/json-ld/

**Comment by daattali** [comment]
I'd be happy to accept a PR to add the seo plugin and remove the manual code, it would have to be well tested
