### ISSUE TITLE
Github spoilers doesn't work correctly.

### ISSUE THREAD

**Issue by xoac** [daattali/beautiful-jekyll#606]
First thanks for awesome jekyll blog.
I think I could fund a bug or unimplemented feature.
Code:
```
<details>
<summary> Two days later I discovered that implementation of `no_escpe_std_replace` and `to_escpe_std_replace` was not done correctly. Can you found how we can make it better? </summary>

\`\`\`
#[inline]
fn escape_with_replace2(s: &String) -> String {
    s.replace('=', r#"\="#)
        .replace(',', r#"\,"#)
        .replace(' ', r#"\ "#)
}
\`\`\`

So the difference is `char` vs `&str` for matches

And bench results:
\`\`\`
test escape::bench::no_escape_std_replace2         ... bench:         134 ns/iter (+/- 13)
test escape::bench::to_escape_std_replace2         ... bench:         401 ns/iter (+/- 34)
\`\`\`

If I would found it earlier I will not write this blog post since std version is good enough!.
</details>
```

I have added `\` to prevent nested code section marker. 

The above code rendered here:
- - - -
<details>
<summary> Two days later I discovered that implementation of `no_escpe_std_replace` and `to_escpe_std_replace` was not done correctly. Can you found how we can make it better? </summary>

```
#[inline]
fn escape_with_replace2(s: &String) -> String {
    s.replace('=', r#"\="#)
        .replace(',', r#"\,"#)
        .replace(' ', r#"\ "#)
}
```

So the difference is `char` vs `&str` for matches

And bench results:
```
test escape::bench::no_escape_std_replace2         ... bench:         134 ns/iter (+/- 13)
test escape::bench::to_escape_std_replace2         ... bench:         401 ns/iter (+/- 34)
```

If I would found it earlier I will not write this blog post since std version is good enough!.
</details>

The above code rendered on website (screenshot):
- - - - - 

Before clik:
![image](https://user-images.githubusercontent.com/1863020/79052463-065c9e00-7c37-11ea-9d01-0d7b4596dc40.png)

After click:
![image](https://user-images.githubusercontent.com/1863020/79052443-e5944880-7c36-11ea-9614-366ac36157b2.png)

## Problems:
- No visible clues that text could be a spoiler
- Context inside spoiler is  incorrectly rendered

**Comment by daattali** [comment]
Sorry, I don't understand the issue. What is github spoilers? Does whatever you're trying to do work with other jekyll themes? Is it something in github-falvoured-markdown?

**Comment by xoac** [comment]
Oo it looks like this is not officially supported. [Here](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef282870 is example that I have followed. 

But is there a way to use spoilers with this template?

**Comment by daattali** [comment]
The page you linked to doesn't exist (or maybe it's private and it doesn't exist for me).

Anyway, when I tried googling for github spoilers I don't think it's a standard thing, it looks like just something a random person came up with and named it. Unfortunately I don't have enough bandwidth to look into unofficial features and try to support them or understand them.

**Comment by xoac** [comment]
I have fixed link. 

No problem. I probably created this issue without enough research. Thanks for quick responses.

**Comment by daattali** [comment]
You can perhaps ask the person who created "github spoilers" how to use it inside a jekyll theme
