### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by GabeL7r** [daattali/beautiful-jekyll#607]
Hi Dean,

I love the theme!

I am having an issue with code blocks not being formatted properly and I was wondering if you could help me. The code blocks are being put in a <pre><code><text> HTML field rather than each line of the code getting a separate span with the correct highlighting applied. 

You can see an example here: https://clean.tf/2020-04-11-resource-names/

And the _config.yml file here https://github.com/Clean-Terraform/website/blob/master/_config.yml

I was wondering how I would go about getting syntax highlighting to work properly?

**Comment by daattali** [comment]
That sort of stuff is not handled by the theme, but by jekyll itself. There are many different ways to write markdown syntax and jekyll has support for a few different ones. The default one I chose to use is "kramdown" (you can see an entry `markdown: kramdown` in the config.yml file). You can read jeky'll documentation [here](https://jekyllrb.com/docs/configuration/markdown/) and experiment with the different types of markdown engines and the different options each one provides and the syntax for each one. I also struggle with this stuff and have to do a lot of experimentation every time I need to use special syntax and it's dependent on the markdown variant.

Closing this as it's not a theme issue.

**Comment by GabeL7r** [comment]
Thanks for the quick reply, the reason I thought/think it is a theme issue is because I created the same post in a different directory where I initialized Jekyll and made no changes and the code block rendered properly. 

I wasn't sure if bootstrap or some other setting in the theme was perhaps causing the code block to break? I also saw some custom CSS for code blocks in the theme.

**Comment by daattali** [comment]
The css is only responsible for visual rendering. You mentioned the actual HTML generated is different than what you expect, that sounds to me like a markdown enginer issue. These issues are indeed annoying to troubleshoot, you'll have to play around with the different options. Sorry I can't be of more help.
