### ISSUE TITLE
How can I enlarge the spacing between list items?

### ISSUE THREAD

**Issue by binlidaily** [daattali/beautiful-jekyll#611]
I write blogs in Chinese, the spacing between list items is not appropriate. How can I enlarge the spacing? I found many `li` tag setting in css files, I really don't know which one is the key setting? I tried to change some `li` tag, it doesn't work.

![image](https://user-images.githubusercontent.com/5987437/79536335-68dbf100-80b2-11ea-9089-11bb09f67f23.png)

Thank you very much!

**Comment by daattali** [comment]
That sounds like something you can do with CSS, maybe using `margin` on `li` tags. You have to know or learn a bit of CSS to change the look away from the defaults.
