### ISSUE TITLE
Open URL's in new tab/window

### ISSUE THREAD

**Issue by Cloudsparkle** [daattali/beautiful-jekyll#617]
Hi,

Can you implement the possibility to open URL's in a new tab, and not in the same window as it is today?

**Comment by daattali** [comment]
This isn't supported here natively as a configuration option (I don't think I've ever seen something like 
this, it seems too specific). This is possible in HTML if you want, you can google for "html open link in new tab" and edit all the links

**Comment by OCram85** [comment]
@Cloudsparkle: In markdown you can specify the the target as well. If you follow this syntax use can create links which should open in a new blank tab:

```mardkown
[Github.com](https://github.com){:target="_blank"}
```

**Comment by daattali** [comment]
Thanks @OCram85 . This suggestion would have to be done for every link, it's not a config parameter
