### ISSUE TITLE
Submenu Items Causing Github Build Error

### ISSUE THREAD

**Issue by markjamesm** [daattali/beautiful-jekyll#632]
Attempting to add a submenu to one of my navbar-links is causing Github to display the following build error:

The page build failed for the `master` branch with the following error:
You have an error on line 23 of your `_config.yml` file.

- My [_config.yml](https://github.com/markjamesm/markjamesm.github.io/blob/master/_config.yml)

Lines 22-27 of my _config.yml:

22: navbar-links:
23:  About Me: "aboutme"
24:  Projects: "projects"
25:    - CU Libraries: "https://markjames.dev/cu-libraries"
26:    - Linnstrument Helper: "https://markjames.dev/linnstrument-helper"
27:   Contact: "contact"

**Comment by daattali** [comment]
Sounds like a spacing issue. Make sure your spacing is correct.

**Comment by markjamesm** [comment]
Thanks Dean! Seems like I can do this:

navbar-links:
  About Me: "aboutme"
  Projects:
    - All Projects: "projects"
    - CU Libraries: "https://markjames.dev/cu-libraries"
    - Linnstrument Helper: "https://markjames.dev/linnstrument-helper"
  Author's home: "https://markjames.dev"

but not this:

navbar-links:
  About Me: "aboutme"
  Projects: "projects"
    - CU Libraries: "https://markjames.dev/cu-libraries"
    - Linnstrument Helper: "https://markjames.dev/linnstrument-helper"
  Author's home: "https://markjames.dev"
