### ISSUE TITLE
Where to add readtime.html?

### ISSUE THREAD

**Issue by Tanjim131** [daattali/beautiful-jekyll#639]
Where should I add include readtime.html so that it correctly renders?

Adding at the top of the post doesn't render it correctly.

---
layout: post
title: Flake it till you make it
subtitle: Excerpt from Soulshaping by Jeff Brown
cover-img: /assets/img/path.jpg
tags: [books, test]
---

{%- include readtime.html -%}

Under what circumstances should we step off a path? When is it essential that we finish what we start? If I bought a bag of peanuts and had an allergic reaction, no one would fault me if I threw it out. If I ended a relationship with a woman who hit me, no one would say that I had a commitment problem. But if I walk away from a seemingly secure route because my soul has other ideas, I am a flake?

![image](https://user-images.githubusercontent.com/32413465/82157861-c0ce6900-98a5-11ea-8cfa-8a98d56b3166.png)

**Comment by daattali** [comment]
You dont include it explicitly. It's a YAML parameter, like all the other parameters.

```
---
title: title
readtime: true
---
```
