### ISSUE TITLE
Creating archives navbar

### ISSUE THREAD

**Issue by Tanjim131** [daattali/beautiful-jekyll#640]
Is it possible to create an archives page like the following? 

![image](https://user-images.githubusercontent.com/32413465/82159672-ca5dce00-98b1-11ea-915a-8f71f9f5996d.png)

**Comment by daattali** [comment]
An "archive" is not directly supportd, but you can achieve something similar with tags if you give each post a tag of its year. Look at `link-tags: true` in the config file
