### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by rs9899** [daattali/beautiful-jekyll#641]
I'm noticing there being an issue of exit code 15 in jekyll build. Is there any issue with that Jekyll yml file in the GitHub action workflow?

**Comment by daattali** [comment]
Yes I did notice that, but I'm not sure why. I looked at the history of builds and can't tell why it started failing. If you're able to figure it out I would be happy to get some help.

The theme itself does work with no issues, it's only the github action that's broken.

**Comment by rs9899** [comment]
Exit code 15 seems like out of resources
https://www.mersenneforum.org/showthread.php?t=23370

maybe its more of a resource constraint of the public github repo maybe. Not sure though. I will look more on this too.

**Comment by daattali** [comment]
I haven't been able to figure it out. It would be very very helpful if you do -- thank you
