### ISSUE TITLE
How to highlight asymptote code?

### ISSUE THREAD

**Issue by quanhinh9** [daattali/beautiful-jekyll#643]
Hi,

I use the asymptote code with `` asy but site not showing highlight.

How to fix it?

**Comment by daattali** [comment]
I don't know what that is. This doesn't look like a beautiufl-jekyll specific issue, I think it's a question for the highlighter/kramdown engine/etc. I'm closing this issue as it's not directly about the theme

**Comment by Tanjim131** [comment]
Can you post a screenshot of the code and your output on the website?
