### ISSUE TITLE
[Proposal] Add Matrix and Mastodon social network links

### ISSUE THREAD

**Issue by Iolaum** [daattali/beautiful-jekyll#646]
Hello, I have started using your template recently ([here](https://github.com/Iolaum/Iolaum.github.io), it's still barebones). I really liked it and I am going to spend more time with it and make a small website out of it.

I was exploring the `_config.yml` options, being pleasantly surprised by the many options that were available for [social network links](https://github.com/daattali/beautiful-jekyll/blob/54ca4023738b77d3b7c64f7aded7fc404f00fec7/_config.yml#L40), and noticed that there were no Mastodon and Matrix links. Given all the other ones that are there, I am wondering if you would be open to considering including them in the template.

**Comment by daattali** [comment]
I haven't heard of these servies, so I had to look them up and they seem legitimate. Feel free to submit a PR

**Comment by daattali** [comment]
Matrix doesn't seem to have a font-awesome icon

**Comment by daattali** [comment]
@Iolaum feel free to submit a PR if you'd like to see these added, but I'm closing the issue
