### ISSUE TITLE
Changing Fonts should be easier

### ISSUE THREAD

**Issue by navendu-pottekkat** [daattali/beautiful-jekyll#647]
Please only submit feature suggestions or bug reports if you believe something is broken. Please do not submit support requests and general help questions.
Add options to change the font family of the website

**Comment by daattali** [comment]
I don't consider that a mandatory feature.  There are infiintely many things you can change about the appearance of the them by modifying the css, it would get very messy if every possible thing would get a dedicated option and instructions in the README. There are many configurable options for common things users might want to change, but for everything else you're free to modify the CSS.
