### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by angoodkind** [daattali/beautiful-jekyll#648]
This might be a dumb question, but how do update my site to the most recent version of Beautiful-jekyll?

**Comment by daattali** [comment]
It depends on how you're using the theme.

If you're using one of the "advanced" methods https://beautifuljekyll.com/getstarted/#install-steps-hard using the ruby gem, then updating is as simply as changing the line `gem "beautiful-jekyll-theme", "3.0.0"` to `gem "beautiful-jekyll-theme", "4.0.0"`

If you're using the simple method described in the README where you fork this github repository, then there isn't really an easy way to sync your project to this one. You can google for "github how to sync a fork" - there isn't a great way. What I would recommend is maybe save all your posts and config parameters and any other files you may have created yourself , re-fork this project, and add back the posts/any other files you created. Sorry there isn't a better way.

**Comment by daattali** [comment]
It seems like GitHub now has a "Sync fork" button! 

![image](https://github.com/daattali/beautiful-jekyll/assets/952340/df31307b-9a13-4f0b-b728-b2e13657f82b)
