### ISSUE TITLE
Proper way to update theme 

### ISSUE THREAD

**Issue by Hax4us** [daattali/beautiful-jekyll#650]
What is the proper way to update your theme. I was using blogger for years and now suddenly i decided to migrate so i am absolute beginner in Jekyll world and after reading docs i am able to setup my website with the help of your amazing theme ( i forked your theme and then after some changes i created a new repository and deleted forked one ) 
Mainly which folders or data should i copy blindly if you commit something. 
For example if you changed something in `_layouts` folder then can i just copy your changes ? Will it affect my site ?

**Comment by daattali** [comment]
This was asked a couple days ago, please see #648

**Comment by Hax4us** [comment]
Thank you very much :)

**Comment by daattali** [comment]
It seems like GitHub now has a "Sync fork" button! 

![image](https://github.com/daattali/beautiful-jekyll/assets/952340/df31307b-9a13-4f0b-b728-b2e13657f82b)
