### ISSUE TITLE
[Question] can i make post images rectangular 

### ISSUE THREAD

**Issue by Hax4us** [daattali/beautiful-jekyll#652]
By default Post image are in circular shape

**Comment by daattali** [comment]
Every option that is common is exposed in the config file, this (and any other style you want to change) needs to be done manually in the CSS files.

**Comment by Hax4us** [comment]
At least can you give a hint like which file exactly ? 
 I don't know much about web development

**Comment by daattali** [comment]
This theme is meant to be easy to use by anybody with no web knowledge. As such, it doesn't allow you to do EVERYTHING you want, the more flexibility you want the more knowledge you'll need. You need to create your own css file or modify an existing one. You'll need to learn some CSS and how it works if you want to do this. I cannot give you exact instructions

**Comment by Hax4us** [comment]
Ok so i changed the shape of Post image to rectangular but changes in height & width is only working in desktop but not in mobile device , can you tell me why ?

**Comment by daattali** [comment]
There are probably rules somewhere in the css file that are specific to mobile devices.

Can you show me what it looks like before and after your circle -> rectangle change

**Comment by Hax4us** [comment]
Before 

![Screenshot_2020-06-10-12-28-36-563_com termux](https://user-images.githubusercontent.com/30441647/84236953-21a03880-ab16-11ea-8be8-8a5fd63c4f33.jpg)
![Screenshot_2020-06-10-12-28-25-796_com android chrome](https://user-images.githubusercontent.com/30441647/84236962-25cc5600-ab16-11ea-8fb9-4483ae5978e5.jpg)


After 

![Screenshot_2020-06-10-12-28-54-524_com termux](https://user-images.githubusercontent.com/30441647/84236984-2cf36400-ab16-11ea-979f-89dd4c9b848e.jpg)
![Screenshot_2020-06-10-12-29-32-448_com android chrome](https://user-images.githubusercontent.com/30441647/84236994-3086eb00-ab16-11ea-8740-7cf033aba2ec.jpg)

**Comment by daattali** [comment]
Thanks. You can open a separate issue to ask for this, and if other people also request/support this feature then maybe I'll change it

**Comment by Hax4us** [comment]
Thank you
