### ISSUE TITLE
[Request] Change post images shape to rectangular 

### ISSUE THREAD

**Issue by Hax4us** [daattali/beautiful-jekyll#654]
Addressing https://github.com/daattali/beautiful-jekyll/issues/652

For example

![Screenshot_2020-06-10-12-49-04-020_com android chrome](https://user-images.githubusercontent.com/30441647/84238583-e18e8500-ab18-11ea-8dcc-6f43bda1e2b9.jpg)

Above Screenshot is from __basically-basic-jekyll-theme__

**Comment by daattali** [comment]
Can you show the current version vs your proposed?

**Comment by Hax4us** [comment]
Means current look or shape of Post image , right ?

**Comment by daattali** [comment]
The screenshot you showed is not from this theme so it's hard to compare. If you've implemented this feature for your own site, then it would be useful if you can show here your before and after, to be able to diretly compare the two versions.

**Comment by Hax4us** [comment]
Sorry for delay :)

> If you've implemented this feature for your own site, then it would be useful if you can show here your before and after

This is not my site i just took it for example 
Here is source of example site https://github.com/thatvirtualboy/thatvirtualboy.github.io

**Comment by daattali** [comment]
I'll leave this issue open, I'll look into adding an option for square vs round photos one day

**Comment by daattali** [comment]
I experimented a little bit with removing the circular borders around post images in the feed page, and it did not look great. I could not find a way to make it fit the look of the page without significant other changes. I'm going to keep the images on the feed page as circular only. If you want to change it yourself, you can remove the `border-radius` from `.post-image img` in the main.css file.

**Comment by Hax4us** [comment]
border-radius method is useless as images are not fitting correctly and whole layout is misbehaving

**Comment by daattali** [comment]
It's only meant to be a thumbnail. It cannot cater to all image aspect ratios. I don't understand what you mean by "layout is misbehaving" - the layout seems fine, if not then please show a screenshot of what's wrong.
