### ISSUE TITLE
Consider using CSS variables/properties instead of plain CSS (or potentially SCSS)

### ISSUE THREAD

**Issue by daattali** [daattali/beautiful-jekyll#661]

**Comment by lexicalunit** [comment]
This would be quite nice.

**Comment by daattali** [comment]
Instead of going to scss, which would be a huge structural change, perhaps a happy middle ground is introducing some css variables. Unfortunately IE11 doesn't support them, so this will have to wait until IE11 dies...

**Comment by daattali** [comment]
We're at a time now where IE usage is low enough that it's probably safe to start using CSS variables. If anybody wants to take this one, I'd be happy to work with you
