### ISSUE TITLE
how to inlcude academicons

### ISSUE THREAD

**Issue by roman-tremmel** [daattali/beautiful-jekyll#664]
since most useres have a scientific background it could be helful to include academic icons like https://jpswalsh.github.io/academicons/ including google-scholar, orcid and others. 

I will try it to include by myself, but this needs a couple of hours or even days :)

**Comment by daattali** [comment]
Thanks for the suggestion. 

I would prefer not to add this library to the theme. I prefer not to add too much dependency on many external libraries. There are many very very useful third party tools but I want to keep beautiful-jekyll minimal and simple. Every additional external dependency brings with it more room for issues, more support requests, more maintenance, slightly slower performance, and and adds another (small) complexity is using the theme. I try very very hard to fight feature creep and not only the absolute necessities.

If you want to add it yourself to your own theme, you can try to follow a similar approach to how font-awesome is being included.

**Comment by camilogarciabotero** [comment]
Hi @daattali,

I was trying to follow your suggestions on adding the library, but I can't find the exact place on where to add it... Is it in `_includes/footer.html`? If it is, can you provide an example on how to do it (I've no proficiency on html code 😕). I've seen the suggestions on their web [page ](https://jpswalsh.github.io/academicons/) and they suggest adding the following lines on the html index file:

`<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">`

and then

`<a class="ai ai-google-scholar"></a>`

I guess the following steps (for anyone doing it for its own page) would be to:

2. Define the custom icon link on `_data/SocialNetworks.yml`
3. Call it in the `_config.yml`

Thanks in advance,
Camilo.

**Comment by daattali** [comment]
I'm sorry I really don't have the bandwidth for such support requests. I maintain a few dozen open source projects and cannot solve individual issues.

**Comment by daattali** [comment]
ORCID and google scholar are now supported using fontawesome
