### ISSUE TITLE
Feature Request: Adding a Table of Contents

### ISSUE THREAD

**Issue by tirthasheshpatel** [daattali/beautiful-jekyll#665]
Is it possible to redesign the `posts` page to include a table of contents fixed on the side of the post? It will be very helpful to navigate from in between a post.

**Comment by daattali** [comment]
That's not possible. If you install jekyll locally using one of the advanced methods, you might be able to find some "table of contents plugin" that somebody wrote and use it. But beuatiful jekyll doesn't support it.
