### ISSUE TITLE
jQuery-3.4.1 missing in console after enabling staticman

### ISSUE THREAD

**Issue by nxli** [daattali/beautiful-jekyll#678]
Can be reproduced by enabling staticman and then inspect the post page. The error is gone after adding jQuery-3.4.1 in `/assets/js/`

**Comment by daattali** [comment]
Which version of beautiful jekyll are you using? I fixed this yesterday https://github.com/daattali/beautiful-jekyll/commit/f23fe9c4181fe5d61b35059e40e75fd2ba02df72

**Comment by nxli** [comment]
I just noticed this error today and am not sure if it exists yesterday.

**Comment by daattali** [comment]
Fixed with #680
