### ISSUE TITLE
Staticman error message even before submitting.

### ISSUE THREAD

**Issue by nxli** [daattali/beautiful-jekyll#679]
Can be reproduced by enabling staticman and then go to any post page. The following messages appear at the same time. The `submit comment` and `submitted` button appears at the same time as well.

> Thanks for your comment! It will show on the site once it has been approved. 
> Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again.

**Comment by daattali** [comment]
Is this related to the jquery issue?

I myself don't use and never used staticman so I'm not the best at debugging it

**Comment by nxli** [comment]
I don't think it is a jquery issue since the two messages & buttons appear at the same time even without the jquery file.

**Comment by daattali** [comment]
It looks like a CSS problem. After looking into it for some time, I believe the problem is that the staticman javascript/css is using bootstrap 3 while the theme migrated to bootstrap 4

**Comment by daattali** [comment]
Have you used staticman in beautifuljekyll previously?

**Comment by nxli** [comment]
Makes sense, it is showing when it should have been hidden. No, I haven't used staticman in beautifuljekyll before.

**Comment by daattali** [comment]
I know when the UI issue happened, when I upgraded to bootstrap 4 (staticman uses classes such as `hidden` which were used in bootstrap 3 but removed in bootstrap 4)

Regardless of the UI, I'm trying to see why the comment submission behaviour itself is broken too. I'm trying to use staticman in an older version of beautifuljekyll https://github.com/daattalitest/test1 but I can't get it to work

**Comment by nxli** [comment]
A `.hidden {display: none;}` in `staticman.css` can also solve the issue. Your way is far more better though.

**Comment by daattali** [comment]
I prefered to change everything to match bootstrap 4. There were a few other changes that had to be made.
