### ISSUE TITLE
[Question] can i use adsense 

### ISSUE THREAD

**Issue by Hax4us** [daattali/beautiful-jekyll#682]
Can i use adsense in this theme ? I have no idea but a simple hint can help.
Is procedure same as blogger ? i will have to include add code in each post ?

**Comment by daattali** [comment]
I also have no idea. Never used adsense, I don't know what's involved. You should look at the documentation for adsense, although before even doing that I would first google for "jekyll adsense" or "github pages adsense" and see if there are blog posts about how to do it to know if it's feasiable or not. But it's certainly not going to be supported out of the box so I'm closing.
