### ISSUE TITLE
Deploying error to my own server.

### ISSUE THREAD

**Issue by ppkris** [daattali/beautiful-jekyll#687]
Thank you Dean for this beautiful theme. I really like it.

Yet, I encountered one problem when deploying the _site to my server after building.
1. it seems not rendering well.
2. the permalink I set for "about", "blog" or "projects" does not work.
http://www.diagnosticforest.com:200/

Both of the problems do not exist when I deploy them on Github.
https://ppkris.github.io/df-beautiful-jekyll/
GitHub repo: https://github.com/ppkris/df-beautiful-jekyll

I spent 2 whole days googling and trying to figure it out, but this place is my last resort.
Anyone encounter the same problem? I really like the theme so I don't want to quit.
Thank you so much.

**Comment by daattali** [comment]
I'm sorry it's going to be very very difficult for me to help you debug a custom server set up, there's just too many variables at play there. If I had a lot of time on my hands I would ask you to send me credentials to your server to troubleshoot, but I'm working on about a dozen open source projects at the moment (plus my actual work) so I really don't have time to dedicate so much time for free help unfortunately. If I were you I'd try to start again and take small steps and see when exactly it stops working.

**Comment by ppkris** [comment]
Thank you for the advice!
