### ISSUE TITLE
Collapsible section in markdown doesn't work

### ISSUE THREAD

**Issue by kunalspathak** [daattali/beautiful-jekyll#689]
I am trying to add a collapsible section in the markdown, but looks like it doesn't render correctly. I am expecting to render it the way it renders below.

<details>
<summary>Short summary</summary>

```
SOME DETAILS
```
</details>

**Comment by daattali** [comment]
Is this a problem speicfic to beautifuljekyll? It doesn't sound like it is. Do you know that this works in other jekyll websites with the kramdown engine? You can change the markdown engine in `_config.yml` to try other non-karmdown engines.

**Comment by kunalspathak** [comment]
Thanks for the quick response. I will try it out.

**Comment by daattali** [comment]
I'm closing this issue, but if you truly believe that this is specific to my theme only then feel free to re-open
