### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by logicatcore** [daattali/beautiful-jekyll#704]
After a bit of trial and error and giving up on loading a JSON file to draw a network graph in my [post](https://logicatcore.github.io/2020-08-15-Finding-shortest-route-using-Dijkstra-algorithm/), I just instantiated a variable and copied the json contents into the html post file. 

The problem, that I am facing now is, the graph shows up and works as expected for first few minutes after the build or when i change the branch that is being published. After 2-4 minutes the graph does not show up at all.
 
![Bildschirmfoto von 2020-08-15 16-18-40](https://user-images.githubusercontent.com/24767234/90314382-a727d680-df13-11ea-9096-2700b993a54d.png)

![Bildschirmfoto von 2020-08-15 16-18-06](https://user-images.githubusercontent.com/24767234/90314380-a68f4000-df13-11ea-8577-5e1b5f8f0d17.png)

Can anyone help me with understanding what is happening here and how to go about correcting?

TIA

**Comment by daattali** [comment]
I just took a quick look at your page and it seems like one issue is that you're trying to include javascript files that don't exist (for example, `../assets/js/sigma.js-1.2.1/build/sigma.min.js` does not exist in your repo, and `../plugins/sigma.parsers.json/sigma.parsers.json.js` is an incorrect path as well).

I will not be able to provide any further unpaid support, please use online discussion forums for more help if you need. The gitub issues section is only for bugs or feature requests, not for individual help.
