### ISSUE TITLE
Deploying site

### ISSUE THREAD

**Issue by csgillespie** [daattali/beautiful-jekyll#710]
From the README

> Click on __*Settings*__ at the top (the cog icon) and on that page you'll have an option to rename the project (*repository name*). This will create a website with the **Beautiful Jekyll** template that will be available at `https://<yourusername>.github.io` within a couple minutes.

This __didn't__ work - I waited around 10 minutes. However, when I changed and pushed a file, the website was up in around 10 seconds. Perhaps adding a note in the README.

**Comment by daattali** [comment]
Thanks for the notice @csgillespie (also, curious what you're using this for!)

It definitely used to work just like that. I'll try it with a test account

**Comment by daattali** [comment]
Seems to have worked for https://github.com/daattalitest/daattalitest.github.io

I'll still add a note though to account for github potential glitchiness. Thanks!

**Comment by csgillespie** [comment]
I was setting up a website for my daughter ;)

So a complete set of steps:

1. Create a brand new Github account
2. Create a `x.github.io` account and publish a simple index.html file. This worked.
3. Clone __your__ repo 
4. Delete `x.github.io` and rename the cloned beautiful Jekyll to `x.github.io`
4. Wait 10 minutes, I didn't get an error, just a `404` (I think)
5. Comment out a single line on the config.yml
6. Website now works.

I suppose it could be the change from index.html to jekyll?

**Comment by daattali** [comment]
Sounds like a the github build glitch, renaming the repo should have triggered a re-build. I'll add a note after I finish my current work (I'm adding a lot of features this weekend related to SEO/social media sharing, if your daughter cares about that stuff!)

**Comment by daattali** [comment]
FYI I was able to replicate by doing what you did - deleting the repo, and quickly forking and renaming.

It's definitely a github bug though. On the [builds page](https://github.com/daattalitest/daattalitest.github.io/runs/1019288986) it tells me that the page was built and is available at `https://daattalitest.github.io` but that page is a 404. After forcing a re-build, it's fine
