### ISSUE TITLE
bump kramdown dependancy

### ISSUE THREAD

**Issue by VincentTam** [daattali/beautiful-jekyll#713]
Thx for great theme.  I don't know Ruby (gems), and I don't have Ruby gems installed in the local repo for my fork of your theme.  I tried clicking the green button to generate a PR, but dependabot didn't show the generated PR for this particular kramdown gem.
I would appreciate an update for the Ruby gem dependancy.
![Screenshot from 2020-08-28 12-01-04](https://user-images.githubusercontent.com/5748535/91548777-37a7e300-e926-11ea-8111-12240d8c75c8.png)

**Comment by daattali** [comment]
I'm a noob when it comes to ruby/gems as well, my only experience is through writing the readme for this repo. So this doesn't make a lot of sense to me either. After a long time battling with the gemfile, I think that perhaps adding `spec.add_runtime_dependency "kramdown", "~> 2.3.0"` is all it takes to fix this, but I'm not sure. I also don't know if that will break anything else. I'd rather leave this for someone who actually has experience with ruby/gems

**Comment by VincentTam** [comment]
Thx for update.  I merged the above commit at VincentTam/beautiful-jekyll@8fbdaa2, but I'm still seeing this warning.
![kramdown security warning](https://user-images.githubusercontent.com/5748535/92081436-55ac9200-edc3-11ea-8320-8072a6eb8d2a.png)
With a bit of patience, I've finally received VincentTam/beautiful-jekyll#34 from @dependabot.

**Comment by daattali** [comment]
So it is or is not fixed?

**Comment by daattali** [comment]
BTW notice that Gemfile.lock is no longer included in beautifuljekyll. I read up on the subject, and when building a gem that file should not be included

**Comment by VincentTam** [comment]
> So it is or is not fixed?

After merging the automatically generated PR, the issue is gone.  I simply let the bot does it job.

**Comment by daattali** [comment]
So what I did didn't help?

---
Dean Attali
President & CEO
AttaliTech Ltd
https://AttaliTech.com <https://attalitech.com>

**Comment by VincentTam** [comment]
Sorry I can't tell.  I'm using Jekyll & Hugo, but I know neither Ruby nor Golang.  Actually the bot changed only `Gemfile.lock`, which was deleted at 114170b.  I did tried to merge the recent updates yesterday, but I was misled by the bot's automatically generated PR's.  If the problem illustrated in the screenshot doesn't happen on your GitHub repo for your GH Pages, then the Gem deps should be well-maintained.  I'm using "your" repo since I've messed up mine with a cherry-pick.

**Comment by VincentTam** [comment]
I tried placing it inside my `_config.yml`, and I configured GH Actions a year ago, but I dunno why the GH Page build have failed.
I use this theme just like I'm using a bunch of others so as to showcase how Staticman can be integrated into blog themes.  My choice of blog theme is random, a few of them are well-known, and the rest are less popular.
P.S. I'm using Staticman, but I dunno node.js.
