### ISSUE TITLE
Change width at which the top navbar becomes a burger

### ISSUE THREAD

**Issue by yeroc-sebrof** [daattali/beautiful-jekyll#719]
At a width of 768 the right options from the top bar becomes a menu burger, I would argue this is too late as a resized half browser window on a 1080p screen shows the following:

![image](https://user-images.githubusercontent.com/24794972/93282903-52ec6c80-f7c7-11ea-8a68-093cf8ea8109.png)

This collision between the icon and the text does not occur beyond 1260px wide. Hopefully an easy fix to switch between navigation bars sooner 🙂

**Comment by daattali** [comment]
You're right, the next breakpoint (which is at 992px) makes more sense.  The problem you're seeing will still happen for a small range of widths, but it's still a width that makes more sense
