### ISSUE TITLE
One question abou the yaml header

### ISSUE THREAD

**Issue by LinyiGuo96** [daattali/beautiful-jekyll#721]
Hi @daattali,

I forked your wonderful project **beautiful-jekyll** to build my personal website months ago but didn't finish it at that time.

Now I want to add an image backgroud behind the title in the `index.html`, but haven't figure it out. My yaml is as following:

```
layout: page
title: 'Hi, I am Lincoln!'
css: "/css/index.css"
subtitle: Data Science, Machine Learning & AI
use-site-title: true
cover-img: "/img/face.jpg"
```

BTW, the index.css file is copied from your homepage repository. How can I fix it?

Much appreciate:)

**Comment by daattali** [comment]
Hi @LinyiGuo96 , thanks for using beautiful jekyll! The issues here are only for reporting bugs with the theme, not for general support questions. If you'd like support, please consider any of the plans https://beautifuljekyll.com/plans/
