### ISSUE TITLE
staticman comment submission fails

### ISSUE THREAD

**Issue by danforth-restorative** [daattali/beautiful-jekyll#731]
First, thanks for this awesome website template! It really is beautiful!

I have my own instance of staticman, and my own custom form on the same page, so I know it's working right.

However, when I send a submission through the forms built into beautiful-jekyll, I get 405 nginx. Since it's hosted on my server, I can look at the logs, but that's not too illuminating:

```
66.122.76.82 - - [18/Oct/2020:08:01:12 -0400] "POST /2020-10-18-digital-transformation-for-the-rest-of-us/ HTTP/2.0" 405 166 "https://digitalskills.info/2020-10-18-digital-transformation-for-the-rest-of-us/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"
```

I was using v2 endpoint, but tried v3 like in your config, to make sure that wasn't the problem.

I may try and debug comments form, but I'm not advanced in html and it's a little dizzying compared to my simple 4 line version.

**Comment by daattali** [comment]
I have no experience with trying to host a staticman instance, I'm afraid I can't help much with this. I'm not sure if staticman itself has some sort of forum where you can ask for help? Perhaps @VincentTam has any wisdom hereon this

**Comment by danforth-restorative** [comment]
so I drilled down a bit deeper, and decided to hardcode my action url into the form.

`<form id="new_comment" class="page__comments-form js-form form" method="post" action="https://identosphere.net/staticman/v2/entry/danforth-restorative/digitalskills.info/master/comments">`

now the form is communicating with staticman.. so I figure something's up with the javascript, because before the error was from nginx, meaning the submission didn't post to the url where staticman is listening.

As I said, I have another working form on the same page with the same staticman instance, so I know staticman *is* working.

Debugging some other issues right now, but at least I'm headed in the right direction,

**Comment by daattali** [comment]
So can this issue be closed? What endpoint appears in the form when you don't hardcore it? (You can use the chrome/firefox developer toolbar to look at the HTML on the page and see what the `action` attribute of the form contains)

**Comment by danforth-restorative** [comment]
`<form id="new_comment" class="page__comments-form js-form form" method="post">`

I guess it's supposed to call upon staticman js, which I've seen in the built site has proper values encoded into it.. but I don't know how that's supposed to connect with the form.

**Comment by daattali** [comment]
I don't know anything about staticman, I never used it myself...... but looking at the javascript file, I do see these lines:

https://github.com/daattali/beautiful-jekyll/blob/8e98675644c7dae56e4d50047868c64021dcccd2/assets/js/staticman.js#L18-L29

Notice specifically the line `url: endpoint + repository + '/' + branch + '/comments',`. My guess would be that this is where it's deciding on the URL to hit, and those endpoint/repository/branch parameters come from the config file probably. I do see parameters for those 3 fields in the config file, and it does say in the comments that these parameters need to be set..... did you set those parameters?

**Comment by danforth-restorative** [comment]
I did set parameters and also saw those those lines in the built version of staticman.js

```
staticman:
  repository : danforth-restorative/digitalskills.info
  branch     : master 
  endpoint   : https://digitalskills.info/staticman/v3/entry/github/
```

```
    var endpoint = 'https://digitalskills.info/staticman/v3/entry/github/';
    var repository = 'danforth-restorative/digitalskills.info';
    var branch = 'master';

    $.ajax({
      type: $(this).attr('method'),
      url: endpoint + repository + '/' + branch + '/comments',
      data: $(this).serialize(),
      contentType: 'application/x-www-form-urlencoded',
      success: function (data) {
        $('#comment-form-submit').addClass('d-none');
        $('#comment-form-submitted').removeClass('d-none');
        $('.page__comments-form .js-notice').removeClass('alert-danger');
        $('.page__comments-form .js-notice').addClass('alert-success');
        showAlert('success');
      },
```

I may try and debug this more later, and will leave the issue open, since the comments aren't working without hardcoding the endpoint html side.

**Comment by daattali** [comment]
So I see a couple of differences.

https://digitalskills.info/staticman/v3/entry/github/danforth-restorative/digitalskills.info/master/comments

vs

https://digitalskills.info/staticman/v2/entry/danforth-restorative/digitalskills.info/master/comments


It looks like your entrypoint uses v3 instad of v2, and has the word "github" in it. Your hardcoded string does not.

**Comment by VincentTam** [comment]
@danforth-restorative If you git blame the JS code for Staticman and trace back the related PR and issues, you'd see that I have moved and decomposed the form action url to the JS file so as avoid to sp\@m bots (c.f. https://github.com/daattali/beautiful-jekyll/issues/518#issuecomment-515554335).

For testing, it helps it you include screenshots (and even better if application, server's JSON response) of the Network tab of your browser's dev tool.  That allows viewing the actual request URL & body sent.

**Comment by danforth-restorative** [comment]
ok, thanks @VincentTam that's good to know about `git blame`. 
I can't do it immediately, but will come back with more detail.

**Comment by VincentTam** [comment]
> ok, thanks @VincentTam that's good to know about `git blame`.
> I can't do it immediately, but will come back with more detail.

Lemme do this for you this time.

![image](https://user-images.githubusercontent.com/5748535/96847956-165e0180-1454-11eb-8194-3141ed5d7bcb.png)
I encourage using Google ReCAPTCHA v2 as a means to stop b0τs.  I've wrote in `staticman.yml` and `_config.yml` (or somewhere else) that the user's personal ReCAPTCHA key has to used.

![Screenshot from 2020-10-22 10-45-07](https://user-images.githubusercontent.com/5748535/96848364-a00dcf00-1454-11eb-8b1c-893e225c0a14.png)
What I intended is your Staticman instance v3 endpoint's response to a POST request generated by the `ajax` method in (my adaptations to Micheal Rose's, the author of the theme Minimal Mistakes,) `staticman.js`.  To observe how this theme's Staticman v3 support works for your site, you may rollback your hardcoded stuff and test again.  I'm not sure whether the reCAPTCHA error above caused a submission error with your Staticman v3 endpoint.

**Comment by danforth-restorative** [comment]
ok... I reverted the form and had a few confounding errors like `405 method not allowed` not sure how I fixed that, since I forgot to pull changes to my server while testing (probably similar problem I was having the first time)

then I got `$.ajax is not a function` which I [solved by changing all instances](https://stackoverflow.com/questions/44212202/my-javascript-is-returning-this-error-ajax-is-not-a-function/44212249) of `jquery-3.5.1.slim.min` to `jquery-3.5.1.min`

Thanks for all the help!

**Comment by VincentTam** [comment]
> I have no experience with trying to host a staticman instance, I'm afraid I can't help much with this. I'm not sure if staticman itself has some sort of forum where you can ask for help? Perhaps @VincentTam has any wisdom hereon this

@daattali At the 2nd reading of the issue, I finally notice the words "host staticman instance".  In the [official repo for the Node.JS app Staticman](//github.com/eduardoboucas/staticman), you'd find more help on backend stuff like hosting a Staticman instance from other fellow users by just asking a question in the issues.  A theme's Staticman support do front end stuff.

I'm glad to see this question, as I can help you save time by spotting out some error(s).
