### ISSUE TITLE
How can i add a index or directory of my articles?

### ISSUE THREAD

**Issue by hannlp** [daattali/beautiful-jekyll#735]
at title

**Comment by daattali** [comment]
Hi @hannlp thanks for your question. The GitHub Issues section is meant to be used only for bugs or feature requests. If you'd like to receive some support or have questions, please look at the different plans for support https://beautifuljekyll.com/plans/

**Comment by hannlp** [comment]
I have solve it by myself, thank you a lot^ ^.
