### ISSUE TITLE
Image for Twitter card isn't generated if cover-img has a caption

### ISSUE THREAD

**Issue by manelrodero** [daattali/beautiful-jekyll#740]
Using beautiful-jekyll 5.0.0

Post with simple a simple **cover-img** like this:
`cover-img: "/assets/img/image.jpg"`

Renders correctly in HTML as:
`<meta name="twitter:image" content="https://www.blog.com/assets/img/image.jpg">`

But if we use a caption like this:
`cover-img: {"/assets/img/image.jpg" : "Caption"}`

then **twitter:image** is missing from the HTML code.

If we use **share-img** there isn't any problem and **twitter:image** is generated (it doesn't matter if cover-img has or not the caption).

So, probably, code for **img** detection is broken somewhere.

Edit: In fact, if we don't add Caption, then image.jpg is used as a thumbnail in the list of blog posts. When adding a Caption the list of blog posts don't have any image to the right of the post title.

**Comment by daattali** [comment]
That syntax is slightly wrong. It's an array, not a dictoinary, so it should be `["/img/path" : "caption"]` instead of `{}`

I'm honestly surprised that the caption is even working with this syntax :)

**Comment by manelrodero** [comment]
Thanks. I'll try it with [ insted of { tomorrow and let you know.

I've only following instructions for cover-img in your README.md ;-)

`Include a large full-width image at the top of the page. You can either provide the path to a single image (eg. "/path/to/img") , or a list of images to cycle through (eg. ["/path/img1", "/path/img2"]). If you want to add a caption to an image, then the image should be provided as {"/path/to/img" : "Caption of image"}.`

**Comment by daattali** [comment]
Wow, that's definitely wrong! I'll fix that, thanks for pointing that out.

**Comment by daattali** [comment]
> If you want to add a caption to an image, then you must use the list notation (use `[]` even if you have only one image), and each image should be provided as `"/path/to/img" : "Caption of image"`.

Please close this issue if you think the new wording is good

**Comment by manelrodero** [comment]
Hi,

Tested cover-img: ["/path/to/image" : "caption"] and it works well. Page has the cover and the caption is on bottom right of ti.

Generated code is (when developing locally):
<meta name="twitter:image" content="http://localhost:4000/path/to/image">

So, I'll close this issue.

BTW, if you try to add a caption to share-img using the same syntax you end having wrong source code ;-)
<meta name="twitter:image" content="http://localhost:4000/%7B%22/path/to/image%22=%3E%22Caption%22%7D">

**Comment by daattali** [comment]
Share-img should only be an image path, a caption doesn't make sense for it.
