### ISSUE TITLE
How to generate rss-feed with more than 10 items?

### ISSUE THREAD

**Issue by toleeck** [daattali/beautiful-jekyll#741]
I would like to receive a RSS-feed, in which, 30 posts are published.

As I understand it, the following construction in `_config.yml` should have saved me:
```xml
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

feed:
  posts_limit: 30 
```

But I didn't get the expected result.
How to increase the number of entries in the RSS-feed, for those, if I am far from coding?

**Comment by toleeck** [comment]
The number of posts in the rss-feed can be edited directly in the xml-file:
```
{% for post in site.posts limit:30 %}
```

**Comment by daattali** [comment]
Thanks for posting your own solution!
