### ISSUE TITLE
google scholar link broken?

### ISSUE THREAD

**Issue by ht-timchen** [daattali/beautiful-jekyll#742]
Adding google scholar link to the social-network-links: in _config.yml file seems to break the build. 

I have tried multiple format, e.g. https://scholar.google.com.au/citations?hl=en&user=UgJAkMgAAAAJ, or just UgJAkMgAAAAJ, but both break the build.

**Comment by daattali** [comment]
I can't reproduce using the latest version. Unfortunately I can't debug your version. I suggest trying to update to the new version when you can (you'll also get many new features).

To debug one more time, perhaps try placing "google-scholar: UgJAkMgAAAAJ" as the first line in the list (above email) to see if that line specifically is broken or something about the list format. But unfortunately I can't debug this individual issue.

**Comment by ht-timchen** [comment]
moving the google-scholar to the first line in the list actually works!

**Comment by daattali** [comment]
So that means that there's an error with your syntax
