### ISSUE TITLE
Quotes in a post title cut the title in the social preview

### ISSUE THREAD

**Issue by f-squirrel** [daattali/beautiful-jekyll#744]
I've noticed that if a post has quotes in its title then when the post is shared on Facebook or Twitter, only the part before the quotes is shown.
Example:
```
title: The "moving" truth behind std::optional
```
=> The preview shows everything before the quote:
```
The
<excerpt>
<share-img>
```
When I remove the quotes:
```
title: The moving truth behind std::optional
```
=> The preview shows the full title:
```
The moving truth behind std::optional
<excerpt>
<share-img>
```
I've tried to put `\"` but it did not help.
 
I am not sure if it is a bug or misconfiguration, I'd be happy if anybody has any leads to offer.

P.S. I am really grateful for this awesome theme and the whole work that Dean and the contributors are doing!

**Comment by daattali** [comment]
This seems like an escaping issue, I'm probably not escaping the title somewhere where it should be escaped. I'd be happy for a PR!

**Comment by f-squirrel** [comment]
@daattali , I've created a PR(https://github.com/daattali/beautiful-jekyll/pull/745).
I am pretty new to HTML/Ruby, but it worked for me.
