### ISSUE TITLE
Spacing between image and text is not consistent. 

### ISSUE THREAD

**Issue by adityakamath** [daattali/beautiful-jekyll#748]
Hi, I have two pages - projects.md, and aboutme.md. I've basically used the same piece of code to add 2 circular png images (of the same size) in both the pages. However, in aboutme.md, I see a space between the image and the following text. In projects.md, this space doesnt exist. What am I doing wrong??

This is the code I used:

```
<figure class="aligncenter">
	<img align="left" width="200" height="200" src="https://adityakamath.github.com/assets/img/image.png" />
</figure>
```

https://github.com/adityakamath/adityakamath.github.io/blob/master/projects.md --> https://adityakamath.github.io/projects/

https://github.com/adityakamath/adityakamath.github.io/blob/master/aboutme.md --> https://adityakamath.github.io/aboutme/

**Comment by daattali** [comment]
Hi @adityakamath , this doesn't look like an issue with the theme itself, but rather a problem with your code. I think a problem like this will happen with any theme. If you want to get personalized help then please have a look at the support plans! https://beautifuljekyll.com/plans/

**Comment by adityakamath** [comment]
@daattali good to know that it's not an issue with the theme. I'll check my code, thanks!
