### ISSUE TITLE
Site avatar image is too low on Safari

### ISSUE THREAD

**Issue by lexicalunit** [daattali/beautiful-jekyll#749]
I didn't dig into what's going on here, but it seems to work fine on Firefox and Chrome.

**large screen**
<img width="914" alt="Screen Shot 2020-12-03 at 10 42 31 PM" src="https://user-images.githubusercontent.com/1903876/101130833-0f7cef80-35b9-11eb-8e06-df7e1f887f43.png">

**small screen**
<img width="815" alt="Screen Shot 2020-12-03 at 10 42 44 PM" src="https://user-images.githubusercontent.com/1903876/101130829-0e4bc280-35b9-11eb-975d-726c220dd4c8.png">

**Comment by daattali** [comment]
Thanks for the report. I don't have any macs or iphones around me, I'll try to look into it when I'm with someone who has an Apple device

**Comment by daattali** [comment]
To confirm: this happens for all beautifuljekyll websites, not just the demo one, right?

**Comment by lexicalunit** [comment]
It's happening for my site and I checked https://beautifuljekyll.com/ just to see if it was happening there too just to confirm. I didn't check more sites than that though.

**Comment by daattali** [comment]
That sounds like it's probably true for all of them :)
