### ISSUE TITLE
Change the order of social icons on footer?

### ISSUE THREAD

**Issue by CarlosGrohmann** [daattali/beautiful-jekyll#757]
Is there an easy way to change the order of the social icons of the footer? I did it by manually re-ordering stuff in `_includes/social-networks-links.html` but I was wondering if there was a better way...

**Comment by daattali** [comment]
No there isn't, the order is hard coded and the only way to change it is by modifying the file you did

**Comment by daattali** [comment]
@CarlosGrohmann this is 2.5 years later, but now you can change the order of the social icons by changing their order in the config file

**Comment by CarlosGrohmann** [comment]
Brilliant!
