### ISSUE TITLE
Feature suggestion: Menu width based on the width of the longest word

### ISSUE THREAD

**Issue by manelrodero** [daattali/beautiful-jekyll#765]
Hi Dean,

After asking on Twitter about this, I'm creating this "issue" with a feature suggestion.

Menu width should be based on the width of the longest word in menu items.

If not, words are "truncated" to the next line. For example, a menu called "ABOUT" with 3 items ("ME", "LAPTOP", "SOFTWARE") is rendered like this:

![image](https://user-images.githubusercontent.com/26098260/104852334-c7145980-58fa-11eb-8600-2896bcd7c560.png)

**Comment by daattali** [comment]
I agree the length of the dropdown should be better. 

Looking at the Bootstrap documentation, it seems that the length should automatically get adjusted to fit https://getbootstrap.com/docs/4.0/components/navbar/ - in the examples they have, they aren't doing anything special to set the width.

The code I use is very similar https://github.com/daattali/beautiful-jekyll/blob/master/_includes/nav.html so I'm not sure why it's not adjusting the width like in the bootstrap documentation. 

If anyone wants to take a look and fix it, I would be happy to accept a pull request

**Comment by manelrodero** [comment]
I'm not a web developer, so I don't know too much about Bootstrap.

In my error sample, I can have the text "SOFTWARE" without the wrap undefining word-break using F12 Developer Tools in 'beautifuljekyll.css' (line 255): https://github.com/daattali/beautiful-jekyll/blob/master/assets/css/beautifuljekyll.css.

.navbar-custom .nav-item.dropdown .dropdown-menu {
  min-width: 0;
  margin-top: 0;
  font-size: 1em;
  border: 0;
  padding: 0;
  width: 100%;
  **word-break: break-word;**
}

Don't know if this breaks other things.

![image](https://user-images.githubusercontent.com/26098260/104923309-2aa29380-599c-11eb-8bad-136f51af87bb.png)

**Comment by daattali** [comment]
In your case specifically, by chance, the length of the word is only slightly more than the given space, so if you force it onto one line it looks normal. But if you add any more letters to the word "software" you'll see what this breaks - it will put everything on one line. It's not the correct solution.

**Comment by manelrodero** [comment]
I understand. But I don't know how to solve for everyone because I'm not a programmer :-/. I hope some BJ user can solve this problem.

A "solution" for my case without changing any CSS would be changing the "ABOUT" title for something larger. As the menu width seems to be related to width of top menu, then "SOFTWARE" will fit.

In default bootstrap, menus seems to adapt to the larger item on it like in this screenshot:
![image](https://user-images.githubusercontent.com/26098260/105094546-bacc0000-5aa4-11eb-9a1d-dc9c2ca60b13.png)

**Comment by daattali** [comment]
That's right, fixing it for one case is easy, but having a general solution that works for all cases is the difficult part. As my first comment mentions, I'm not sure why bootstrap menus seem to adapt in the documentation but not here - and would be happy if someone had half an hour to take a look and fix.

**Comment by manelrodero** [comment]
Sorry, I tried to fix it myself overwriting CSS without success.
I hope someone knows how to solve this for everyone.

In the meantime, I've used this workaround, define About menu item using an extra space like this:

```
"About ":
   - Me: "about/me"
   - Software: "about/software"
```

This does the trick for my page but obviously is not the solution.

**Comment by daattali** [comment]
Note that a solution like that may work on your specific device but because
you're relying on the precise width of a font, it might not look the same
on other devices.

**Comment by daattali** [comment]
@manelrodero this has now been fixed

**Comment by dagnelies** [comment]
Hmmm... I would make it the default ...but I can live with that. Thanks for merging.

**Comment by daattali** [comment]
@dagnelies I chose not to make it the default because it's not necessarily always the more desireable behaviour. If a word is breaking up then it would probably be better to use this feature, but if a title is made of multiple words, I'd say that the old behaviour is better. See https://beautifuljekyll.com/ as an example - the old way is better in my opinion.

Old:

![image](https://user-images.githubusercontent.com/952340/180238566-061da926-d1f6-4fff-8f46-e31af60603f7.png)

New:

![image](https://user-images.githubusercontent.com/952340/180238319-89abff00-5ae9-4262-9c8b-47b84d5aa630.png)

**Comment by manelrodero** [comment]
Better late than never.

I am now deploying version 6.0.1 and have added this option to remove my workaround.

Thank you for this feature and sorry for the delay in answering.
