### ISSUE TITLE
$.Ajax not available in staticman.js

### ISSUE THREAD

**Issue by sidharthramesh** [daattali/beautiful-jekyll#766]
When trying to submit comments through staticman, the form posts to the same page and results in a 405 not allowed (since github doesn't allow posts)

The error on the console is:
```
staticman.js:14 Uncaught TypeError: $.ajax is not a function
    at HTMLFormElement.<anonymous> (staticman.js:14)
    at HTMLFormElement.dispatch (VM494 jquery-3.5.1.slim.min.js:2)
    at HTMLFormElement.v.handle (VM494 jquery-3.5.1.slim.min.js:2)
```
Maybe the slim version of jQuery doesn't include ajax?
https://github.com/daattali/beautiful-jekyll/blob/fe0a48eea01d0351c8bff7473b5d58482da47da9/_includes/staticman-comments.html#L75-L81

As a result, none of these gets called, and the defaultAction of the form is to post on the same page. Which results in a 405 error.
https://github.com/daattali/beautiful-jekyll/blob/fe0a48eea01d0351c8bff7473b5d58482da47da9/assets/js/staticman.js#L13-L41

**Comment by daattali** [comment]
You're right, slim doesn't support Ajax. This is a bug, you can submit a PR

**Comment by sidharthramesh** [comment]
I saw your comment regarding including jQuery twice. How does this happen? I don't want to include it twice and make the page slower.

**Comment by daattali** [comment]
Generally staticman is included on the page when jQuery is already loaded
by beautifuljekyll. But in case you for some reason are using it on a page
that didn't load jQuery, we need to load jQuery for staticman

**Comment by sidharthramesh** [comment]
I like the fact that the pages load fast. However, I'm working on optimising it even more. 

Is $.ajax really required here? How about using fetch or axios here instead of the full version of jQuery? Including a very common version of jQuery from a CDN will be another alternative since it is almost a given that the browser will have a copy of it in its cache.

**Comment by daattali** [comment]
I'm not an expert in staticman. You can look at the staticman javascript file to see where/why it's needed

https://code.jquery.com/jquery-3.5.1.slim.min.js is the version that's being loaded and it's the officially recommended CDN by jQuery, are you saying that's not a good CDN?

**Comment by daattali** [comment]
Perhaps @VincentTam has something useful to say here

**Comment by VincentTam** [comment]
When I ported @<span>mmistakes</span>'s code, I was using the min version.  Tracing back the changes, I see that it has been replaced to a slim version at commit https://github.com/daattali/beautiful-jekyll/commit/5991966d38054938fa0506414b9f7e1c10946340#diff-e9c677c6d71b6acd8eb0963e0e2a9bd997a86240a3711c2d391c42d18eb12c32.

I'm learning JavaScript, and I'll know `$.ajax` in a month or so.

> Is $.ajax really required here? How about using fetch or axios here instead of the full version of jQuery?

AFAIK, it's possible to use [Staticman without jQuery](https://vincenttam.gitlab.io/post/2019-08-05-staticman-script-in-pure-js/).

**Comment by daattali** [comment]
You're right looks like I'm at fault for slim-mifying jquery. When I refactored I noticed that slim version is fine for all the parts of the site that I built, I didn't think to consider staticman. Let us know when you find out

**Comment by VincentTam** [comment]
I respect your decision to use slim.  I'll soon search for the functional difference between the two versions of jQuery.  As @<span>onweru</span> has worked out a pure-JS implementation of Staticman integration in his Hugo theme for which I has been invited to a collaborator (c.f. the 2nd external link in my previous comment), it would be nice if I can decipher his code and find a slimmer version.  Lemme try this this/next week-end.

**Comment by VincentTam** [comment]
@sidharthramesh @daattali I've fixed the code a few days ago by replacing `$.ajax` method with `fetch()` in standard JS.  Please verify and merge, so that the reported problem would be fixed.

P.S. Staticman officially updated its website to include setup guide for v3 yesterday.  https://staticman.net

**Comment by sidharthramesh** [comment]
Hey @VincentTam thank you! I considered using fetch as well, however not all browsers support it. Especially IE. So perhaps a solution using XHR will be better for comparability? Axios can be another alternative. What do you think @daattali ?

**Comment by VincentTam** [comment]
@sidharthramesh Thanks for suggestion.  I prefer your way.  I've worked it out.  Please verify.

**Comment by sidharthramesh** [comment]
Great work @VincentTam. I'll be testing it and using this PR on my fork. @daattali please consider merging and closing this issue.

**Comment by VincentTam** [comment]
> Hey @VincentTam thank you! I considered using fetch as well, however not all browsers support it. Especially IE.

I'm posting links to MDN docs about the browser compatibilities for quick reference.

1. https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility no IE support :sob: 
2. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#browser_compatibility
  - `XMLHttpRequest()` constructor: 7
  - `onreadystatechange`: 5
  - `readyState`: 7
  - `readyState.constants`: 9
  - `send`: 5
  - `setRequestHeader`: 5

I've used `XMLHttpRequest.DONE` in my 2nd proposed PR, so the min version needed is IE9.  I prefer readability over a marginal gain of backward compatibility.  Who's using IE8 nowadays?

https://github.com/daattali/beautiful-jekyll/blob/ceb994a4e53283baacd0eb934f0601a267040156/assets/js/staticman.js#L20-L33

**Comment by daattali** [comment]
I think IE11+/edge is reasonable, anyone using IE10 or below is probably having problems with half the internet, so I wouldn't worry about that. Too bad that IE never implemented fetch support. I'm sorry for the long delay, will look at the PR now
