### ISSUE TITLE
Post header section doesn't show post title 

### ISSUE THREAD

**Issue by nvtrang91** [daattali/beautiful-jekyll#769]
Please help, 
My post does not show the title and subtitle and I couldn't find how to fix it. I kept the beautifuljekyll unchanged, just modified the _config file to no avatar, no title image.
![image](https://user-images.githubusercontent.com/35219743/105894869-57fbdb00-6047-11eb-9252-2071e2e324a9.png)

**Comment by daattali** [comment]
Sorry, I'm not able to help with personal issues. This area is only for bugs with the theme, not personal support. For individual help please use a general jekyll forum online or [a support plan](https://beautifuljekyll.com/plans/)
