### ISSUE TITLE
Formatting change suggestion: Long strings not wrapping

### ISSUE THREAD

**Issue by b-kennedy0** [daattali/beautiful-jekyll#787]
First, apologies, I am in no way a HTML/CSS expert, this is just a suggestion. 

Long strings (such as URLs) break the container in mobile view as they do not wrap. E.g
![image](https://user-images.githubusercontent.com/42816209/110516116-11e36e00-8101-11eb-9325-b87da7cb0cca.jpeg)

A quick search suggests a modification to CSS:
[https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)

**Comment by b-kennedy0** [comment]
Not sure if useful in any way, but I managed to coerce my own page to wrap by using HTML and adding CSS inline. E.g.
`<div style="overflow-wrap: break-word; word-wrap: break-word; -webkit-hypens: auto; -ms-hyphens: auto; -moz-hyphens: auto; hyphens: auto;">`

**Comment by b-kennedy0** [comment]
I _think_ so, yes. 

To be honest, I was hoping that somebody with **much more** experience than I would chime in here!

**Comment by daattali** [comment]
Let's give it some time and see if others are able to discuss and test. I'm very conservative about making changes that affect existing behaviour because of the huge number of people affected
