### ISSUE TITLE
cover-img is not working

### ISSUE THREAD

**Issue by Hax4us** [daattali/beautiful-jekyll#791]
Post Link : https://hax4us.github.io/2020-07-12-install-jedi-vim-termux/

Problem : Cover-img is not working

Source : https://github.com/Hax4us/Hax4us.github.io/blob/gh-pages/_posts/2020/2020-07-12-install-jedi-vim-termux.md

image is here : https://github.com/Hax4us/Hax4us.github.io/blob/gh-pages/assets/img/vimjedi_preview.jpg

**Comment by daattali** [comment]
I don't know what version of beautifuljekyll you're using. It must be very old. cover-img is only available for about a year if I recall (it was called something else before), I suggest re-installing from scratch if you want all the new features.

**Comment by Hax4us** [comment]
yes you were right :) btw old name of cover-img was bigimg
