### ISSUE TITLE
Rewrite history request

### ISSUE THREAD

**Issue by gpotter2** [daattali/beautiful-jekyll#796]
Hello,

Please rewrite the history of this repo to remove the mention to my name in https://github.com/daattali/beautiful-jekyll/commit/114170ba86429da3ea2f2b658656c4089eeb9c1d

I am aware that this is annoying, but I am getting *spammed* with notifications of non-technical people failing their rebase.. There is no way to disable notifications in all forks on github. I just end up blocking whoever pings me but it never stops... 😞

Thanks for the support

**Comment by daattali** [comment]
I'm really sorry, I'll try to look into this

**Comment by daattali** [comment]
If you know the exact procedure for this, feel free to let me know

**Comment by gpotter2** [comment]
You can do

```
git rebase -i <commit hash>
```

replace `pick` by `rename` on the commit, then rename the commit, finish the rebase.

Make sure you're using the latest up-to-date version because you'll have to force-push the changes (`git push -f`)

**Comment by daattali** [comment]
It scares me to tinker with git history, I'll do it if I have to do but I emailed github support for help to see if they can help

**Comment by gpotter2** [comment]
Heh; I can answer that.

```
Hi gpotter2,

Thank you for the information, it was very helpful!

As it turns out, this is expected behavior for the notification, but definitely annoying.

The reason for the notification was a direct mention remove gemfile lock as suggested by @gpotter2. This mention is part of the commit message and would trigger a notification to the mentioned username.

[...]

The final option is to have the commit message changed on that specific commit. Having usernames in commit messages is a bad practice and should be avoided. The details for that are below and would require write permissions to the repository.

https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages

If you can get a repository owner or admin to change that commit message that would be the easiest.
```

**Comment by daattali** [comment]
Rewriting the history also means that ALL commit SHAs since then will be modified, which is something I really wanted to avoid. Looks like we won't need to! Here's a message I received from support just now:

```
Hi Dean,

Wow, you're in luck! Just 4 hours ago the team made a slight change to the way the notification system works, and you should find that you collaborator has stopped getting those spammy notifications!

So it looks like you shouldn't need to rewrite the repository history after all!

If there's anything else I can do, give me a shout!
```

I'll leave this issue open until you can verify that this stopped

**Comment by gpotter2** [comment]
Hah, nice.
It's likely they followed suite on my request. They said they would ask the devs about that.
I'll keep you up to date and report if I get any

**Comment by daattali** [comment]
Can we close this?
