### ISSUE TITLE
Support Cloudflare analytics as alternative to Google + Matomo

### ISSUE THREAD

**Issue by artis3n** [daattali/beautiful-jekyll#797]
<https://support.cloudflare.com/hc/en-us/articles/360052685432-Cloudflare-Web-Analytics>

Happy to put in the PR myself as long as you approve, similar to Google where an account code is added to the config and inserted into a JS script template.

**Comment by daattali** [comment]
I didn't know cloudflare offered analytics! TLDR of how it's different from GA/why use it over GA? 

Is it getting traction? I only want to support popular tools

**Comment by artis3n** [comment]
They released it last year. It's main selling point (it's free) is privacy-preserving analytics.

https://blog.cloudflare.com/free-privacy-first-analytics-for-a-better-web/

**Comment by daattali** [comment]
Sure, I'll accept a PR -- I assume it will add one config file parameter and a _includes html file

**Comment by artis3n** [comment]
Yup!
