### ISSUE TITLE
Issues after updating content

### ISSUE THREAD

**Issue by jeromehanan** [daattali/beautiful-jekyll#802]
After updating contents on md files inside posts directory, Actions was successfully built but github.io page doesn't show me up anything. What actually happened was I've just updated the title of first post and push into master branch. Can you pls help me out to figure out the exact issue?? 

Below is the evidence for what was built 

![Capture](https://user-images.githubusercontent.com/37964809/116976625-09fa1180-acdf-11eb-9e3f-fa4db4fdf695.PNG)

**Comment by jeromehanan** [comment]
I found out the solution..

**Comment by daattali** [comment]
It might help other people in the future of you can add a comment about what the issue/solution was
