### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by jeromehanan** [daattali/beautiful-jekyll#803]
For development purposes, how to run on this on localhost? I've installed Ruby, RubyGem and Jekyll via Bundler? What to do then? I run this  `$ bundle exec jekyll serve ` on terminal, but I cannot see it working properly.

**Comment by daattali** [comment]
This is not a question specific to beautiful jekyll, and it isn't an issue or a feature requests, so I'm going to close this.

There are many instructions online about how to locally run jekyll themes, but it's out of scope for me to help individuals learn how to run jekyll locally.
