### ISSUE TITLE
Author information is missing from `<meta>` tag in HTML

### ISSUE THREAD

**Issue by tillgrallert** [daattali/beautiful-jekyll#816]
I just updated a [project website](https://openarabicpe.github.io) to the latest version of Beautiful Jekyll and it appears the `<meta>` tag for authorship information in the HTML header is empty even though the YAML for blog posts includes the relevant field.  One of the recent changes seemingly was to remove the general authorship information from `_config.yml` but I am not sure what is going on and what is the proposed use case/ workflow for including authorship information.

**Comment by tillgrallert** [comment]
After some poking around it is indeed the case that the `author` tag in the YAML for blog posts is ignored and everything instead relies on the `_config.yml`. Why is that?

**Comment by daattali** [comment]
Was "author" ever a supported YAML option?

**Comment by tillgrallert** [comment]
I thought it was. But then if you as the developer think it wasn't, I am most probably wrong.

**Comment by daattali** [comment]
Actually there's a `author` field in the config file. It's currently only used in the footer, but it would make sense to have it generate a meta tag for author as well. I'd be happy to accept a PR adding a meta tag for author

**Comment by tillgrallert** [comment]
Dear @daattali, this is already the case. `<meta>` tags for author are generated based on the `author` field in the config file.

**Comment by daattali** [comment]
Ah yes, looks like it is there. So if the author is supported in the config file, can we close this issue? Or do you have a different feature request?

**Comment by tillgrallert** [comment]
I think, we can close this issue. I will probably submit another feature request for the support of the author tag in the YAML block of individual posts.
