### ISSUE TITLE
Website in two languages

### ISSUE THREAD

**Issue by leopqrz** [daattali/beautiful-jekyll#837]
Hi, sorry if this is a silly question, but this is my first time creating a website.
How is the easiest way to have a double website each in a different language (Portuguese and English)?
ps. Using the beautiful-Jekyll

**Comment by daattali** [comment]
Beautiful jekyll doesn't have such a feature. I suggest googleing for ideas on how to have a multi-language jekyll site, or perhaps asking on social media/online forums for how to do that. It seems like a generic jekyll question, not specific to this theme
