### ISSUE TITLE
Add support for Polywork icon in the footer

### ISSUE THREAD

**Issue by VMois** [daattali/beautiful-jekyll#850]
I have recently got access to a [Polywork](https://www.polywork.com) and want to put my Polywork link on my personal website (of course, powered by `beautiful-jekyll`). There is already support for LinkedIn, Twitter, etc. icons in the footer. I would like to add support for the Polywork icon too.

Polywork has freely available icons [here](https://drive.google.com/drive/u/0/folders/1LpVFyw8rsxggJwdi_gTslglOofvorKCY).

What do you think? Will any additional design work be needed for Polywork icons? If not, I think I can work on the coding part.

Thank you.

**Comment by daattali** [comment]
Any icon that is supported by fontawesome can be included. You can see the list of icons they currently support here https://fontawesome.com/v5.15/icons

They do continuously add new ones, so perhaps one day if polywork will become popular enough they'll add their icon. You can also request fontawesome to add polywork's icon to their library.

If the icon is not on fontawesome, I won't be able to add it to the template's footer, but of course the template is open source so you can always modify it yourself to manually add your own. It just won't be using the framework that all the other icons use, you'll need to know a bit of HTML and jekyll to add it to your site.

**Comment by VMois** [comment]
I found the request for the PolyWork icon - https://github.com/FortAwesome/Font-Awesome/issues/18038. If anyone is interested in the icon, please, go to the request and hit "thumbs up".

**Comment by daattali** [comment]
When it gets added, feel free to open an issue here again
