### ISSUE TITLE
Specific changes in _config.yml are not reflecting

### ISSUE THREAD

**Issue by VVVFO** [daattali/beautiful-jekyll#86]
I have changed the "title" field along with some other things in the _config.yml, but the title of the webpage is still shown as "My Website" as the default, while other changes has been reflected. For reference, the webiste: [vvvfo.github.io](https://vvvfo.github.io)

**Comment by VVVFO** [comment]
Changed index.html and it functioned correctly, so what is the function of the "title" field and "description" field in the _config.yml?

**Comment by daattali** [comment]
The `title` param in the config variable is what's responsible for the text on the top left of every page.  Sometimes jekyll behaves weird and doesn't update for a while and you just need to make any other change to any other page just to force it to update.  The `title` param in `index.html` is responsible for the title of the actual page itself (the big centered text below the navigation bar)
