### ISSUE TITLE
Both a website title and an image logo in the navigation bar. 

### ISSUE THREAD

**Issue by matanmus** [daattali/beautiful-jekyll#865]
Hello Dean.

Beautiful Jekyll is really great and helpful. I was wondering if it is possible to have both a website title and an image logo in the top-left corner of the navigation bar. Within _config.yml I could not manage to do it.

Thank you,
Matan

**Comment by matanmus** [comment]
Hello Dean. 

Beautiful Jekyll is really great and helpful. I was wondering if it is possible to have both a website title and an image logo in the top-left corner of the navigation bar. Within _config.yml I could not manage to do it.

Thank you,
Matan

**Comment by daattali** [comment]
That's not possible out-of-the-box. You can probably modify the source files yourself to achieve that - you'd have to modify `_includes/nav.html` and the css file. (And of course you'll need to know basic CSS and HTML to be able to do that :) )
