### ISSUE TITLE
Any chance of a new release?

### ISSUE THREAD

**Issue by sparkertime** [daattali/beautiful-jekyll#870]
For those of us on the remote theme option, any chance of a new release? I'd love to get the search features that were added in May

Thanks!

**Comment by daattali** [comment]
Yes, a new version is definitely due. I just spent this past weekend upgrading another project of mine, I'll try to release this next time I find a free day

**Comment by aperezbios** [comment]
@daattali  ping, any chance we can get a new release? It's been a while.

**Comment by dfreilich** [comment]
I'd also love to see a new release! I'm a big fan of the fact that it's OSS, and it would be great to see some of the advances over the past two years be made available for the different forms of installation.

**Comment by daattali** [comment]
I apologize for the VERY long wait. I finally released a new version today. I spent the last few days on updating the documentation and making sure everything works well. You can see https://beautifuljekyll.com/updates/ for a list of updates.
