### ISSUE TITLE
giscus support

### ISSUE THREAD

**Issue by patgarz** [daattali/beautiful-jekyll#886]
I'm reaching the finishing stages of adding [giscus](https://giscus.app) comments support for my Beautiful Jekyll site. If you're not familiar, giscus is what I would consider the "spiritual successor" to utterances as it uses GitHub Discussions rather than GitHub Issues for its comments.

Do you have any interest in me putting together a PR to add that functionality? Setup is almost identical to utterances so I don't think it adds much, if any, complexity (apart from a slightly longer config file).

**Comment by patgarz** [comment]
To any consumer, yes. For anyone wanting to dive into the site code, they'll also find the `giscus-comment.html` included in `_includes` and a reference in `comments.html` (nearly identical to utterances).

I'll go ahead and put together the PR and link it here so you can see the exact diff - should be able to do that after I'm off work this evening.

**Comment by daattali** [comment]
Closign the issue, as it's already in a PR
