### ISSUE TITLE
Avatar icon disappearing instead of fading on mobile scroll.

### ISSUE THREAD

**Issue by cyaris** [daattali/beautiful-jekyll#902]
Experiencing this on mobile only and actually haven't been able to replicate it while testing mobile functionality on my laptop. Only seen only while using a browser from my mobile phone.

https://user-images.githubusercontent.com/35279417/142740207-59de8c1b-d73a-4bd8-8c1b-cafdd1de4cf7.mov

**Comment by daattali** [comment]
It's most likely an issue with the specific browser you're using. Is that Chrome or some other major browser, or is it a simple default browser?

**Comment by cyaris** [comment]
Using Google Chrome on mobile.

**Comment by daattali** [comment]
What's the url? So i can try

**Comment by cyaris** [comment]
My domain is https://cyaris.github.io/. I'm not seeing the issue anymore but before posting I made sure to check https://beautifuljekyll.com/ and it was occurring there too.

**Comment by daattali** [comment]
If you're not seeing it anymore, it might have been a temporary bug with your phone/browser? I've never experienced this and I've been looking at beautifuljekyll sites daily for 6 years :) Closing this issue, feel free to reopen if needed
