### ISSUE TITLE
If previous or next page title has "", pagination links get broken.

### ISSUE THREAD

**Issue by alperyazar** [daattali/beautiful-jekyll#906]
On my blog, one page has `""` characters at the title. The post before and after that page have invalid next and previous links.

Cause:
https://github.com/daattali/beautiful-jekyll/blob/71824e526850c971e95cffc3f36ee0c071bfa781/_layouts/post.html#L70
https://github.com/daattali/beautiful-jekyll/blob/71824e526850c971e95cffc3f36ee0c071bfa781/_layouts/post.html#L75

Example:

` <a class="page-link" href="{{ page.previous.url | relative_url }}" data-toggle="tooltip" data-placement="top" title="{{page.previous.title | strip_html | xml_escape}}">&larr; Previous Post</a>`

`title="{{page.previous.title | strip_html | xml_escape}}"` renders into `title="test"title""` if title of the page is `test"title"`. Firefox still works but highlights the link in red when I check the source HTML. The problem is [HTMLProofer](https://github.com/gjtorikian/html-proofer) returns error and my CI pipeline fails. Of course I will change double quotes to single quote to avoid the error but fixing in the theme is a better solution.

I quickly checked Liquid filters but couldn't find a proper filter for this situation (escaping `"""`).

**Comment by daattali** [comment]
Can you show me the exact YAML for the page? I just tried placing quotes in a page title and it seems to work for me.

**Comment by alperyazar** [comment]
Oh, my mistake! I am using version 5.0.0 but I mistakenly thought that I was using the latest. Looks like problem has been already fixed in 505305ebe7c1f1e8a2b11cdd6582619fd5f745ab.
