### ISSUE TITLE
Add a favicon for the website

### ISSUE THREAD

**Issue by zhichucode** [daattali/beautiful-jekyll#910]
I want to add a favicon. I write this in the `_config.yml`
`favicon: /assets/img/favicon.ico`
but it doesn't work.

**Comment by daattali** [comment]
That isn't meant to work, did someone/somewhere claim that the config file accepts a favicon parameter?

See here https://beautifuljekyll.com/faq/#favicon

**Comment by zhichucode** [comment]
Thank you for your help.
