### ISSUE TITLE
Add Copy-to-Clipboard feature

### ISSUE THREAD

**Issue by MohamedAliRashad** [daattali/beautiful-jekyll#923]
I want my blog readers to be able to copy code directly from the website. can a feature like this exist ?

https://www.aleksandrhovhannisyan.com/blog/how-to-add-a-copy-to-clipboard-button-to-your-jekyll-blog/

**Comment by daattali** [comment]
The code sections in this theme are simple HTML code blocks, they aren't the fancy ones that have interactive features. You can add this yourself if you're very savvy with HTML/javascript, but it's not going to be a built in feature here.
