### ISSUE TITLE
Building (even with a fresh fork) fails.

### ISSUE THREAD

**Issue by tatewilhelm** [daattali/beautiful-jekyll#924]
This is issue with building on my personal website I already have worked on, and a new fork.

When I push commits, the actions return the following:

Beautiful Jekyll CI
```
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: beautiful-jekyll-theme (= 5.0.0) and beautiful-jekyll-theme (>= 0). Bundler cannot continue.

 #  from /srv/jekyll/Gemfile:5
 #  -------------------------------------------
 #  gem "beautiful-jekyll-theme", "5.0.0"
 >  gemspec
 #  
 #  -------------------------------------------
```

pages build deployment:
```
Run actions/deploy-pages@v1-beta 

7Actor: github-pages[bot] 

8Action ID: 1617403395 

9Artifact URL: https://pipelines.actions.githubusercontent.com/eJtK52eQJDfWlYnYl2I26eAutCdlLkRfE6zG3lFIlK69UQRi42/_apis/pipelines/workflows/1617403395/artifacts?api-version=6.0-preview 

10{"count":0,"value":[]} 

11Failed to create deployment for ebb488cbcdb1a6fae0af85e7bc378413440a642c. 

12Error: Error: No uploaded artifact was found! 

13Error: Error: No uploaded artifact was found!

```

This applies to both a new template and one that has been used for a while.

Repositories I used:
[tatewilhelm.github.io.old](https://github.com/tatewilhelm/tatewilhelm.github.io.old) 
[tatewilhelm.github.io](https://github.com/tatewilhelm/tatewilhelm.github.io)

**Comment by daattali** [comment]
I'm not seeing any problems, I just tried creating a site in a few different methods and had no issue. Please outline all steps to reproduce your issue.

**Comment by tatewilhelm** [comment]
Oops found the issue. I apparently specified the theme for some reason on my original config.yml and I just added it to the new repository thinking it wasn't the one causing the issue. 

Sorry, but thanks for your time still.
