### ISSUE TITLE
Update copyrightyear

### ISSUE THREAD

**Issue by cskartikey** [daattali/beautiful-jekyll#926]
I know this will be a bit pedantic but I love the project and just want to remind you to upload the copyright year to 2021
![image](https://user-images.githubusercontent.com/64925909/147887886-12e1c1b4-7d17-4410-a048-8e11bd2c1c81.png)

**Comment by daattali** [comment]
Thanks! It will actually update automatically to the current year when any change is made to the website. I'll do that right now, thanks for the reminder!
