### ISSUE TITLE
dark theme toggle by default (n00by suggestion)

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [daattali/beautiful-jekyll#932]
i just thought that now its only light theme by default. wouldnt it be better to also add a toggle at top-right corner to have a theme toggle? i know its already possible while modifying some config files but also - wouldnt it be a good idea? recently dark theme is common... (also detecting default OS theme at first opening of page , github-like , they catch this setting)

**Comment by daattali** [comment]
Dark theme is available as a [plan](https://beautifuljekyll.com/plans/) - feel free to check that out!

**Comment by hacknorris-aka-penguin** [comment]
like always - to code locally...
