### ISSUE TITLE
modifying theme of navigation buttons

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [daattali/beautiful-jekyll#936]
for the now everything i can modify is text in buttons. just imagie - someone know how to read config file and want to make all the site in dark theme (not mode, not toggle). and how it looks - just see ↓ 
![Screenshot from 2022-02-11 12-36-39](https://user-images.githubusercontent.com/97974194/153585312-bd0e5b0b-07ac-46ce-b1fd-f20bd60fe799.png)

white background both with white text. unreadable. will someone add this feature to control nav buttons fully? 

also - it'd be good to be able to frame posts in feed... (and control colors of it ;p)

**Comment by daattali** [comment]
You can use your own css for that - the config file only has explicit parameters for the most common items but it's not feasible to put everything in there. If you don't know css and need help learning how to modify a specific button, you can ask on a beginner CSS forum for help

**Comment by hacknorris-aka-penguin** [comment]
any apis for that?

**Comment by daattali** [comment]
There is no such thing as an API in HTML/CSS. Please request help in an appropriate forum

**Comment by hacknorris-aka-penguin** [comment]
no, i meant - what is class on these buttons, what is class of search bar, what is class of post text? hope ya understand... everything coded into markdown/xml , not html and you dont show publicly classes of objects... there are no docs for css/js ... only for xml files and 'n00by' usage

**Comment by daattali** [comment]
I don't know off the top of my head. I would have to investigate by looking at the DOM. I suggest learning basic CSS if you want to do modifications, there's no way around that.

**Comment by hacknorris-aka-penguin** [comment]
arent buttons in classes ? or having id's ? i really need to lurk in browser inspector?
