### ISSUE TITLE
better mastodon support

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [daattali/beautiful-jekyll#937]
could you guys modify link to mastodon accounts if he own to include rel="me" to verify profiles? 

docs why and how - here : https://docs.joinmastodon.org/user/profile/#verification

**Comment by daattali** [comment]
It was actually done a few days ago. The new version has this.

**Comment by hacknorris-aka-penguin** [comment]
paid one? free doesnt or i have old one...

**Comment by hacknorris-aka-penguin** [comment]
paid one? free doesnt or i have old one...

**Comment by daattali** [comment]
It's in the regular free version.
