### ISSUE TITLE
External font appearing only on main/home page

### ISSUE THREAD

**Issue by vignesh99** [daattali/beautiful-jekyll#942]
I was initially trying to find out how to add 'Computer Modern Serif' font to my webpage and described the issue I was facing [here](https://stackoverflow.com/questions/71198520/adding-computer-modern-serif-to-jekyll-github-page). With help, I found a partial fix by adding the following code in my `assets/css/beautifuljekyll.css` file.
```
@font-face {
	font-family: 'Computer Modern Serif';
	src: url('./fonts/Serif/cmunrm.eot');
	src: url('./fonts/Serif/cmunrm.eot?#iefix') format('embedded-opentype'),
		 url('./fonts/Serif/cmunrm.woff') format('woff'),
		 url('./fonts/Serif/cmunrm.ttf') format('truetype'),
		 url('./fonts/Serif/cmunrm.svg#cmunrm') format('svg');
	font-weight: normal;
	font-style: normal;
}

body {
  font-family: 'Computer Modern Serif',sans-serif;
```
However, the 'Computer Modern Serif' font is being reflected only in the home (index.md) page and not on the other pages (all of them have the same `layout : page`. After this, I added the bold font face code (given below) into the `assets/css/beautifuljekyll.css` file and all the [font files](https://www.checkmyworking.com/cm-web-fonts/#serif) into the `assets/css/` folder. When reloaded, all the other pages become 'Computer Modern Serif' **bold** font, but the home page remained normal.
```

@font-face {
	font-family: 'Computer Modern Serif';
	src: url('./fonts/Serif/cmunbx.eot');
	src: url('./fonts/Serif/cmunbx.eot?#iefix') format('embedded-opentype'),
		 url('./fonts/Serif/cmunbx.woff') format('woff'),
		 url('./fonts/Serif/cmunbx.ttf') format('truetype'),
		 url('./fonts/Serif/cmunbx.svg#cmunbx') format('svg');
	font-weight: bold;
	font-style: normal;
}
```
I want to find a way where all the pages become 'Computer Modern Serif' normal (without bold) font. What do I do to fix this? I believe this is specific to this jekyll design. You can visit my [repo](https://github.com/vignesh99/vignesh99.github.io) to take a look at the current files.

**Comment by daattali** [comment]
Whatever you add to `beautifuljekyll.css` will indeed be reflected on all pages, but I'm not an expert on how fonts work, I don't know the answer to this.

**Comment by vignesh99** [comment]
Hello @daattali  , the problem is that it is not working as it should, which is change uniformly (unbold font) on all pages. Can you please check if this issue occurs when you also add this font? This is not about how fonts work, but it is about why it does not work the same on all the pages - something specific to your page's design.
Also, can you keep this issue open in case some of the other contributors know a way to fix this?

**Comment by daattali** [comment]
This is more of a troubleshooting problem than an actual bug. You're dealing with CSS here, so you would need to look at the source or at the CSS browser of the pages that "don't work" and see if there are CSS rules that are overriding whatever you add in beautifuljekyll.css

The Issues tab is meant for bugs or feature requests, not for receiving personal help troubleshooting individual problems with custom modification, because that would ve a never ending fulltime job. This question belongs in the Discussion tab or in other jekyll forums.

**Comment by vignesh99** [comment]
I now understand the purpose this Issue section. Thanks for the replies.

**Comment by vignesh99** [comment]
@daattali one last request. Can you suggest someone who I can contact to help with this issue please?
