### ISSUE TITLE
Page not updating

### ISSUE THREAD

**Issue by Azizimj** [daattali/beautiful-jekyll#946]
The page does not update even after several days of a successful build. 

I updated my index.html a while ago but it does not update the io webpage after several days. Please let me know what could be a possible reason. I have tried editing the file on the github website. And also setting `future: true` in the _config.yml file.

**Comment by Azizimj** [comment]
NVM, it's the Github Pages new policy. (make it public to publish)

**Comment by daattali** [comment]
Closing this issue, but can you share a link that describes this new policy you're talking about?

**Comment by Beaty84** [comment]
I had the same issue. I was making commits both locally and on GitHub and my site wasn't getting updated. Nothing seemed to work for me but here's the solution.
~I merged the gh-pages branch to the master branch where I was making my commits
~I then made gh-pages branch the default branch 
On refreshing, everything run as expected.
