### ISSUE TITLE
The excerpt is not generated correctly by GitHub actions when publishing to a GitHub page

### ISSUE THREAD

**Issue by martijnvanschie** [daattali/beautiful-jekyll#955]
Hi,

I noticed that the `excerpt` (or `excerpt_length`) is not correctly honored on GitHub pages.

I took a copy from your repo so i was sure i got the latest version. Then I added my test post and generated it locally. The excerpt is shown and contains the default number of words (50).

After i published it to GitHub Pages the page is automatically generated by a GitHub actions bot. The result is that the word count was only 1. It only took the first header from the post and not the rest.

Any idea what could be wrong?

Regards.

**Comment by daattali** [comment]
Could you please share a reproducible example or point us to your source code and generated website please.

BTW your title says "GitHub actions" but the description doesn't mention Actions

**Comment by martijnvanschie** [comment]
Hi, 

Please find below the output of the generated blog over where the excerpt would be show. As you can see the excepts only contains one word instead of the default 50.

https://martijnvanschie.github.io/blog/

Source code is here:
https://github.com/martijnvanschie/blog/blob/master/_posts/2022-02-02-process-azure-subscription-system-topics-using-azure-function.md

Reason i mentioned GitHub actions in the title is because when pushing content to a GitHub page publishing branch GitHub actions is actually triggered behind the scenes and generating the page. 

My locally generated pages does have the expected number of words so there is a difference between local generated and generated using GitHub Actions. That was the main reason. I will change the title to hopefully make this more clear.

Thanks in advance.

**Comment by daattali** [comment]
Excerpts in jekyll take the first paragraph. When your post starts with a header, that header counts as the first paragraph.

If you used 

```
# Introduction to the post
```

as the first line in the post, then that entire line (4 words) would be the excerpt. If you google for this online you'll see that this is how excerpts work. I don't know why you get a different behaviour when running locally, I get the correct behaviour locally, but I'm closing this as a non issue.

**Comment by martijnvanschie** [comment]
Oker, thanks for the feedback. I'll try that.
With regards to the different behavior, this seems more an issue for Jekyll itself, i guess? Or even GitHub actions.
