### ISSUE TITLE
Assets not loaded on GitHub Pages with Forking method

### ISSUE THREAD

**Issue by nattadasu** [daattali/beautiful-jekyll#971]
Hello!

Recently I've forked this repo for [my blog site](https://nattadasu.my.id). However, after GitHub Action generated Pages, top navbar did not load properly. I thought it broke because I deleted some lines from `_config.yml`, but nope, triple checked my commit (b0e48809ba9e9f3bb124d07befcb7b0f3016a894) and I only deleted:
```diff
 navbar-links:
   About Me: "aboutme"
-  Resources:
-    - Beautiful Jekyll: "https://beautifuljekyll.com/"
-    - Learn markdown: "https://www.markdowntutorial.com/"
-  Author's home: "https://deanattali.com/"
```
So as I write this issue, I absolutely clueless what happened to the Pages, even I did disable/comment out some stuff like comment and analytic.

I checked if issue reproducible/shown on another gadgets, and it's still there. My oversea friend confirmed this too.

The repo for the blog site is [nattadasu/nattadasu.github.io](https://github.com/nattadasu/nattadasu.github.io).\
I also use Cloudflare for DDoS protection.

**Comment by daattali** [comment]
I just tried forking a fresh copy and even did the same commit you did: https://github.com/daattalitest/daattalitest.github.io/commit/8ea19cbedf4b47ad93e0d07a007c595bcd8f9fbf

The result is fine https://daattalitest.github.io/

I think it's a problem with your hosting or CDN. If you look at your page source, for example the css file that's trying to load is https://nattadasu.my.id/assets/css/beautifuljekyll.css but when you try to load it it redirects to https://cda.nattadasu.my.id/css/beautifuljekyll.css which is a 404. My guess at this point is that this is not a beautifuljekyll or github issue
