### ISSUE TITLE
404 error when baseurl not present in _config.yml

### ISSUE THREAD

**Issue by pjakobsen** [daattali/beautiful-jekyll#990]
Reproduce; follow the 3 simple steps very carefully, and perhaps observe 404 error.   (That drove me nuts for about 2 hours as I kept forking and following 3 steps again and again and on two Github accounts, but to no avail)

Possible Solution: Look carefully at video and notice that @daattali  has a `baseurl: ""` in his  _config.yml  -  Once I added this to the forked _config.yml file,  it solved the problem.

I would consider this bug critical, but perhaps you are unable to reproduce it?

**Comment by daattali** [comment]
The baseurl config used to be needed a long time ago but it was removed. I never got around to making a new video.

Please post the exact steps to reproduce the issue

**Comment by pjakobsen** [comment]
Bizarre.  I asked my friend to follow steps 1,2,3 on his Github repo, and it worked like a charm.  The only think I can think of is that since my Github account is very old, it may be running different versions of Jekyll.  Since this "bug" can't be reproduced consistently, I will close ticket.  And thanks for your quick responses (I wonder looking at your site if you are a windsurfer or kiteboarder!)
