### ISSUE TITLE
Is it possible to create side menu bars with this theme?

### ISSUE THREAD

**Issue by thulasis** [daattali/beautiful-jekyll#994]
Hi Daattali,

Is it possible to create or does it supports a side menu or automated table of contents for the posts we create with markdown or html? If possible let me know the ways.

Thanks,
Tulasi

**Comment by daattali** [comment]
No this is not supported. I create table of contents manually. You may be able to google to find online tools that create one automatically maybe.

**Comment by thulasis** [comment]
Okay..
Thank you
