### ISSUE TITLE
Maximum utilization of screen size for text (100% width)

### ISSUE THREAD

**Issue by vignesh99** [daattali/beautiful-jekyll#995]
Hello,
Currently the screen width is not fully covered by the text in my blog. I am looking for something as described [here](https://stackoverflow.com/questions/53874469/how-to-make-maximum-utilization-of-the-screen-space-in-my-web-page-generated-fro). Unfortunately I am unable to locate these files and make the changes.

Can you please tell me what changes I need to make in which files so that my content-width can be made 100%? Thanks.

**Comment by daattali** [comment]
Please see [FAQ & Support](https://github.com/daattali/beautiful-jekyll#faq-and-support). I cannot provide individual support. For personal help you may either request support from the entire community/internet on public forums, or purchase a plan to receive help.
